### PR TITLE
[14.0][FIX] product_route_profile: Wrong inverse profile id

### PR DESCRIPTION
**Pull request by awisky**
- fix _inverse_route_ids to store the selected route_profile_id

### CODE REVIEW

**Review by bosd — APPROVED** [review]
LGTM

**Comment by bosd** [comment]
@espo-tony Can you leave a review?

**Comment by awisky** [comment]
@bosd I didn't push the change here yet. As it is failing a test in stock_request, I removed the change.

**Comment by bosd** [comment]
@awisky Have you seen this PR?
Also adresses some changes on the inverse
https://github.com/OCA/stock-logistics-warehouse/pull/1547/files

**Comment by awisky** [comment]
@bosd I checked it, it has the same issue we are trying to solve.
I think I found a workaround, as we have the issue during the creation of the product, I avoid the inverse method with a flag. 
I couldn't reopen the PR so I created another here, which looks fine
https://github.com/OCA/stock-logistics-warehouse/pull/1689

**Pull request closed without merging**
