### PR TITLE
[16.0] [MIG] stock_available_immediately

### PR DESCRIPTION
**Pull request by marielejeune**

### CODE REVIEW

**Comment by rousseldenis** [comment]
Don't merge this as it should be switched to new stock-availability repo

**Comment by marielejeune** [comment]
depends on https://github.com/OCA/stock-logistics-warehouse/pull/1495

**Review by pierre-halleux — APPROVED** [review]

**Comment by rousseldenis** [comment]
Should change to https://github.com/OCA/stock-logistics-availability

**Comment by marielejeune** [comment]
Moved to OCA/stock-logistics-availability. See https://github.com/OCA/stock-logistics-availability/pull/1

**Pull request closed without merging**
