### PR TITLE
[10.0][mig] account_move_line_product

### PR DESCRIPTION
**Pull request by LoisRForgeFlow**
Basic migration to v10.

### CODE REVIEW

**Review by JordiBForgeFlow — APPROVED** [review]
:+1: Technical and functional review.

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: LGTM

**Review by gmeficent — APPROVED** [review]
Functional review :+1:

**Review by MiquelRForgeFlow — APPROVED** [review]
fine :+1:

**Comment by lmignon** [comment]
@pedrobaeza your super power will be appreciated on this one :smirk:

**Review by lmignon — APPROVED** [review]

**Pull request merged**
