### PR TITLE
[10.0][ADD] stock_orderpoint_manual_procurement_uom

### PR DESCRIPTION
**Pull request by LoisRForgeFlow**
Stock Orderpoint Manual Procurement UoM
=================================

Glue module for ``stock_orderpoint_uom`` and ``stock_orderpoint_manual_procurement``

cc @rousseldenis @jbeficent

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
Pending:
* [x] : fix tests
* [x] : depends on https://github.com/OCA/stock-logistics-warehouse/pull/360

**Comment by jgrandguillaume** [comment]
Hi @lreficent 

https://github.com/OCA/stock-logistics-warehouse/pull/360 has been merged

**Comment by guewen** [comment]
Hi @lreficent, what's the state of the tests? Still pending? Travis seems happy

**Comment by LoisRForgeFlow** [comment]
Hi @guewen just did a test with more sense, now it is good from my side!

**Comment by LoisRForgeFlow** [comment]
Just squashed commits. Some kind :+1: ?

**Review by rousseldenis — APPROVED** [review]
Code review. LGTM

**Review by rgarnau — APPROVED** [review]
LGTM :+1:

**Review by MiquelRForgeFlow — APPROVED** [review]

**Pull request merged**
