### PR TITLE
[16.0] [MIG] stock_quant_expiration_date_tree: Migration to 16.0

### PR DESCRIPTION
**Pull request by AdrianaSaiz**
Standard migration

### CODE REVIEW

**Review by aitoreizmendi — APPROVED** [review]

**Review by aitoreizmendi — APPROVED** [review]
Technical review LGTM

**Comment by imoralesc** [comment]
Hi @AdrianaSaiz, I have performed a series of tests and the performance is as expected.

- From the model`stock.lot`
image

- From the model`stock.quant` 
image

**Review by RodrigoBM — APPROVED** [review]

**Comment by AdrianaSaiz** [comment]
Hi, could someone from @OCA/logistics-maintainers  check this PR?

**Review by hparfr — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
