### PR TITLE
[12.0] stock_request: allowed translating status values, model stock.…

### PR DESCRIPTION
**Pull request by alexeirivera87**
small adjustment to allow translating the status values of a stock request

### CODE REVIEW

**Comment by etobella** [comment]
This is not  necessary, odoo automatically detects this. On weblate, you can see that this values can be translated, as you can see in the screenshot for spanish
imagen

**Comment by rousseldenis** [comment]
> This is not necessary, odoo automatically detects this. On weblate, you can see that this values can be translated, as you can see in the screenshot for spanish
> imagen

Agree. This is not needed.

**Comment by alexeirivera87** [comment]
@rousseldenis 

Hello
I believe that what is being translated are the filters in the search views of stock.request and stock.request.order, not the values of the field state.

**Comment by alexeirivera87** [comment]
Hello @rousseldenis @pedrobaeza 

The values of the field state, are taken from a function which takes the values from a variable defined outside the class

`    state = fields.Selection(
        selection=_get_request_states, string='Status',
        copy=False, default='draft', index=True,
        readonly=True, track_visibility='onchange',
    )`

In the .po file, these are the filters in the search views of stock.request and stock.request.order, not the values of the field state:

#. module: stock_request
#: model_terms:ir.ui.view,arch_db:stock_request.stock_request_order_search
#: model_terms:ir.ui.view,arch_db:stock_request.stock_request_search
msgid "Cancelled"
msgstr "Annulé"

**Pull request closed without merging**
