### PR TITLE
[14.0][FIX] stock_request: Stock Request User can delete Stock Request

### PR DESCRIPTION
**Pull request by newtratip**
1. Setting user role to `Stock Request User`
2. Create Stock Request Order
3. Add Item Lines
4. Can not delete item lines
Selection_145

This PR is fix item lines should be delete by stock request user.

cc: @kittiu @ps-tubtim

### CODE REVIEW

**Comment by kittiu** [comment]
@newtratip The module intention is for stock manager to delete only, and not allow for stock user. I think this is by design since version 11.

I also don't know why it happen this way. But I think you should consult with the original author of this module, if you still want to proceed.

**Comment by newtratip** [comment]
@kittiu, There is PR for `Allow users to delete stock requests` https://github.com/OCA/stock-logistics-warehouse/pull/645 in V.11 and `Fix user can delete lines` https://github.com/OCA/stock-logistics-warehouse/pull/879 in V.12. we can cherry pick this one.

In V.11, V.12 we can delete stock request
In V.13, V.14 we can not delete stock request

I think we should fix it.

**Comment by kittiu** [comment]
> @kittiu, There is PR for `Allow users to delete stock requests` #645 in V.11 and `Fix user can delete lines` #879 in V.12. we can cherry pick this one.
> 
> In V.11, V.12 we can delete stock request
> In V.13, V.14 we can not delete stock request
> 
> I think we should fix it.

OK. Thanks for explaination.

**Review by kittiu — APPROVED** [review]

**Review by rousseldenis — APPROVED** [review]

**Review by HaraldPanten — APPROVED** [review]
LGTM

**Pull request merged**
