### PR TITLE
[ADD] [16.0] stock_valuation_layer_inventory_filter

### PR DESCRIPTION
**Pull request by Shide**
This module extends the Stock Valuation functionality to support grouping by Reference, filtering by Inventory Adjustments moves and filtering by Creation Date and allow you to obtain a more detailed Inventory Valuation.

https://www.loom.com/share/aa81a1b9f8b146b384c7186ae6180522?sid=8f357d53-422c-466e-af52-8398c2a6b053

MT-6661 @moduon @rafaelbn @yajo @fcvalgar @Gelojr please review if you want :)

### CODE REVIEW

**Review by fcvalgar — APPROVED** [review]
Functional review, 

LGTM thank you @Shide .

[OCA | stock_valuation_layer_inventory_filter QA Fran - Watch Video](https://www.loom.com/share/aa8e7ef1da904ddda993a1c4509ca3f4)

**Review by Gelojr — APPROVED** [review]
LGTM Thanks @Shide 

https://www.loom.com/share/3395a1cef9b44bacb516424042d30ac6?sid=16fb6d73-35e4-45fc-95ca-a631dcc02ac6

**Review by rafaelbn — APPROVED** [review]
Review film 👍🏼

**Pull request merged**
