### PR TITLE
[11.0][stock_account_inventory_force_date]

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
This module allows to post an inventory adjustment using a past date. 

If you use perpetual accounting, and standard cost method, the module will make sure that any future price changes are going to be revalued for the quantity that changed. The solution is not yet implemented for average or fifo costing.

### CODE REVIEW

**Comment by rousseldenis** [comment]
@jbeficent still WIP?

**Comment by rousseldenis** [comment]
@jbeficent

**Comment by JordiBForgeFlow** [comment]
@rousseldenis this is ready to review. 

cc @ageficent @lreficent @aheficent

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: Functional review

Created inv adjustment in the past with different price history:
-  inventory posted with past date and accounting entries created accordingly with the proper valuation

Created inv adjustment now:
- The last adjustment was taking into account

Set a lock date and try to post inventory in the past:
- Constraint raises

LGTM

**Comment by rousseldenis** [comment]
@jbeficent Travis is red now. Some modules were merged since the beginning of this PR. 11.0 branch is green. So, could you see what's wrong ?

**Review by HviorForgeFlow — APPROVED** [review]

**Pull request merged**
