### PR TITLE
[12.0][IMP] stock_quant_manual_assign: make quant search flexible

### PR DESCRIPTION
**Pull request by yostashiro**
This is to make it easier to manipulate with the domain conditions
and search results for available quants.

### CODE REVIEW

**Comment by rousseldenis** [comment]
@yostashiro Could you rebase ?

**Comment by rousseldenis** [comment]
@yostashiro Do you plan to forward port this ?

**Review by rousseldenis — APPROVED** [review]

**Comment by AungKoKoLin1997** [comment]
> @yostashiro Do you plan to forward port this ?

I will forward port this.

**Pull request merged**
