### PR TITLE
[8.0] stock_inventory_preparation_filter

### PR DESCRIPTION
**Pull request by pedrobaeza**
# More preparation filters for inventories

Includes more options for making an inventory out of:
- Multiple products.
- Products of a category.
- Multiple lots

It also allows to make an inventory based on scanned products, adding a line
with product code and quantity

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Added tests!

**Comment by oihane** [comment]
:+1:

**Comment by michaeljohn32** [comment]
:+1:

**Comment by guewen** [comment]
Not saw this before, but next time please pay attention to write the commit messages in english. Thanks

**Pull request merged**
