### PR TITLE
[MIG] stock_putaway_method in v15

### PR DESCRIPTION
**Pull request by stvn-vaidehi**

### CODE REVIEW

**Comment by rousseldenis** [comment]
@sts-vaidehi Tahnks for this. Could you please follow migration guide especially Full process part ? Thanks 

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0

**Comment by rousseldenis** [comment]
@sts-vaidehi

**Comment by nikul-serpentcs** [comment]
Supersede https://github.com/OCA/stock-logistics-warehouse/pull/1545

@rousseldenis @max3903  Can you please take a look?

**Comment by rousseldenis** [comment]
Closing this as no answer in favor of #1545

**Pull request closed without merging**
