### PR TITLE
[FIX] Decimal precision parameter

### PR DESCRIPTION
**Pull request by clonedagain**
Decimal precision parameter for products is 'Product Unit of Measure' in v7

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Why fixing an unported module?

**Comment by clonedagain** [comment]
There is a part that is ported: stock_available_immediately/product.py
The fix dates back to before the module was marked "unported": https://code.launchpad.net/~numerigraphe-team/stock-logistic-warehouse/7.0-fix-decimal-precision/+merge/223881
I hadn't managed to push it to github until today.

**Comment by clonedagain** [comment]
Looks like this fails on flake8 for an unchanged file.

**Comment by pedrobaeza** [comment]
OK, we can patch files waiting for a migration.

:+1:

**Comment by pedrobaeza** [comment]
That is unrelated, but if you want, go ahead to fix the branch.

**Comment by clonedagain** [comment]
Sorry @pedrobaeza I thought it was related, unfortunately I won't have time to flakeify the branch.

**Comment by pedrobaeza** [comment]
It's only one error, because the branch was already greeinify, but now there is another condition that it's being checked, but don't worry, we can do it in another PR.

**Comment by lmignon** [comment]
:+1:  LGTM. Thank you

**Pull request merged**
