### PR TITLE
[17.0][MIG] stock_mts_mto_rule: Migration to 17.0

### PR DESCRIPTION
**Pull request by milinsoft**

### CODE REVIEW

**Comment by milinsoft** [comment]
@pedrobaeza Could you please help? 
codecov checks failure does not make any sense here.

**Comment by pedrobaeza** [comment]
Just ignore Codecov. It's not mandatory. It's just an indication. Anyway, it may be correct and saying that not all the introduced code is covered in the tests.

**Comment by milinsoft** [comment]
> Just ignore Codecov. It's not mandatory. It's just an indication. Anyway, it may be correct and saying that not all the introduced code is covered in the tests.

Thank you for your prompt response!
If I understood you correctly, no actions need from my side, and this PR can be accepted without fixing codecov? 

At this point it shows `patch` issues for the lines that does not make sense to test, and I didn't even touch.
+ `project` shows warning regarding another module that I didn't touch as well.

**Comment by pedrobaeza** [comment]
Correct, you just need to wait for the reviews. But the don't come spontaneously is there is no interest in the module, or if you don't push it. You can review other PRs in this repository or similar ones, and ask in exchange that they review yours. Quid pro quo.

**Comment by milinsoft** [comment]
@OCA/core-maintainers please approve & merge

**Review by FrancoMaxime — APPROVED** [review]
LGTM: code review

**Comment by milinsoft** [comment]
> LGTM: code review

Thank you!
This is my first PR to OCA. 
How can I request it to be merged?

**Comment by FrancoMaxime** [comment]
> > LGTM: code review
> 
> Thank you! This is my first PR to OCA. How can I request it to be merged?

You have to wait more reviews and then a maintainer can merge it. You will have to be patient. If you need to include your PR in your code or in another PR you can check this documentation: https://github.com/OCA/maintainer-tools/wiki/Use-temporary-reference%28s%29-to-another-pull-request%28s%29

**Review by dreispt — APPROVED** [review]

**Review by vvrossem — APPROVED** [review]

**Review by antoniodavid — APPROVED** [review]

**Review by ShokaUladzislau — APPROVED** [review]

**Review by AgaevDanik — APPROVED** [review]

**Comment by rafaelbn** [comment]
Just if you like to know. Odoo actually in a MTO products, consume first from stock and if stock ends, then apply MTO. So in my opinion this module is only needed for really specific point. In my case, it is not needed any more! 😄 m2c

PD: This is from Odoo 16

**Review by micheledic — APPROVED** [review]

**Comment by rousseldenis** [comment]
> Just if you like to know. Odoo actually in a MTO products, consume first from stock and if stock ends, then apply MTO. So in my opinion this module is only needed for really specific point. In my case, it is not needed any more! 😄 m2c
> 
> PD: This is from Odoo 16

You're right. This has already been discussed in previous migrations. I don't know yet if Odoo has scheduled to fill this gap

**Comment by yung-wang** [comment]
This scenario does not work in MTO standard Odoo. So this module is still needed.

The virtual stock is more than 0 but less than ordered quantity
=> On part of the products will be taken from stock and a purchase order
will be created for the rest. So it will act like both make to order and make to stock rule.

> Just if you like to know. Odoo actually in a MTO products, consume first from stock and if stock ends, then apply MTO. So in my opinion this module is only needed for really specific point. In my case, it is not needed any more! 😄 m2c
> 
> PD: This is from Odoo 16

**Comment by micheledic** [comment]
Hello, can somebody merge? i need it in a prod env... i do not want to use the pr on our repo

**Comment by wedoo-justynar** [comment]
Hi,

I use MTS + MTO. Unfortunately, in v17 it doesn't work as it should. I verified on several Odoo.sh

I noticed the following problems:
- after mistakenly deleting the MTS+MTO rule, you cannot add a multi-company, you cannot add or change anything in warehouses, and often you cannot create a new warehouse.

Can I count on help and verification of the topic? Thank you very much and have a nice day.

**Pull request merged**
