### PR TITLE
[14.0][IMP] procurement_auto_create_group: auto_create_group for push rules

### PR DESCRIPTION
**Pull request by BernatPForgeFlow**

### CODE REVIEW

**Review by AaronHForgeFlow — APPROVED** [review]
Code review LGTM :+1:

**Review by JoanMForgeFlow — APPROVED** [review]
:+1: 
thanks!

**Comment by LoisRForgeFlow** [comment]
For reference: this was done in v15 during migration: https://github.com/OCA/stock-logistics-warehouse/pull/1300.

**Review by LoisRForgeFlow — APPROVED** [review]

**Pull request merged**
