### PR TITLE
[10.0][MIG] Port stock_orderpoint_generator to 10.0

### PR DESCRIPTION
**Pull request by willmakenoise**
Port stock_orderpoint_generator from 11.0 to 10.0

Nothing to do, besides changing version number in manifest.

### CODE REVIEW

**Comment by rousseldenis** [comment]
@willmakenoise Please check pylint (missing utf-8 headers)

**Comment by rousseldenis** [comment]
@willmakenoise You have to preserve commit history.

**Comment by willmakenoise** [comment]
I'll have to read up on git.. I'll see if I can fix this over the weekend.

**Comment by rousseldenis** [comment]
@willmakenoise Any news on this ?

**Comment by rousseldenis** [comment]
@willmakenoise

**Comment by rousseldenis** [comment]
@willmakenoise What's the status of this ?

**Comment by rousseldenis** [comment]
@willmakenoise Closing this as no answer. Please feel free to reopen it if applicable.

**Pull request closed without merging**
