### PR TITLE
[15.0][MIG] stock_request_purchase

### PR DESCRIPTION
**Pull request by BernatPForgeFlow**
If a user is not in Inventory User group, and mrp is installed, **stock_request_mrp** module should be migrated.

### CODE REVIEW

**Review by mariadforgeflow — APPROVED** [review]
LGTM! (CI failing because it depends on #1350)

**Comment by rousseldenis** [comment]
@BernatPForgeFlow For migration PR's with not merged dependencies, it's better to add them to PR comment here above.

**Comment by rousseldenis** [comment]
@BernatPForgeFlow Could you rebase ?

**Comment by BernatPForgeFlow** [comment]
> @BernatPForgeFlow Could you rebase ?

@rousseldenis Rebase done!

**Review by rousseldenis — APPROVED** [review]

**Pull request merged**
