### PR TITLE
[FIX] onchange_warehouse_id: security restrictions error

### PR DESCRIPTION
**Pull request by bodedra**
Forward port https://github.com/OCA/stock-logistics-warehouse/pull/781

### CODE REVIEW

**Comment by bodedra** [comment]
@mreficent @hveficent @lreficent

**Review by LoisRForgeFlow — DISMISSED** [review]
Ty!

**Comment by HviorForgeFlow** [comment]
@lreficent have you check if this tweak is necessary on v12?

**Comment by LoisRForgeFlow** [comment]
@hveficent I just assumed the same issue was present in v12, please go ahead and check, I will cancel the merge for the time being.

**Comment by HviorForgeFlow** [comment]
@lreficent I tested in local and it is not required.

**Comment by LoisRForgeFlow** [comment]
@bodedra I will close the PR then, please reopen if you think we are missing anything.

**Pull request closed without merging**
