### PR TITLE
[13.0][FIX] stock_available_mrp: Set correctlly immediately_usable_qty value.

### PR DESCRIPTION
**Pull request by victoralmau**
Related to: https://github.com/OCA/stock-logistics-warehouse/pull/1152#commitcomment-67223998

Set correctlly `immediately_usable_qty` value (related to https://github.com/OCA/stock-logistics-warehouse/pull/1379).

Please @chienandalu and @pedrobaeza can you review it?

@Tecnativa TT27873

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Review by chienandalu — APPROVED** [review]

**Comment by Cedric-Pigeon** [comment]
@victoralmau would be great to adapt tests, isn't it ?

**Comment by pedrobaeza** [comment]
Which kind of adaptation, Cédric? They are green. If you have steps to reproduce the previous problem, a regression test can be done then to avoid such regression.

**Comment by Cedric-Pigeon** [comment]
Well just wondering why test were not failing before the fix. :thinking:

**Comment by pedrobaeza** [comment]
@victoralmau if you think in any case where the previous code could fail, please express it in a test. If not, please tell and at least let's merge this for avoiding further problems.

**Comment by rousseldenis** [comment]
Such changes that have impact on returned values can easily expressed through a test. That has to be done

**Comment by victoralmau** [comment]
A bit of context on this might help.
The change that was made in the migration is related to this comment https://github.com/OCA/stock-logistics-warehouse/pull/1152#pullrequestreview-663199244 by my colleague @chienandalu .

Reviewing again the change that I have suggested and the tests I think that it is really not necessary. The variables `potential_qty` and `bom_id` are always defined. I have created a local test of a product with a bom without components and no error appears.

@Cedric-Pigeon, can you explain a use case to reproduce the error and see if any changes are really necessary?

**Comment by Cedric-Pigeon** [comment]
Well I have a bom of type "Phantom". None of the components have availabilities -> so I expected to get immediately_available = 0
But due to Odoo compute, the value is 1 because the min (virtual_available) of components is 1

**Comment by victoralmau** [comment]
I've added several tests to check some use cases, but I don't think it's necessary to apply any changes to the current code.

**Comment by Cedric-Pigeon** [comment]
@rousseldenis reproduced the bug here: https://github.com/OCA/stock-logistics-warehouse/pull/1379

**Comment by victoralmau** [comment]
> @rousseldenis reproduced the bug here: #1379

Ok thanks, I have applied the change that I THINK should be applied. It is important that all reviewers have an opinion about it.

**Review by pedrobaeza — APPROVED** [review]

**Review by chienandalu — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Travis seems broken for now: https://app.travis-ci.com/github/OCA/stock-logistics-warehouse/jobs/561591463

I will retry later

**Pull request merged**
