### PR TITLE
[13.0][stock_demand_estimate] fix multicompany security

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**

### CODE REVIEW

**Comment by JordiBForgeFlow** [comment]
cc @AdriaGForgeFlow @JoanSForgeFlow @LoisRForgeFlow @NuriaMForgeFlow

**Review by AdriaGForgeFlow — APPROVED** [review]

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM

**Comment by LoisRForgeFlow** [comment]
optimistically trying to merge, as CI is red but change is trivial. I will try to fix if it does not succeed:

/ocabot merge minor

**Comment by LoisRForgeFlow** [comment]
should be fixed now:

/ocabot merge minor

**Pull request merged**
