### PR TITLE
[16.0][MIG] stock_secondary_unit

### PR DESCRIPTION
**Pull request by remihb**
With changes introduced by #1606 for 15.0 (Compatibility with product variants)

Wait for https://github.com/OCA/product-attribute/pull/1325 to be merged

### CODE REVIEW

**Comment by rousseldenis** [comment]
@remihb Thanks for this. FYI, you can embed open depending PR's here following this method:

https://github.com/OCA/maintainer-tools/wiki/Use-temporary-reference%28s%29-to-another-pull-request%28s%29

This can help reviewers to test on runboat and unit tests running.

**Comment by remihb** [comment]
> @remihb Thanks for this. FYI, you can embed open depending PR's here following this method:
> 
> https://github.com/OCA/maintainer-tools/wiki/Use-temporary-reference%28s%29-to-another-pull-request%28s%29
> 
> This can help reviewers to test on runboat and unit tests running.

I follow the instructions in the link you gave me. But when I put the _test-requirements.txt_ at the root folder of the OCA repo (as mentioned in instructions), it raise me the error `Unreleased dependencies found in "test-requirements.txt` during the ___tests / Detect unreleased dependencies___

So I tried to put the _test-requirements.txt_ at the module folder level so the ___tests / Detect unreleased dependencies___ is successful but the ___tests / test___ part is not.

I don't know what to do about it. Can you help me ?

**Comment by matiasperalta1** [comment]
@remihb Hi! could you rebase this PR to get the runboat build? The dependence https://github.com/OCA/product-attribute/pull/1325 has been merged

**Comment by rousseldenis** [comment]
> > @remihb Thanks for this. FYI, you can embed open depending PR's here following this method:
> > https://github.com/OCA/maintainer-tools/wiki/Use-temporary-reference%28s%29-to-another-pull-request%28s%29
> > This can help reviewers to test on runboat and unit tests running.
> 
> I follow the instructions in the link you gave me. But when I put the _test-requirements.txt_ at the root folder of the OCA repo (as mentioned in instructions), it raise me the error `Unreleased dependencies found in "test-requirements.txt` during the _**tests / Detect unreleased dependencies**_
> 
> So I tried to put the _test-requirements.txt_ at the module folder level so the _**tests / Detect unreleased dependencies**_ is successful but the _**tests / test**_ part is not.
> 
> I don't know what to do about it. Can you help me ?

@remihb That's normal. In order to not forget to remove the added lines in test-requirements.txt before merging, a failed test has been added. When all dependencies are merged, PR author is invited to remove those lines.

**Comment by rousseldenis** [comment]
@remihb Do you mind if we switch to #1769 ?

**Comment by pedrobaeza** [comment]
Superseded by #1769

**Pull request closed without merging**
