### PR TITLE
[10.0] [ADD] stock_location_product_restriction: Prevent to mix different products into the same stock location

### PR DESCRIPTION
**Pull request by lmignon**
ping @rousseldenis

### CODE REVIEW

**Review by apollet — APPROVED** [review]
LGTM not tested

**Review by jbaudoux — APPROVED** [review]
LGTM. Tested, works fine.

**Review by rousseldenis — APPROVED** [review]
Code review.

**Comment by lmignon** [comment]
@dreispt Can you relaunch the merge with minor? Otherwise AFAIK, the merge will not produce a 'normal' release on pypi but only a .dev release.

**Comment by lmignon** [comment]
thank you @rousseldenis

**Pull request merged**
