### PR TITLE
[FIX] stock_request: Multi-company record rules

### PR DESCRIPTION
**Pull request by max3903**

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]
Code review. Trivial

**Comment by etobella** [comment]
A migration script is needed to fix current installations

**Comment by rousseldenis** [comment]
> A migration script is needed to fix current installations

Indeed, good catch. @max3903

**Comment by rousseldenis** [comment]
@max3903

**Comment by pedrobaeza** [comment]
Superseded by #1615

**Pull request closed without merging**
