### PR TITLE
product default location module

### PR DESCRIPTION
**Pull request by rami-wafaie**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
In v8, you can do this with putaway strategies, so there's no need of this module.

https://www.odoo.com/documentation/user/9.0/inventory/routes/strategies/putaway.html

**Comment by gurneyalex** [comment]
@pedrobaeza unless I'm mistaken, this PR is for v7, so it makes sense to me. Needs fixing, though.

**Comment by rami-wafaie** [comment]
@gurneyalex right it is for Version 7, I will fix the errors soon

**Comment by pedrobaeza** [comment]
Sorry, I didn't see the target version. I'm too used to review 8.0 PRs only.

OK, go ahead with it then.

**Comment by rami-wafaie** [comment]
@gurneyalex I fixed the code and it now works, I don't know why it didn't pass the runbot checks, can you please have a look?

**Comment by OSguard** [comment]
rami-wafaie is working on initOS so he is cover to our company CLA

**Comment by OSguard** [comment]
Runbot:
2016-03-10 14:19:48,876 4049 WARNING 3143493-120-126455-all openerp.modules.loading: The transient model stock.warehouse.orderpoint.generator (Orderpoint Generator) should not have explicit access rules!
unrelated!

**Comment by rami-wafaie** [comment]
@gurneyalex Please can you look at the runbot test, I dont think that the poblem is from our side

**Comment by OSguard** [comment]
@rami-wafaie maybe a rebase can help

**Comment by rami-wafaie** [comment]
PR is fixed please have a look

**Comment by gurneyalex** [comment]
@rami-wafaie I'd like a note in the module description that the module does not support a multi company setting. I also think from a a casual glance that it will raise lots of issues in a single company + multiple warehouse setup. I'm not sure it works either if you change the chaining setup of the 'output' location of your warehouse (this is broken in many ways in Odoo itself, but it deserves a mention in the documentation. 

As far as I remember (it's a long time since I've used v7), if the product location is a child location of the stock location of the warehouse, you don't need to do anything to change the from location of the stock.move, as Odoo will do this for you.

**Comment by Cedric-Pigeon** [comment]
@rami-wafaie Is this Pr still usefull ?

**Comment by rousseldenis** [comment]
@rami-wafaie This will be closed. Please feel free to reopen it if you want.

**Pull request closed without merging**
