### PR TITLE
[13.0][FIX]make reason fields read-only if in done state

### PR DESCRIPTION
**Pull request by bizzappdev**

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]
Makes sense

**Review by AaronHForgeFlow — APPROVED** [review]

**Comment by AaronHForgeFlow** [comment]
ping @rousseldenis

**Comment by rousseldenis** [comment]
@bizzappdev Could you rebase ?

**Comment by bizzappdev** [comment]
> @bizzappdev Could you rebase ?

rebase done.

**Comment by dreispt** [comment]
Travis needs fixing.

**Comment by rousseldenis** [comment]
@bizzappdev

**Comment by bizzappdev** [comment]
@dreispt @rousseldenis I did rebase from the 13.0 upstream and push code. as there was no log available for Travis.
now Travis is green and runbot is failing. and runbot log seems partial. so seems like some problem from runbot. can anyone give me a helping hand to trace the real issue

**Comment by dreispt** [comment]
@bizzappdev Thank you. Runbot is not a problem, TravisCI is where tests are run.

**Comment by rousseldenis** [comment]
> @bizzappdev Thank you. Runbot is not a problem, TravisCI is where tests are run.

@dreispt I agree partially. Runbot can indicates Warnings or Errors when loading simultaneously with Travis green.

**Pull request merged**
