### PR TITLE
[12.0][IMP] Use many2many_tags widgets for lots on inventory adjustment

### PR DESCRIPTION
**Pull request by ivantodorovich**
~This PR improves the stock_inventory_preparation_filter module by making it easier to filter on products.~

~Replace the many2many_tags in product_ids~
~Using the standard many2many widget allows the user to easily search and select a list of products~

Use many2many_tags widgets on lots

### CODE REVIEW

**Comment by ivantodorovich** [comment]
@pedrobaeza on https://github.com/OCA/stock-logistics-warehouse/pull/745#issuecomment-551860791
> Don't introduce several things in the same PR: do separate PRs. About the m2m_tags change, I say no. I think you need to know: https://github.com/OCA/web/tree/12.0/web_widget_many2many_tags_multi_selection

**Comment by ivantodorovich** [comment]
I'm trying to test this widget on runbot but apparently it's not doing anything. Am I missing something?

image

IMO having to install a module like this to solve somthing that can be solved in standard odoo is overkill. What's wrong with the many2many widget?

**Comment by pedrobaeza** [comment]
> I'm trying to test this widget on runbot but apparently it's not doing anything. Am I missing something?

It serves on the `Search more...` dialog, where you can select more than one element (that's the difference). You are not seeing it because you don't have more than 7 elements.

> What's wrong with the many2many widget?

- It takes a lot of vertical space, although you select few elements.
- It looks ugly if you have several columns in less than half of the screen.

**Comment by rousseldenis** [comment]
Actually, it does this :

image

**Comment by ivantodorovich** [comment]
> > I'm trying to test this widget on runbot but apparently it's not doing anything. Am I missing something?
> 
> It serves on the `Search more...` dialog, where you can select more than one element (that's the difference). You are not seeing it because you don't have more than 7 elements.
> 
> > What's wrong with the many2many widget?
> 
> * It takes a lot of vertical space, although you select few elements.
> * It looks ugly if you have several columns in less than half of the screen.

Nice!!
I agree, it looks much nicer!

Thanks :+1:

**Comment by rousseldenis** [comment]
Ok, good catch @pedrobaeza

**Comment by ivantodorovich** [comment]
In fact we should do the same for the lots filter.
Because currently it's using the standard many2many

**Comment by pedrobaeza** [comment]
Then you can reconvert the PR for that and adding in the README a recommendation for installing that module. We are already doing that on account_financial_report: https://github.com/OCA/account-financial-reporting/tree/11.0/account_financial_report#account-financial-reports

**Comment by ivantodorovich** [comment]
> Then you can reconvert the PR for that and adding in the README a recommendation for installing that module. We are already doing that on account_financial_report: https://github.com/OCA/account-financial-reporting/tree/11.0/account_financial_report#account-financial-reports

:+1: Thanks @pedrobaeza !

**Review by pedrobaeza — APPROVED** [review]
Thanks to you for being flexible, allow a healthy debate, and perform the changes!

**Review by mamcode — APPROVED** [review]
LGTM.

**Review by HaraldPanten — APPROVED** [review]
LGTM

**Pull request merged**
