### PR TITLE
14.0 mig stock picking volume packaging

### PR DESCRIPTION
**Pull request by mt-software-de**
Backport of https://github.com/OCA/stock-logistics-warehouse/pull/1629

### CODE REVIEW

**Comment by mt-software-de** [comment]
cc @lmignon @jbaudoux @raumschmiede-joshuaL

**Review by jbaudoux — APPROVED** [review]
LGTM

**Comment by jbaudoux** [comment]
ping for review @rousseldenis

**Review by rousseldenis — APPROVED** [review]
Code review

**Pull request merged**
