### PR TITLE
[13.0][IMP] README.md: Show Weblate status

### PR DESCRIPTION
**Pull request by rousseldenis**

### CODE REVIEW

**Comment by rousseldenis** [comment]
image

**Review by pedrobaeza — APPROVED** [review]
Maybe it's more useful the widget by languages in the bottom part.

**Comment by rousseldenis** [comment]
That one ? https://translation.odoo-community.org/widgets/stock-logistics-warehouse-12-0/#horizontal

It's a little bit more complex to read. This one is more 'github' style no ?

**Comment by rousseldenis** [comment]
My aim here is to spread it on my competence repos in order to communicate on that. Maybe that will help translators (I'm not one of them...) to come.

**Comment by pedrobaeza** [comment]
Or maybe this one:

https://translation.odoo-community.org/widgets/stock-logistics-warehouse-12-0/#multi

The example presented by Weblate is too complex, as there are not so much languages in OCA. You can try.

The question is that the global translation percentage says nothing to me as Spanish translator. I want to know the translated percentage for Spanish, not that someone adds Suahili, but then don't translate anything, and that lower the global percentage.

**Comment by rousseldenis** [comment]
> Or maybe this one:
> 
> https://translation.odoo-community.org/widgets/stock-logistics-warehouse-12-0/#multi
> 
> The example presented by Weblate is too complex, as there are not so much languages in OCA. You can try.
> 
> The question is that the global translation percentage says nothing to me as Spanish translator. I want to know the translated percentage for Spanish, not that someone adds Suahili, but then don't translate anything, and that lower the global percentage.

Yes, but that indicates to people including maintainers what is the average translation rate. 

If you want the detail, just click on it (for me , the button link is the most useful add, here)

**Comment by rousseldenis** [comment]
> > Or maybe this one:
> > https://translation.odoo-community.org/widgets/stock-logistics-warehouse-12-0/#multi
> > The example presented by Weblate is too complex, as there are not so much languages in OCA. You can try.
> > The question is that the global translation percentage says nothing to me as Spanish translator. I want to know the translated percentage for Spanish, not that someone adds Suahili, but then don't translate anything, and that lower the global percentage.
> 
> Yes, but that indicates to people including maintainers what is the average translation rate.
> 
> If you want the detail, just click on it (for me, the button link is the more useful add)

**Comment by pedrobaeza** [comment]
I prefer the other verbose option, but I have already approved this simple one.

**Pull request merged**
