### PR TITLE
[8.0] account_move_line_product

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
Account Move Line Product
=========================

This module enhances the views associated to account moves and account move
lines to display the product that is associated to the move line.

This will be relevant in perpetual inventory, for inventory-related account
moves.

### CODE REVIEW

**Comment by JordiBForgeFlow** [comment]
cc @eficent

**Review by LoisRForgeFlow — APPROVED** [review]
Tested on runbot + code review :+1:

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: 

Very useful when adjusting stock valuation discrepancies

**Comment by rousseldenis** [comment]
@jbeficent I think there is a problem of context here ...
Maybe you could have waited a little bit more reviews before merging ?
See my remark in https://github.com/OCA/stock-logistics-warehouse/pull/238

Functional need (inventory) can not just justify the location of this module here IMO
@lmignon @adrienpeiffer

**Comment by JordiBForgeFlow** [comment]
@rousseldenis Oh, I see... This feature is, however, a grey zone... It is sufficiently justified in the README that this feature is associated to the perpetual inventory management. I propose that we stick to this branch now, in order to avoid futher confusion between versions.

**Comment by rousseldenis** [comment]
@jbeficent Ok. That was just for consistency reasons (as if I want accounting modules, I go naturally in accounting repos :-) )

**Pull request merged**
