### PR TITLE
[12.0] stock_request: Add order desc for SR and SRO

### PR DESCRIPTION
**Pull request by HviorForgeFlow**
Gain user-friendly usability showing last records on top.

@max3903 @etobella @jbeficent

CC @Eficent

### CODE REVIEW

**Review by etobella — APPROVED** [review]

**Review by JordiBForgeFlow — APPROVED** [review]

**Comment by JordiBForgeFlow** [comment]
cc @aheficent

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: Makes sense

**Comment by AaronHForgeFlow** [comment]
The error does not make much sense, it is on `stock_warehouse_orderpoint_stock_info_unreserved `module. Could not reproduce.

Process followed:
created DB, install all the modules of this repo and nothing else. Install stock request with those changes. Run all tests. No errors got.

Let's try rebuild.

**Comment by rousseldenis** [comment]
@aheficent This was due to https://github.com/OCA/stock-logistics-warehouse/pull/668

So, @hveficent  please rebase

**Comment by AaronHForgeFlow** [comment]
I thought this was even. Rebased. Thanks @rousseldenis

**Pull request merged**
