### PR TITLE
[16.][MIG] stock_change_qty_reason

### PR DESCRIPTION
**Pull request by Urvisha-OSI**

### CODE REVIEW

**Review by rousseldenis — CHANGES_REQUESTED** [review]
Functional review. The reasons view form is weird for the active field:

image

**Comment by rousseldenis** [comment]
@Urvisha-OSI

**Comment by paradoxxxzero** [comment]
Superseeded in #1854

**Comment by rousseldenis** [comment]
@Urvisha-OSI We switched to #1854

**Comment by rousseldenis** [comment]
switched to https://github.com/OCA/stock-logistics-warehouse/pull/1854

**Pull request closed without merging**
