### PR TITLE
[15.0][MIG]stock_inventory_discrepancy

### PR DESCRIPTION
**Pull request by Chanakya-OSI**
Depends on: https://github.com/OCA/stock-logistics-warehouse/pull/1512

### CODE REVIEW

**Comment by rousseldenis** [comment]
@Chanakya-OSI Thanks for this.

Don't forget to mention in your PR description if this depends on another PR (stock_inventory).

You can add also an entry in test-requirements.txt file (in separate commit) to be able to launch tests and runboat build.

**Comment by rousseldenis** [comment]
And please follow https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0#technical-method-to-migrate-a-module-from-140-to-150-branch

As your commit about Travis is not correct.

**Comment by rousseldenis** [comment]
@Chanakya-OSI Could you rebase ?

**Comment by pedrobaeza** [comment]
Superseded by #1683

**Comment by mileo** [comment]
Can some one reopen this pull request?

**Pull request closed without merging**
