### PR TITLE
[14.0][FIX] stock_mts_mto_rule: check mts+mto in mrp

### PR DESCRIPTION
**Pull request by alan196**
This PR add the functionality to use mts+mto in procurements created from MRP module.

### CODE REVIEW

**Comment by jonerikceberio** [comment]
Been working in a very similar solution, my two cents:

- We thought that it should be a separate module: mrp_mts_mto_rule, as the method is called in mrp components (not sure why the original method is in stock)
- The solution does not work without a rule with action split from stock to production. In our code we inherited the _get_global_route_rules_values (as the original stock_mts_mto_rule) to create such a rule.

So I understand that the afore code does not work without creating that rule manually, is that so?

**Comment by jonerikceberio** [comment]
Indeed there is another possible problem: In the case of a double dependency of a component, e.g. A has a BoM with B and C, and B has a BoM with C, the method is not able to recognize that the stock of C has been used for producing A in the production of B. 
In the same example, with BoMs usin 1 component each, if you have 5 units of C and you sell 4 units of A, the method finds no needed_qty (zero) of C. This is because the make_to_stock moves are not confirmed and therefore they do not reserve stock. And so it uses the same 4 units twice.
If you don't mind I can PR your branch so you can see the differences with your code.

**Comment by elvise** [comment]
@alan196 really cool! 
Any feedbacks about comments of @jonerikceberio ?

**Comment by elvise** [comment]
> Indeed there is another possible problem: In the case of a double dependency of a component, e.g. A has a BoM with B and C, and B has a BoM with C, the method is not able to recognize that the stock of C has been used for producing A in the production of B.
> In the same example, with BoMs usin 1 component each, if you have 5 units of C and you sell 4 units of A, the method finds no needed_qty (zero) of C. This is because the make_to_stock moves are not confirmed and therefore they do not reserve stock. And so it uses the same 4 units twice.
> If you don't mind I can PR your branch so you can see the differences with your code.

@jonerikceberio good point! 
any progress in this direction?

**Comment by rousseldenis** [comment]
@alan196 Could you rebase?

**Comment by rousseldenis** [comment]
@alan196 Could you add a test that highlight this change ?

**Comment by elvise** [comment]
@alan196 just a gentle reminder :)

**Comment by elvise** [comment]
> > Indeed there is another possible problem: In the case of a double dependency of a component, e.g. A has a BoM with B and C, and B has a BoM with C, the method is not able to recognize that the stock of C has been used for producing A in the production of B.
> > In the same example, with BoMs usin 1 component each, if you have 5 units of C and you sell 4 units of A, the method finds no needed_qty (zero) of C. This is because the make_to_stock moves are not confirmed and therefore they do not reserve stock. And so it uses the same 4 units twice.
> > If you don't mind I can PR your branch so you can see the differences with your code.
> 
> @jonerikceberio good point! any progress in this direction?

@jonerikceberio just a gentle reminder :)

**Comment by elvise** [comment]
> Indeed there is another possible problem: In the case of a double dependency of a component, e.g. A has a BoM with B and C, and B has a BoM with C, the method is not able to recognize that the stock of C has been used for producing A in the production of B. 
> 
> In the same example, with BoMs usin 1 component each, if you have 5 units of C and you sell 4 units of A, the method finds no needed_qty (zero) of C. This is because the make_to_stock moves are not confirmed and therefore they do not reserve stock. And so it uses the same 4 units twice.
> 
> If you don't mind I can PR your branch so you can see the differences with your code.


@alan196 thanks for your commit!
Do you have considered @jonerikceberio scenario ?

**Comment by alan196** [comment]
@elvise no I don't 😞 currently I'm a bit busy, but If you or @jonerikceberio propose the change in a PR I'll take the time to review and make the proper tests.

Sadly, at this moment, I cannot take the time to develop that feature.

**Comment by elvise** [comment]
@pedrobaeza have you time for this PR ?

**Comment by pedrobaeza** [comment]
I'm not using this module anymore, sorry.

**Comment by elvise** [comment]
@rousseldenis merge ? :)

**Comment by rousseldenis** [comment]
> @rousseldenis merge ? :)

As said above, tests should be added.

Moreover, I would say that code that depends on mrp should be added in a dedicated module.

Somehow `stock_mts_mto_mrp_rule`.

**Comment by elvise** [comment]
> > @rousseldenis merge ? :)
> 
> As said above, tests should be added.
> 
> Moreover, I would say that code that depends on mrp should be added in a dedicated module.
> 
> Somehow `stock_mts_mto_mrp_rule`.

Sorry! Got it

**Comment by elvise** [comment]
> > @rousseldenis merge ? :)
> 
> As said above, tests should be added.
> 
> Moreover, I would say that code that depends on mrp should be added in a dedicated module.
> 
> Somehow `stock_mts_mto_mrp_rule`.

@alan196 have you time for follow these points ?

**Comment by francesco-ooops** [comment]
Hi @alan196, do you think you can add tests soon? 

or is it ok if we complete your work in a new PR in order to merge it?

Thanks!

**Comment by francesco-ooops** [comment]
> Hi @alan196, do you think you can add tests soon?
> 
> or is it ok if we complete your work in a new PR in order to merge it?
> 
> Thanks!

@alan196 gentle reminder :)

**Comment by alan196** [comment]
@francesco-ooops sorry for the late response, is ok for me.

Sadly at this moment I don't have the time to write tests, but as soon as you make the PR please tag me and I will review

**Comment by francesco-ooops** [comment]
@alan196 sure thanks!

**Pull request closed without merging**
