### PR TITLE
[10.0][MIG] stock_account_change_product_valuation

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Standard migration.

Pending to add:
- [x] ae0276999c1d8fbbf88658ced80136cc003fe0c0 (https://github.com/OCA/stock-logistics-warehouse/pull/342)

### CODE REVIEW

**Review by gurneyalex — APPROVED** [review]
Technically ok. Maybe the README should warn explicitely that changing the type of a product can cause irreversible data loss.

test cov drop is ok

**Review by rousseldenis — APPROVED** [review]
Code review

**Comment by LoisRForgeFlow** [comment]
open PR in v9: https://github.com/OCA/stock-logistics-warehouse/pull/342

**Review by LoisRForgeFlow — CHANGES_REQUESTED** [review]
please review my fixes in v9

**Comment by LoisRForgeFlow** [comment]
@mreficent the changes at https://github.com/OCA/stock-logistics-warehouse/pull/342 are merged. Could you please update this PR accordingly?

commit is here: ae0276999c1d8fbbf88658ced80136cc003fe0c0

**Review by LoisRForgeFlow — APPROVED** [review]

**Pull request merged**
