### PR TITLE
[16.0][MIG] stock_quant_cost_info: Migration to version 16.0

### PR DESCRIPTION
**Pull request by Yadier-Tecnativa**
@Tecnativa TT42443

### CODE REVIEW

**Comment by Yadier-Tecnativa** [comment]
ping @pedrobaeza , @sergio-teruel

**Review by CarlosRoca13 — APPROVED** [review]
Tested on runboat :+1:

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge nobump

**Comment by sergio-teruel** [comment]
ping @juangomezzurita

**Pull request merged**
