### PR TITLE
[MIG] stock_available_immediately: Migration to 15.0

### PR DESCRIPTION
**Pull request by glitchov**

### CODE REVIEW

**Review by victoralmau — APPROVED** [review]
Code review OK

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
It seems this one is collapsing with `sale_stock_available_info_popup`, as it contains tests that expects the usual behavior of `stock_available`, not this modified one. One possible technique is to not enable the feature if in test mode (`not config["test_enable"]`) and not testing this exact module (through a context key check).

How this was done in 13.0 that both coexist?

**Comment by victoralmau** [comment]
Superseed by https://github.com/OCA/stock-logistics-warehouse/pull/1588

**Pull request closed without merging**
