### PR TITLE
[14.0][IMP] stock_location_warehouse: change development_status

### PR DESCRIPTION
**Pull request by twalter-c2c**
Change `development_status` in the manifest from Alpha to Beta to reflect the maturity level of the module and to allow to use it as a dependency by other modules in the Beta status

### CODE REVIEW

**Comment by rousseldenis** [comment]
@twalter-c2c Thanks for this. Don't hesitate to improve your PR's title in order to help reviewers.

**Comment by rousseldenis** [comment]
Same for commit message:

`[IMP] stock_location_warehouse: (...)`

**Comment by twalter-c2c** [comment]
Thank you @rousseldenis for your comments. I will do my best to remember it in the future.

**Review by ajaniszewska-dev — APPROVED** [review]

**Review by bosd — APPROVED** [review]

**Review by sebalix — APPROVED** [review]

**Pull request merged**
