### PR TITLE
[12.0][IMP] stock_request:- Improved _compute_qty code

### LINKED ISSUE #958: stock_request: Quantity done calculation
# Version

Reproduced on 12.0.
Have not tested other versions.

# Description

If someone creates a return from a delivery order that is linked to a stock request order, the quantity returned is added to the SRO's quantity done field. 

This can cause issues, specifically when accounting bills a customer. The invoice is based off the Qty Done field on an SRO, so a mistake on the SRO can create a mistake on the invoice. If something is returned, the quantity returned should be deducted the SRO, not added to it. 

# Steps to reproduce

* Create stock request order. Add Deliver in 1 step (ship) to each line item route. Submit and confirm. Delivery Order created.
* Process delivery order so that it is validated and Done.
* Verify the Qty Done and Quantity fields on the SRO match.
* On the delivery order, click the Return button. Choose the HQ warehouse on the pop window and click Return in the pop up window.
* On the created WH/IN return order, process so that the order is validated and Done.

# Result

* On the originating stock request order, the Qty Done field has now increased by the amount that was received on the return. 

# Expected Result

* A return should not increase the Qty Done field on the SRO, it should decrease it.

### PR DESCRIPTION
**Pull request by murtuzasaleh**
#958

### CODE REVIEW

**Review by max3903 — APPROVED** [review]

**Review by osi-scampbell — APPROVED** [review]

**Review by bodedra — APPROVED** [review]

**Review by marcelsavegnago — APPROVED** [review]

**Review by HaraldPanten — APPROVED** [review]

**Comment by rousseldenis** [comment]
A test that highlight the change could be welcome. As that would protect the code for further modifications

**Comment by LoisRForgeFlow** [comment]
@murtuzasaleh This looks good, can you add a test case as suggested by @rousseldenis ?

**Comment by osi-scampbell** [comment]
ping @murtuzasaleh

**Comment by etobella** [comment]
@murtuzasaleh Can you add the test as suggested?

**Comment by murtuzasaleh** [comment]
> @murtuzasaleh Can you add the test as suggested?

@etobella Yes, I will add it.

**Comment by kittiu** [comment]
@murtuzasaleh are you still on this? It has been a while so, may I ping this again.

**Pull request closed without merging**
