### PR TITLE
[14.0][MIG] stock_request_tier_validation

### PR DESCRIPTION
**Pull request by SurachetS**
from my test, not used

removed
1. tier_review_order_form_wiz (stock_request_tier_validation/views/stock_request_order_view.xml)
2. tier_review_form_wiz (stock_request_tier_validation/views/stock_request_view.xml)

depends on

- [x] base_tier_validation
- [ ] stock_request #985

### CODE REVIEW

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM

**Review by olgamarcocb — APPROVED** [review]
LGTM 👍

**Pull request merged**
