### PR TITLE
[14.0][MIG] stock_account_internal_move: Migrated the module to version 14.0

### PR DESCRIPTION
**Pull request by ShivamS-SerpentCS**

### CODE REVIEW

**Comment by ShivamS-SerpentCS** [comment]
@kittiu @max3903 Can you please review this PR. Thank You.

**Review by rousseldenis — APPROVED** [review]
Code review

**Comment by kittiu** [comment]
Code reviewed, no major changes. Would encourage you to write more test.

**Review by kittiu — APPROVED** [review]

**Comment by ShivamS-SerpentCS** [comment]
Thank you for the review @kittiu and yes I am working on adding more test cases to this module.

**Review by atchuthan — APPROVED** [review]

**Review by Engmostafa15 — APPROVED** [review]

**Comment by rousseldenis** [comment]
@ShivamS-SerpentCS Could you fix this ?

**Pull request closed without merging**
