### PR TITLE
[14.0] [ADD] stock_orderpoint_template

### PR DESCRIPTION
**Pull request by paradoxxxzero**
This module helps creating orderpoints automatically using templates.
A template is similar to an orderpoint, but it is not linked to a product.

When a picking is validated, the system will look for templates that match
the product and location of the picking. If there is no orderpoint but a 
template is found, it will create an orderpoint for the product and location
of the template.

The new orderpoint is linked to the template, and a change in the template values
will propagate to the orderpoints. To avoid this, you can unlink the orderpoint
by setting its template to False.

### CODE REVIEW

**Comment by rousseldenis** [comment]
@paradoxxxzero Have you looked at https://github.com/OCA/stock-logistics-warehouse/pull/1869 ?

**Comment by paradoxxxzero** [comment]
@rousseldenis ah missed that, but it's not quite the same, here the orderpoints are generated lazily and only on picking/move confirmation (not in the run scheduler cron).

**Comment by rousseldenis** [comment]
@paradoxxxzero yes, but as both modules introduce a template model, IMHO this should either be part of the other module either overrides it

**Comment by paradoxxxzero** [comment]
@rousseldenis indeed this is the same model name, but what IF this module was named `stock_orderpoint_blueprint`? :)

**Pull request closed without merging**
