### PR TITLE
[13.0][MIG] stock_demand_estimate

### PR DESCRIPTION
**Pull request by LoisRForgeFlow**
Standard Migration.

@ForgeFlow

### CODE REVIEW

**Review by AdriaGForgeFlow — APPROVED** [review]
Code review :+1:

**Comment by rousseldenis** [comment]
@LoisRForgeFlow Do you plan to add tests for missing coverage (onchanges specifically) ?

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: Code + functional on local

**Comment by LoisRForgeFlow** [comment]
@rousseldenis Done!

**Comment by LoisRForgeFlow** [comment]
+95% coverage now, everything green and functional test done. Let's merge:

/ocabot merge

**Pull request merged**
