### PR TITLE
[MIG] stock_exception: migration to 16.0

### PR DESCRIPTION
**Pull request by mav-adhoc**

### CODE REVIEW

**Comment by yostashiro** [comment]
@mav-adhoc There is #1957 already. Would you review this instead?

**Comment by mav-adhoc** [comment]
@yostashiro Hi! This PR, apart from migrating the module to the 16 version, includes new features. 

When we were testing the model,  in case we choose 'stock.picking' as the model where we wanted to apply the exception, we noticed that the exception also ran when we confirmed sale orders. 
This happens because, by confirming sale orders, the action confirm creates the respective records in stock.picking (IN/OUT, depending on the configuration you have) and run the exception.
What we wanted is to have the decision when to run the exception, if at the creation of the stock.picking record or if at the validation of the stock.picking record.

Due to this desire, we created two new boolean fields in the stock.exception class (check_on_validate and check_on_confirm) in order to indicate when to run the exception. If you select check_on_confirm, it will run the exception when you create the stock.picking record. If you select check_on_validate, it will run the exception when you validate the stock.picking record.

**Comment by yostashiro** [comment]
@mav-adhoc Thanks for explaining. We currently don't use this module so we may not be doing a thorough review, but I'd suggest splitting the new feature into a separate commit for ease of review and backporting.

**Comment by mav-adhoc** [comment]
@rousseldenis we should close this PR or the previous one?

**Comment by mav-adhoc** [comment]
@yostashiro Hi! Can we merge this PR? Or we should merge the previous pull request (https://github.com/OCA/stock-logistics-warehouse/pull/1957) ?

**Comment by rousseldenis** [comment]
> @yostashiro Hi! Can we merge this PR? Or we should merge the previous pull request (#1957) ?

@mav-adhoc The better is to ask @Saran440 what to do. As it was there before this, it is also fair to review that one instead.

**Comment by Saran440** [comment]
I checked this PR and https://github.com/OCA/stock-logistics-warehouse/pull/1957
it difference a little bit https://github.com/OCA/stock-logistics-warehouse/pull/1965/commits/8d6c62672980c73b1118f4968e6478c90317e5f8#diff-6cd14808c7b5610b6aedda5ec36d4cc5e66fd7839054d24788f2461897619687R41

However, I okay to use this PR.
Closed https://github.com/OCA/stock-logistics-warehouse/pull/1957

**Review by Saran440 — APPROVED** [review]
Code Review :+1:

**Review by rousseldenis — APPROVED** [review]

**Comment by mav-adhoc** [comment]
@OCA/tools-maintainers Merge please

**Comment by jcadhoc** [comment]
@OCA/tools-maintainers Merge please

**Comment by thomaspaulb** [comment]
This does not belong to `tools`. `@OCA/stock...` does not yield me any autofill, @pedrobaeza do you know what the correct ping is?

**Pull request merged**
