### PR TITLE
[13.0] [IMP] stock_inventory_include_exhausted: Use the locations in the stock inventory for exhausted.

### PR DESCRIPTION
**Pull request by nicomacr**
Now we consider the locations selected in the inventory when create the lines for the exhausted values.
We use an approach similar to odoo in v14 to solve this problem.

### CODE REVIEW

**Review by rousseldenis — CHANGES_REQUESTED** [review]
@nicomacr Thanks for this. Could you include tests that highlight these changes ?

**Comment by nicomacr** [comment]
@rousseldenis test cases done!

**Review by florenciafrigieri2 — APPROVED** [review]
Functional review done, working as expected.

**Review by rousseldenis — APPROVED** [review]

**Comment by nicomacr** [comment]
@OCA/logistics-maintainers anyone could check this out? Thanks

**Comment by nicomacr** [comment]
@rousseldenis this PR is ready to merge  isn't it? 
It's pending someone additional review?

**Pull request merged**
