### PR TITLE
[MIG][15.0] stock_orderpoint_uom

### PR DESCRIPTION
**Pull request by JoanMForgeFlow**
Standard migration to version 15.0

### CODE REVIEW

**Review by BernatPForgeFlow — APPROVED** [review]

**Review by mariadforgeflow — APPROVED** [review]

**Comment by rousseldenis** [comment]
@JoanMForgeFlow Could you rebase in order to see why merge has failed ?

**Comment by JoanMForgeFlow** [comment]
@rousseldenis done! :+1:

**Comment by rousseldenis** [comment]
> @rousseldenis done! +1

Could you check pre-commit ?

**Comment by JoanMForgeFlow** [comment]
@rousseldenis done! :+1: 
Now its green

**Pull request merged**
