### PR TITLE
 [12.0][ADD] stock_packaging

### PR DESCRIPTION
**Pull request by rousseldenis**
Depends on :

* [x] https://github.com/OCA/product-attribute/pull/486
* [x] Removing enty in oca_dependencies.txt before merging

### CODE REVIEW

**Review by jgrandguillaume — APPROVED** [review]
LGMT thanks for the job

**Comment by rousseldenis** [comment]
This one is :green_apple:

**Review by lmignon — APPROVED** [review]
Thank you @rousseldenis

**Comment by rousseldenis** [comment]
> /ocabot merge

You have adopted it! :smiley:

**Comment by pedrobaeza** [comment]
Hehe, you see!

**Comment by sbidoul** [comment]
@pedrobaeza @rousseldenis and now we can easily bump versions again.
I'll prepare a communication to contributors about this.

**Comment by rousseldenis** [comment]
> @pedrobaeza @rousseldenis and now we can easily bump versions again.
> I'll prepare a communication to contributors about this.

Great! So, the merger has to check if version bump is included in PR or not to add patch/minor/major attribute to command.

**Comment by pedrobaeza** [comment]
Yes, already using it also: https://github.com/OCA/l10n-spain/pull/1125#issuecomment-503543502 :smiley:

**Pull request closed without merging**
