### PR TITLE
[15.0][IMP] stock_quant_manual_assign: field reserved as readonly

### PR DESCRIPTION
**Pull request by LoisRForgeFlow**
Forward port of https://github.com/OCA/stock-logistics-warehouse/pull/1550.

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Review by mariadforgeflow — APPROVED** [review]

**Comment by LoisRForgeFlow** [comment]
@pedrobaeza @sbidoul Pre-commit failed during merge because it cannot connecto to **gitlab**?

`fatal: could not read Username for 'https://gitlab.com/': No such device or address`

details: https://github.com/OCA/stock-logistics-warehouse/actions/runs/3469739064/jobs/5797086769

any clue?

**Comment by pedrobaeza** [comment]
Again we need a copier template due to other external change in our pre-commit tooling. Fixed here #1554

/ocabot merge patch

**Comment by LoisRForgeFlow** [comment]
Thanks Pedro!

**Pull request merged**
