### PR TITLE
[9.0] procurement_auto_create_group

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
Procurement Auto Create Group
=============================

This module allows the system to propose automatically new procurement groups
 in procurement orders.

 This capability is important when you want to make sure that all the stock
 moves resulting from this procurement will never be mixed with moves from
 other groups in stock transfers.

 The stock transfers resulting from the execution of these procurements will
 only contain stock moves created from that procurement.

Configuration
=============

* Go to *Inventory / Configuration / Settings* and check the option 'Advanced
  routing of products using rules' and press the 'Apply' button.
* Activate the developer mode.
* Go to *Inventory / Configuration / Routes / Routes* and check the option
  'Auto-create Procurement Group' to the pull rules where you want the
  procurement groups to be automatically proposed.

Usage
=====

* Go to *Inventory / Reports / Procurement Exceptions*.
* Create a new procurement order and make sure that it determines a pull rule
 with the option 'Auto-create Procurement Group' set.
* When you save the procurement order, a procurement group with format
  'PR/<year>/000001' will be created.

### CODE REVIEW

**Comment by JordiBForgeFlow** [comment]
cc @lreficent @mreficent

**Review by LoisRForgeFlow — APPROVED** [review]
Tested + code review :+1:

**Review by AaronHForgeFlow — APPROVED** [review]
It works as expected :+1:

**Comment by LoisRForgeFlow** [comment]
Just Added tests. All tests green now. Reviews are welcomed!

**Review by AaronHForgeFlow — APPROVED** [review]
Tests are fine to me :+1:

**Review by MiquelRForgeFlow — APPROVED** [review]
LGTM :+1:

**Review by rousseldenis — APPROVED** [review]
:+1: LGTM Code review

**Comment by jbeficent** [comment]
cc @Eficent

**Pull request merged**
