### PR TITLE
[13.0][MIG] stock_available_unreserved

### PR DESCRIPTION
**Pull request by LoisRForgeFlow**
Standard migration to v13.

@ForgeFlow

### CODE REVIEW

**Comment by rousseldenis** [comment]
@LoisRForgeFlow Already in #771

**Review by AdriaGForgeFlow — APPROVED** [review]
Functional review :+1:

**Review by AaronHForgeFlow — APPROVED** [review]
:+1:  Code review LGTM

**Comment by kos94ok-3D** [comment]
Hi, @LoisRForgeFlow.
Is it in a stock module now or I miss something?

**Comment by LoisRForgeFlow** [comment]
@kos94ok-3D I cannot find it, could you point me the code?

**Comment by kos94ok-3D** [comment]
@LoisRForgeFlow [free_qty field](https://github.com/odoo/odoo/blob/6b491e0a1d405bc1dfc71c800bc192877f42e204/addons/stock/models/product.py#L51)

**Comment by jjscarafia** [comment]
@kos94ok-3D @LoisRForgeFlow 
yes, is seems Odoo has the same field as @kos94ok-3D said ([free_qty field](https://github.com/odoo/odoo/blob/6b491e0a1d405bc1dfc71c800bc192877f42e204/addons/stock/models/product.py#L51)) but it's only on product.product (not in product.template)
perhaps for v14/master we could try a PR to add free_qty also on pt and then we could get rid of this module

**Pull request merged**
