### PR TITLE
[13.0][IMP] stock_move_location: Take into account owner for move quants

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa TT28438
ping @carlosdauden @chienandalu

### CODE REVIEW

**Comment by rousseldenis** [comment]
Hi @sergio-teruel Thanks for this. Could you add a test and remove .po modifications ?

**Review by chienandalu — APPROVED** [review]
Ok, although tests would be welcome indeed

Translation changes maybe would fit better in its own commit

**Comment by pedrobaeza** [comment]
@carlosdauden can you confirm this?

**Review by carlosdauden — APPROVED** [review]
Please review @rousseldenis comments

**Comment by pedrobaeza** [comment]
The changes on the language files are because there are new terms that are translated in this PR. I have checked that there's no pending translating to push and no conflict in https://translation.odoo-community.org/projects/stock-logistics-warehouse-13-0/stock-logistics-warehouse-13-0-stock_move_location/es/#repository

About the test, it's always desirable, but this is more a fix than a imp, and we need it on the repo. Later the regression test can be added:

/ocabot merge patch

**Pull request merged**
