### PR TITLE
[8.0][FIX] Adds standard_price in onchange

### PR DESCRIPTION
**Pull request by P4R**
Adds standard_price in onchange to assing it when create new line or the product changes.

### CODE REVIEW

**Comment by rousseldenis** [comment]
@P4R Thanks for this.

Could you check flake8 errors? And could you provide a test script that highlight that change ?

**Comment by rousseldenis** [comment]
@P4R Look at https://travis-ci.org/OCA/stock-logistics-warehouse/jobs/593525889#L375

That's license missing in __openerp__.py manifest.

**Comment by rousseldenis** [comment]
@P4R Do you plan to add tests for this change ?

Could you squash your two first commits ?

**Comment by P4R** [comment]
> @P4R Do you plan to add tests for this change ?
> 
> Could you squash your two first commits ?

I don't add test because it's triggered by onchange.

**Comment by rousseldenis** [comment]
> > @P4R Do you plan to add tests for this change ?
> > Could you squash your two first commits ?
> 
> I don't add test because it's triggered by onchange.

You can test that :sweat_smile:

**Comment by rousseldenis** [comment]
@P4R Do you plan to add tests or let as is ?

**Comment by rousseldenis** [comment]
@P4R Closing this as very old. Please feel free to reopen it if needed.

**Pull request closed without merging**
