### PR TITLE
[13.0] Add stock_location_position

### PR DESCRIPTION
**Pull request by guewen**
Continued the work started on #712, including the renaming and addition of tooltips asked there.
Migrated to 13.0.

### CODE REVIEW

**Comment by ps-tubtim** [comment]
Please squash migration commits into one.

**Review by rousseldenis — APPROVED** [review]

**Comment by guewen** [comment]
@ps-tubtim I see only one migration commit (46b934c)?

**Comment by ps-tubtim** [comment]
@guewen I mean squash the last three commit into one (8644b67, 745a41a, 46b934c).
Why you separate to three commit ?

**Comment by guewen** [comment]
@ps-tubtim 

* "Add tooltips" is not part of the migration, it adds new things. If we want to backport them to 12.0 for instance, a cherry-pick allows to get them without getting the changes done for 13.0
* "Add setuptools files" is the result of the command `setuptools-odoo-make-default -d .` which generates these files. It's not part of the changes required to make the module work in 13.0, I think it's cleaner to have a commit to keep these new files apart.

**Comment by ps-tubtim** [comment]
@guewen Thank you for expand it to me.

**Review by ps-tubtim — APPROVED** [review]

**Pull request merged**
