### PR TITLE
[10.0][mig] stock_orderpoint_uom

### PR DESCRIPTION
**Pull request by LoisRForgeFlow**
Changes done:
* Basic migration: odoo tags, odoo imports, bump version...
* Update README.
* Fix moved inherited methods.
* Adapt method calls to new version.
* Squash commit history.

### CODE REVIEW

**Review by JordiBForgeFlow — APPROVED** [review]
:+1: Technical and functional review.

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: LGTM

**Review by MiquelRForgeFlow — APPROVED** [review]
fine :+1:

**Comment by lmignon** [comment]
@lreficent The same kind of functionality is provided by the purchase_packaging into #259 
The main difference between the two approaches is that the uom to use is taken on the supplierinfo into purchase_packaging.... It would be nice to have the 2 PRs converging. What do you think?

**Comment by MiquelRForgeFlow** [comment]
@lmignon I think that they are similar features, but some companies do not use packaging at all. And also, as documented in the README, sometimes you have a need in 'mm' but you request in 'm'. Not related to packages.

**Comment by MiquelRForgeFlow** [comment]
@lmignon If you agree we can merge this module.

**Comment by LoisRForgeFlow** [comment]
I will proceed to merge this, after all, #259 is already merged so the possibility to converge both modules is not possible (at least for this version).

**Pull request merged**
