### PR TITLE
[12.0][ADD] stock_realign_move_and_quants

### PR DESCRIPTION
**Pull request by robinkeunen**
A bug in Odoo 12 leads to the desynchronisation of the stock
quants and the stock move lines. The root cause has yet to be found.
This modules fixes the symptoms and not the cause. It aims to
1. Realign the stock quants and the stock move lines
2. Correct on the fly future desynchronisation

To do that, we assume the source of truth are the move lines rather than
the quants.

CAREFUL : this module has not been tested on a warehouse with multi-location or using packages.

More information on this issue: https://github.com/odoo/odoo/issues/62139

### CODE REVIEW

**Comment by robinkeunen** [comment]
Compared to @gurneyalex 's gists, I changed

- the comparison in the wizard uses float_compare
- removed `def fix_reserved_quantity_in_quants` in stock.quant (unused)
- adding inventory line, fixing the quants and computing inventory line's theoretical quantity is done in one pass on the problematic quantities.

**Comment by rousseldenis** [comment]
@robinkeunen Could you rebase ?

**Comment by robinkeunen** [comment]
@rousseldenis here you go

**Review by rousseldenis — APPROVED** [review]
Code review. LGTM

**Comment by rousseldenis** [comment]
@robinkeunen Don't forget to install pre-commit locally

**Pull request merged**
