### PR TITLE
[11.0][MIG] account_move_line_stock_info

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Standard migration.

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
Tests are failing.

**Review by CasVissers-360ERP — APPROVED** [review]
LGTM

**Review by rousseldenis — APPROVED** [review]
Code review

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: LGTM tested on local.

**Review by tafaRU — CHANGES_REQUESTED** [review]
Code review and test locally :+1: 
But https://travis-ci.org/OCA/stock-logistics-warehouse/jobs/434085332 is red: check, please!

**Comment by MiquelRForgeFlow** [comment]
@tafaRU , please update your review

selection_025

It just happens that odoo 10.0 branch is now broken

**Comment by tafaRU** [comment]
> that odoo 10.0 branch is now broken

Did you mean `11.0` branch?

**Comment by MiquelRForgeFlow** [comment]
> Did you mean 11.0 branch?

Yes 😅 The problem is not related with this PR.

**Comment by MiquelRForgeFlow** [comment]
Ok, I saw now the log. It's not a problem of odoo. It's fails a test of another module (`stock_request_purchase`).

**Comment by rousseldenis** [comment]
> > Did you mean 11.0 branch?
> 
> Yes  The problem is not related with this PR.

That's my feeling too. But to ensure that, I've restarted the last 11.0 commit build.

https://travis-ci.org/OCA/stock-logistics-warehouse/builds/430847042

**Comment by tafaRU** [comment]
> I've restarted the last 11.0 commit build.

Ok, probably it will be green considering that https://travis-ci.org/OCA/stock-logistics-warehouse/jobs/434058403 (more recent than this) it is.

**Comment by rousseldenis** [comment]
@tafaRU Travis is green

**Review by tafaRU — APPROVED** [review]
https://travis-ci.org/OCA/stock-logistics-warehouse/builds/434085328 now is :green_apple: 
I merge then.

**Pull request merged**
