### PR TITLE
[11.0][FIX] stock_inventory_lockdown: don't check in any case of inventory adjustments

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
The virtual adjustment location may be different from the one provided in property_stock_inventory of the product.

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
@jbeficent @lreficent @rousseldenis

**Review by LoisRForgeFlow — APPROVED** [review]
:+1: 

You can point in the description the trigger for this: https://github.com/OCA/stock-logistics-warehouse/issues/714

**Comment by JordiBForgeFlow** [comment]
cc @nuriamartinxifre

**Review by rousseldenis — APPROVED** [review]
Code review. Makes sense.

**Pull request merged**
