### PR TITLE
[13.0] stock_request: add basic qweb report.

### PR DESCRIPTION
**Pull request by adrienpeiffer**

### CODE REVIEW

**Comment by rousseldenis** [comment]
@adrienpeiffer There is a repository for reports there : https://github.com/OCA/stock-logistics-reporting

**Comment by adrienpeiffer** [comment]
@rousseldenis I'm not sure I understand. Should I make a dedicated module for this report in the repository you mention? I see that there are already some in this repository.

**Comment by rousseldenis** [comment]
> @rousseldenis I'm not sure I understand. Should I make a dedicated module for this report in the repository you mention? I see that there are already some in this repository.

Nope, ok, I understand

**Review by rousseldenis — APPROVED** [review]
LGTM. Functionally tested

**Pull request closed without merging**
