### PR TITLE
[12.0][MIG] scrap_reason_code

### PR DESCRIPTION
**Pull request by HviorForgeFlow**
Backport from 13.0

CC @ForgeFlow

### CODE REVIEW

**Comment by rousseldenis** [comment]
@HviorForgeFlow Could you fix tests ?

**Comment by HviorForgeFlow** [comment]
@rousseldenis tests fixed

**Review by rousseldenis — APPROVED** [review]
Code review

**Review by LoisRForgeFlow — APPROVED** [review]

**Pull request merged**
