### PR TITLE
[14.0][MIG] stock_request_analytic (Version 13.0 to 14.0)

### PR DESCRIPTION
**Pull request by patrickrwilson**
Depends on https://github.com/OCA/account-analytic/pull/353

### CODE REVIEW

**Comment by rousseldenis** [comment]
> Depends on PR OCA/account-analytic/#353

You need to put real url here

**Comment by rousseldenis** [comment]
@patrickrwilson Do you plan to finish this ? Could you squash your commits and follow migration guide especially for pre-commit (should be before migration commit)? Thanks

**Comment by rousseldenis** [comment]
@patrickrwilson This is a duplicate of #1066. I've done a new PR #1317. Could you review that one ? Thanks

**Comment by patrickrwilson** [comment]
Superceded by #1317

**Pull request closed without merging**
