### PR TITLE
[15.0][MIG] stock_orderpoint_purchase_link

### PR DESCRIPTION
**Pull request by BernatPForgeFlow**

### CODE REVIEW

**Comment by BernatPForgeFlow** [comment]
@ForgeFlow

**Review by mariadforgeflow — APPROVED** [review]
LGTM

**Review by JoanMForgeFlow — APPROVED** [review]
Looks great!

**Comment by BernatPForgeFlow** [comment]
@LoisRForgeFlow @JordiBForgeFlow

**Pull request merged**
