### PR TITLE
9.0 stock mts mto rule

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
Replaces #156

### CODE REVIEW

**Review by Garamotte — APPROVED** [review]
You should rebase on 9.0 (conflicts on translation files).

Few manual tests, it works as expected.

**Comment by Garamotte** [comment]
@jbeficent : I just created the https://github.com/syleam/stock-logistics-warehouse/commits/9.0-migrate-stock_mts_mto_rule branch on our Github repo.

Could you overwrite your branch by mine to update this PR ?
Or I can supersed this PR by a new one, if you prefer.
I cannot propose a PR on your branch, because there are conflicts : I recreated my branch from current 9.0, then applied the whole migration from 8.0 procedure, then updated from your migration branch.

Note : This PR is included in https://github.com/OCA/stock-logistics-warehouse/pull/203 (migration to v10) which has been merged, so it could be merge quickly.

**Comment by pedrobaeza** [comment]
@sylvain-garancher, better if you just superseed this PR and create a new one.

**Comment by Garamotte** [comment]
Done : https://github.com/OCA/stock-logistics-warehouse/pull/204

**Pull request closed without merging**
