### PR TITLE
[16.0][ADD] stock_package_type_button_box

### PR DESCRIPTION
**Pull request by rousseldenis**

### CODE REVIEW

**Review by lmignon — APPROVED** [review]

**Review by pierre-halleux — APPROVED** [review]

**Comment by lmignon** [comment]
could be useless if https://github.com/odoo/odoo/pull/103494 is merged

**Comment by rousseldenis** [comment]
@dreispt You didn't read @lmignon comment.

Were waiting for https://github.com/odoo/odoo/pull/103494

**Comment by dreispt** [comment]
@rousseldenis It wasn't clear that was a blocking comment, especially since Laurent approved the PR.
Will a revert be needed then?

**Pull request merged**
