### PR TITLE
[MIG][13.0] stock_location_zone migration

### PR DESCRIPTION
**Pull request by guewen**
Migration of `stock_location_zone`, including #711

### CODE REVIEW

**Comment by ps-tubtim** [comment]
@guewen Code LGTM. Could you create tests of this module?

**Comment by simahawk** [comment]
@guewen do you want to merge 12.0 first?
@grindtildeath is that one ready to be re-reviewed?

**Review by jgrandguillaume — APPROVED** [review]
Again, as Alpha for now it's sufficiant for now for me

**Review by simahawk — APPROVED** [review]

**Review by grindtildeath — APPROVED** [review]
Would be great to add tests, but LG :+1:

**Pull request merged**
