### PR TITLE
[11.0][FIX] stock_request: security restrictions error in onchange_warehouse_id

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Fast-track.

As done in https://github.com/OCA/stock-logistics-warehouse/blob/11.0/stock_request/models/stock_request_order.py#L164.

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
@etobella @lreficent @bodedra

**Review by bodedra — APPROVED** [review]

**Review by LoisRForgeFlow — APPROVED** [review]
Thanks!

**Comment by LoisRForgeFlow** [comment]
Closes https://github.com/OCA/stock-logistics-warehouse/issues/769

**Pull request merged**
