### PR TITLE
[13.0][MIG] stock_production_lot_quantity_tree: Migration to 13.0

### PR DESCRIPTION
**Pull request by manuelcalerosolis**
It is the migration of the module to version 13.0

### CODE REVIEW

**Comment by ferran-S73** [comment]
LGTM

**Comment by manuelcalerosolis** [comment]
@ferran-73 please aprove this changes to merge, thanks.

**Comment by rousseldenis** [comment]
@manuelcalerosolis Could you check your last two commits, they seem wrong (message and content)?

image

**Comment by rousseldenis** [comment]
@manuelcalerosolis Nearly :sweat_smile: You can remove the 'Merge' commit.

One more thing, you can add yourself in CONTRIBUTORS.rst

**Comment by rousseldenis** [comment]
You can also read https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0

**Review by HaraldPanten — APPROVED** [review]
Functional review

**Review by rousseldenis — APPROVED** [review]
LGTM

**Pull request merged**
