### PR TITLE
[16.0][MIG] stock_demand_estimate

### PR DESCRIPTION
**Pull request by DavidJForgeFlow**
Standard Migration to 16.0

@ForgeFlow

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]

**Review by JoanSForgeFlow — APPROVED** [review]

**Review by LoisRForgeFlow — APPROVED** [review]
Code review LGTM

**Comment by rousseldenis** [comment]
@LoisRForgeFlow I will update copier

**Comment by LoisRForgeFlow** [comment]
@rousseldenis Thanks!

**Pull request merged**
