### PR TITLE
[11.0][FIX] stock_request_tier_validation: SRO tier validation reviews

### PR DESCRIPTION
**Pull request by HviorForgeFlow**
Previous change was only done on Stock Request, it was missing on Stock Request Order 

CC @Eficent

@lreficent @jbeficent @ageficent 

- [x] Depends on https://github.com/OCA/stock-logistics-warehouse/pull/689 to be merged properly.

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]
Code review

**Review by LoisRForgeFlow — APPROVED** [review]
:+1:

**Comment by rousseldenis** [comment]
@hveficent Could you rebase to see why travis does not like it ?

**Comment by LoisRForgeFlow** [comment]
Let's try again.

/ocabot merge minor

**Review by bodedra — APPROVED** [review]

**Pull request closed without merging**
