### PR TITLE
[12.0][MIG] stock_inventory_discrepancy: Migration to 12.0 

### PR DESCRIPTION
**Pull request by bodedra**

### CODE REVIEW

**Comment by bodedra** [comment]
Anyone help me to make it ci/runbot happy ?

**Comment by bodedra** [comment]
@max3903 @pedrobaeza @lreficent @rousseldenis

**Comment by bodedra** [comment]
@OCA/logistics-maintainers Travis is happy. Would you please help me to understand ci/runbot fail ?

Screenshot_2019-06-25 Build #3884 - OCA stock-logistics-warehouse - Travis CI

**Comment by max3903** [comment]
@bodedra Still 2 warnings from Runbot to fix...

**Comment by bodedra** [comment]
@max3903 Thanks. Comment attended! Now it is :green_apple:

**Comment by bodedra** [comment]
@OCA/logistics-maintainers would you please change label from "needs fixing" to "needs review"

**Review by rousseldenis — APPROVED** [review]
Code review

**Comment by bodedra** [comment]
@lreficent @osimallen  Would you please review these.

**Review by osimallen — APPROVED** [review]
LGTM

**Pull request closed without merging**
