### PR TITLE
[13.0][MIG] procurement_auto_create_group

### PR DESCRIPTION
**Pull request by HviorForgeFlow**
Standard migration 
CC @Forgeflow @LoisRForgeFlow

### CODE REVIEW

**Review by LoisRForgeFlow — APPROVED** [review]
Code review, LGTM!

**Review by JordiBForgeFlow — APPROVED** [review]
:+1: Tested on runbot. Works as expected.

**Review by jgrandguillaume — APPROVED** [review]
LGTM

**Pull request merged**
