### PR TITLE
[MIG] stock_vertical_lift_packaging_type: Migration to 14.0

### PR DESCRIPTION
**Pull request by dzungtran89**
Dependencies:
- stock_vertical_lift: https://github.com/OCA/stock-logistics-warehouse/pull/1090
- product_packaging_type: https://github.com/OCA/product-attribute/pull/760

### CODE REVIEW

**Comment by mmequignon** [comment]
@dzungtran89 what's the status of this one, is it still in progress?

**Review by sebalix — APPROVED** [review]
LG, besides the dependencies to update later once they are merged

**Comment by mmequignon** [comment]
@dzungtran89 is it in progress?

**Comment by dzungtran89** [comment]
Hi @mmequignon yes, we've been waiting for #1090 merged

**Comment by dzungtran89** [comment]
I removed the test deps

**Review by simahawk — APPROVED** [review]

**Pull request merged**
