### PR TITLE
[11.0][WIP] stock_orderpoint_manual_procurement: 

### PR DESCRIPTION
**Pull request by LoisRForgeFlow**
Readd date_planned to wizard ~(currently not working, js issue). This fix is not ready, I open it as a reference to report the issue to Odoo.~

EDIT: now is ready

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
issue fixed here: https://github.com/odoo/odoo/commit/52cd52e624d987916ea62e566cc777505c13e469

It should be ready now.

**Comment by rousseldenis** [comment]
@lreficent  Needs review ?

**Comment by LoisRForgeFlow** [comment]
@rousseldenis yes, it does

**Review by max3903 — APPROVED** [review]

**Comment by rousseldenis** [comment]
@lreficent Maybe a little add in tests for the value ?

**Comment by LoisRForgeFlow** [comment]
@rousseldenis Done and :green_apple: tests

**Review by MiquelRForgeFlow — APPROVED** [review]

**Pull request merged**
