### PR TITLE
[10.0][FIX] stock_orderpoint_uom, stock_quant_manual_assign

### PR DESCRIPTION
**Pull request by rousseldenis**
Constrains need to raise ValidationError

### CODE REVIEW

**Comment by rousseldenis** [comment]
Due to https://github.com/odoo/odoo/commit/2b1d3ff82dd23fb0372b3b73ecb84841a0d593d3, only ValidationError has to be raised in constrains.

**Review by florian-dacosta — APPROVED** [review]
Thanks for this fix!

**Comment by rousseldenis** [comment]
Wait for Travis and will merge

**Comment by rousseldenis** [comment]
@OCA/core-maintainers Please check your repos for this if you have red main branches.

**Pull request merged**
