### PR TITLE
[12.0][MIG] stock_inventory_exclude_sublocation: Migration to 12.0

### PR DESCRIPTION
**Pull request by bodedra**

### CODE REVIEW

**Comment by bodedra** [comment]
Travis is :green_apple:

@lreficent @pedrobaeza

**Review by HaraldPanten — APPROVED** [review]
Functional review 👍

**Review by tbaden — APPROVED** [review]
thanks for the work 👍 
I did a code review: LGTM

**Comment by bodedra** [comment]
@HaraldPanten @tbaden Thanks for your review and feedback.

@OCA/logistics-maintainers Would you please merge these or any feedback ?

**Review by rousseldenis — APPROVED** [review]
Code review

**Pull request merged**
