### PR TITLE
Correction for translation issue on menu item

### PR DESCRIPTION
**Pull request by augustodinizl**
as posted on issue:#741 only aim to correct the pointed error

### CODE REVIEW

**Review by LoisRForgeFlow — APPROVED** [review]
Thanks :+1: 

(note for whoever merges it, it would be would to squash the fix into one commit)

**Review by LoisRForgeFlow — CHANGES_REQUESTED** [review]
Actually there is a small lint that you need to fix: 

`stock_request_submit/models/stock_request.py:4:1: F401 'odoo._' imported but unused`

**Comment by rousseldenis** [comment]
@augustodinizl Could you change PR's title to mention module name ?

**Comment by LoisRForgeFlow** [comment]
This issue has been fixed here: https://github.com/OCA/stock-logistics-warehouse/pull/780.

**Pull request closed without merging**
