### PR TITLE
[11.0][ADD]push_rule_auto_create_group

### PR DESCRIPTION
**Pull request by AaronHForgeFlow**
Similar concept that procurement_auto_create_group but for push rules. In many cases we don't want to group quantities in the same picking.

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]
LGTM! Thanks. Code review

**Comment by rousseldenis** [comment]
@AaronHForgeFlow Maybe a little test ?

**Comment by AaronHForgeFlow** [comment]
Little test added :)

**Review by HviorForgeFlow — APPROVED** [review]

**Comment by rousseldenis** [comment]
@AaronHForgeFlow Can you squash your commits ?

**Comment by AaronHForgeFlow** [comment]
@rousseldenis done! :)

**Pull request merged**
