### PR TITLE
[11.0][FIX] stock_request: sudoing

### PR DESCRIPTION
**Pull request by HviorForgeFlow**
At some point using previous sudos, some context are lost.

### CODE REVIEW

**Comment by HviorForgeFlow** [comment]
hey, @etobella @jbeficent with this fix stock request users are able to see generated transfers once they are confirmed. It seems it is not breaking any other workflows. Could you review it?

**Comment by HviorForgeFlow** [comment]
Having this error if user has only stock_request_user. Should Stock Request User read from stock_move ??
image

Event if it is forced to read, users won't be able to see stock move info

**Comment by JordiBForgeFlow** [comment]
The stock request user should have the minimum permissions to create and
view stock.move, stock.move.line, stock picking,... So that this kind of
error does not occur.

Sudoing prevents this from being needed, but is also generating the side
effect that you noticed.

**Comment by etobella** [comment]
@hveficent , could you improve the permissions of stock request user in order to fix the issue?

**Review by JordiBForgeFlow — APPROVED** [review]

**Review by etobella — APPROVED** [review]

**Review by chienandalu — APPROVED** [review]
Looks good :+1:

**Review by chienandalu — CHANGES_REQUESTED** [review]
Sorry, I didn't notice that there's a travis error. Could you check?

**Comment by pedrobaeza** [comment]
Can you check Travis?

**Comment by HviorForgeFlow** [comment]
Travis errors are not related to this PR.
See https://github.com/OCA/stock-logistics-warehouse/pull/552

**Review by rousseldenis — APPROVED** [review]
Seems good to me

**Comment by rousseldenis** [comment]
@hveficent Is this complete ?

**Comment by rousseldenis** [comment]
@chienandalu Could you update your review?

**Review by chienandalu — APPROVED** [review]

**Pull request merged**
