### PR TITLE
[IMP][stock_mts_mto_rule] set pull rule of customer location like spl…

### PR DESCRIPTION
**Pull request by JulioSerna**
…it_procurement to allow when warehouse is two/three steps delivery propagate move by mts-mto in pick/pack/out

### CODE REVIEW

**Comment by nhomar** [comment]
:+1:

**Comment by nhomar** [comment]
Hello....

Do I need another +1 here @jbeficent @pedrobaeza @rvalyi  @ somebody :-)

**Comment by moylop260** [comment]
:+1: wo tests

**Comment by pedrobaeza** [comment]
:+1: (code review)

**Comment by asoral** [comment]
I have an issue on the latest version of MTO/MTS used in odoo8 (recent)
1. create a chained pull rules like -> when a sales order is created procurement chain is created like - Customer location <- sales Staging <- MTO/MTS <- MO/stock move
2. Cancel the procurement MTO/MTS, it does not have a STOCK MOVE associated since it was a dummy procurement without a stock move to check the inventory level
3. System will not propagate the cancellation because it looks for the stock move in the procurement to cancel but this procurement will have none, so it is not canceled.

**Comment by moylop260** [comment]
@asoral 
Please, Could you create a [new issue](https://github.com/OCA/stock-logistics-warehouse/issues/new)?
Explain Steps, Saw, Expected, sha's of your environment, add images or video of your steps

**Pull request merged**
