### PR TITLE
[14.0][ADD] stock_inventory_revaluation_wip

### PR DESCRIPTION
**Pull request by patrickrwilson**
Depends on #1227

### CODE REVIEW

**Comment by patrickrwilson** [comment]
@Chandresh-SerpentCS here is the new PR you requested since the other one was close (PR #1279 )

**Comment by dreispt** [comment]
@patrickrwilson @Chandresh-SerpentCS Pelse fix warning: `odoo.models: The model add.multi.product has no _description`

**Comment by rousseldenis** [comment]
@patrickrwilson This is not an addition. This module already exists. Please feel free to migrate it instead.

https://github.com/OCA/stock-logistics-warehouse/tree/12.0/stock_inventory_revaluation

**Review by dreispt — CHANGES_REQUESTED** [review]
@Chandresh-SerpentCS 
This is missing a dependency on `mrp_account_analytic_wip`.
That is the module that assigns "Cost Type" Products to workcenter operations.

Also, I see references to `analytic_cost_ids` in `stock_inventory_revaluation_mrp` that should be not there, as that module does not have and should not have those dependencies.
Those references should be added as extension in this module.

**Comment by rousseldenis** [comment]
@patrickrwilson @dreispt What's the status of this ?

**Comment by dreispt** [comment]
We are doing QA on this and has active WIP.
I was considering moving it away from here, as I see little probability to see it merged.

**Pull request closed without merging**
