### PR TITLE
[15.0][MIG]stock_available_unreserved

### PR DESCRIPTION
**Pull request by JoanMForgeFlow**
Standard migration to version 15.0.
@AaronHForgeFlow @mariadforgeflow

### CODE REVIEW

**Review by mariadforgeflow — APPROVED** [review]
LGTM!

**Review by AaronHForgeFlow — APPROVED** [review]
Functional tests :+1:

**Comment by JoanMForgeFlow** [comment]
@pedrobaeza could we merge this module?

**Comment by pedrobaeza** [comment]
Merging trusting on the reviewers:

/ocabot merge nobump
/ocabot migration stock_available_unreserved

**Pull request merged**
