### PR TITLE
[14.0][IMP] stock_helper: development_status -> Stable

### PR DESCRIPTION
**Pull request by mt-software-de**

### CODE REVIEW

**Comment by mt-software-de** [comment]
@jbaudoux could we update the development_status?

**Comment by mt-software-de** [comment]
@simahawk or @sebalix could you please review this and merge it?

**Comment by mt-software-de** [comment]
ping @jbaudoux

**Review by jbaudoux — APPROVED** [review]

**Comment by jbaudoux** [comment]
cc @rousseldenis

**Review by rousseldenis — APPROVED** [review]
Yes. Even if for long term, I'd prefer having a module per functionnality and more explicit as this module can quickly become a mess.

**Comment by mt-software-de** [comment]
@jbaudoux could you merge this one?

**Pull request merged**
