### PR TITLE
[14.0][MIG] stock_account_change_qty_reason

### PR DESCRIPTION
**Pull request by Deriman-Alonso**

### CODE REVIEW

**Review by AungKoKoLin1997 — APPROVED** [review]
Code Review: LGTM

**Comment by rousseldenis** [comment]
@Deriman-Alonso Thanks for this. Could you follow this next time ? https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0#technical-method-to-migrate-a-module-from-130-to-140-branch

Especially to have two separate commits for migration and pre-commit.

Could you also include module name in your migration commit (like [14.0][MIG] stock_account_change_qty_reason) ? Thanks

image

**Comment by Deriman-Alonso** [comment]
@rousseldenis  Hi, thats done 👍.

**Pull request closed without merging**
