### PR TITLE
[12.0][MIG] stock_request_purchase

### PR DESCRIPTION
**Pull request by kittiu**
Done migrated.

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]
Code review

**Review by tbaden — CHANGES_REQUESTED** [review]
thanks for the work 👍 
I did a code review:
please use the [fragment readme](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0)  mentioned in the migration guidelines

**Comment by kittiu** [comment]
Thank you all, I did the readme.

**Review by tbaden — APPROVED** [review]

**Pull request closed without merging**
