### PR TITLE
[MIG] scrap_reason_code: Migration to 15.0

### PR DESCRIPTION
**Pull request by glitchov**

### CODE REVIEW

**Comment by CasVissers-360ERP** [comment]
@rousseldenis Your merge failed?

**Review by PierrickBrun — APPROVED** [review]
LGTM

**Comment by rousseldenis** [comment]
> @rousseldenis Your merge failed?

Was not a merge. Just using ocabot to update Migration issue.

**Review by rousseldenis — APPROVED** [review]

**Pull request merged**
