### PR TITLE
14.0 mig stock inventory include exhausted

### PR DESCRIPTION
**Pull request by sebastienbeau**

### CODE REVIEW

**Comment by sebastienbeau** [comment]
@CarlosRoca13

**Review by CarlosRoca13 — APPROVED** [review]
Tested locally :+1: I can't run the runbot

**Comment by CarlosRoca13** [comment]
Please, when you can squash the administrative commits

**Review by rousseldenis — APPROVED** [review]

**Review by atchuthan — APPROVED** [review]

**Review by hparfr — APPROVED** [review]

**Pull request merged**
