### PR TITLE
[13.0][FIX] stock_archive_constraint: ValidationError message not displaying correctly

### PR DESCRIPTION
**Pull request by stefan-tecnativa**
cc@Tecnativa TT41908

@victoralmau please review!

### CODE REVIEW

**Review by victoralmau — CHANGES_REQUESTED** [review]
Also add the change for the rest of the messages.

Modify also the PR title: `[13.0][FIX] stock_archive_constraint: ValidationError message not displaying correctly`

**Comment by pedrobaeza** [comment]
The commit message should be `[FIX] stock_archive_constraint: ValidationError message not displaying correctly` (with the module name).

**Review by carlosdauden — APPROVED** [review]

**Review by sergio-teruel — APPROVED** [review]

**Review by victoralmau — CHANGES_REQUESTED** [review]
Can you also change `stock.location` messages?
Can you update the spanish translations after these changes?

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
/ocabot merge patch

Translations are already OK.

**Pull request merged**
