### PR TITLE
[Migration][11] module stock_mts_mto_rule

### PR DESCRIPTION
**Pull request by florian-dacosta**
Standard migration
@zaoral @sylvain-garancher 

It would be nice to add it here : https://github.com/OCA/stock-logistics-warehouse/issues/343

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Added in migration issue. Please squash together adjacent "OCA Transbot..." commits using https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests

**Comment by florian-dacosta** [comment]
Thanks @pedrobaeza for updating the migration issue.
I squashed it, sorry I forgot!

**Comment by umiphos** [comment]
@florian-dacosta working good, +1

**Comment by JulioSerna** [comment]
I tested this pr and works
👍

**Comment by josemoralesp** [comment]
it works :+1:

**Comment by aitorbouzas** [comment]
Merge this?

**Comment by pedrobaeza** [comment]
It requires a review from a PSC member

**Review by mourad-ehm — APPROVED** [review]

**Comment by nhomar** [comment]
@pedrobaeza It does not require 3 votes only? we  are not PSC on this but we actually tested on 2 internal projects already IMHO this can be merged.

**Comment by pedrobaeza** [comment]
OK, let's go then. Merging!

**Pull request merged**
