### PR TITLE
[WIP] 8.0 mig stock inventory exclude sublocation

### PR DESCRIPTION
**Pull request by daramousk**

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
Hi @daramousk and thanks for the contribution.

You don't need to manually modify .po files, they will be updated automatically after merge.

**Comment by daramousk** [comment]
@lreficent Thanks for the help, fixed now. On this PR and on the other two I have opened

**Comment by LoisRForgeFlow** [comment]
@daramousk usually on back and forward port we squash consecutive "OCA Transbot..." commits together, it would be great if you do that. You should also have a look to travis, it is complaining :red_circle:

**Comment by daramousk** [comment]
@lreficent Fixed travis complains, squashed translation commits

**Review by LoisRForgeFlow — APPROVED** [review]
Everything is green and code seems ok, LGTM

**Review by gurneyalex — APPROVED** [review]

**Pull request merged**
