### PR TITLE
[14.0][FIX] stock_orderpoint_origin: correct procurement_group field for pickings

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Fine repush (squashed) of https://github.com/OCA/stock-logistics-warehouse/pull/1433.

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
@AlejandroBlueOrange @dreispt @rousseldenis @flotho 

NOTE: I am too lazy to add a test. I think in this case a adding test is not mandatory, because simply looking in odoo code you can see that the procurement group m2o field for pickings is "group_id".

**Review by AaronHForgeFlow — APPROVED** [review]
Code review

**Review by flotho — APPROVED** [review]
LGTM, thanks a lot !

**Review by giarve — APPROVED** [review]

**Comment by giarve** [comment]
@rousseldenis 

This one seems to be ready for an /ocabot merge patch 🚀 

thanks.

**Review by rousseldenis — APPROVED** [review]

**Pull request merged**
