### PR TITLE
[17.0][MIG] stock_quant_reservation_info_mrp: Migration to 17.0

### PR DESCRIPTION
**Pull request by MeritxellAForgeFlow**
Standard migration to 17.0

Depends on #2208

### CODE REVIEW

**Comment by rousseldenis** [comment]
@MeritxellAForgeFlow Thanks for this. FYI, you can embed the dependency here in order to:

- Make tests running
- Be able to review it funcionaly through runboat

Follow: https://github.com/OCA/maintainer-tools/wiki/Use-temporary-reference%28s%29-to-another-pull-request%28s%29

**Comment by LoisRForgeFlow** [comment]
@MeritxellAForgeFlow Could you rebase now that the dependency has been merged?

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM :+1:

**Pull request merged**
