### PR TITLE
[14.0][MIG] stock_warehouse_calendar

### PR DESCRIPTION
**Pull request by DavidBForgeFlow**
Standard migration to v14.

cc@LoisRForgeFlow

### CODE REVIEW

**Comment by rousseldenis** [comment]
@DavidBForgeFlow Could you check Travis error ?

**Comment by DavidBForgeFlow** [comment]
@rousseldenis 

Checked!!

**Comment by LoisRForgeFlow** [comment]
@DavidBForgeFlow You have to fix conflicts in the history of this PR. There should not be any merge commit:
image

**Review by LoisRForgeFlow — APPROVED** [review]

**Review by MateuGForgeFlow — APPROVED** [review]

**Review by MateuGForgeFlow — APPROVED** [review]

**Pull request merged**
