### PR TITLE
[14.0][MIG] stock_request_direction

### PR DESCRIPTION
**Pull request by kittiu**
Standard migration

Dependency:

- [x] stock_request https://github.com/OCA/stock-logistics-warehouse/pull/1134
- [x] https://github.com/OCA/stock-logistics-warehouse/pull/1127

### CODE REVIEW

**Comment by kittiu** [comment]
cc @ps-tubtim @rousseldenis

**Review by ps-tubtim — APPROVED** [review]
@kittiu Code LGTM. Do you plan to improve codecov?

**Comment by kittiu** [comment]
Test added

**Comment by kittiu** [comment]
Note: I ran `copier update` also

**Comment by Freni-OSI** [comment]
@kittiu, can you improve test coverage? Thanks.

**Comment by Freni-OSI** [comment]
#1222

**Comment by kittiu** [comment]
> #1222

Thanks @Freni-OSI another option though. Except the test. If you see this PR workable, you can approve it and the maintainer can merge. Then you create another to add only test.

**Comment by kittiu** [comment]
Superseded by https://github.com/OCA/stock-logistics-warehouse/pull/1223

**Pull request closed without merging**
