### PR TITLE
[12.0][FIX] stock_secondary_unit, update secondary_uom_qty on move line

### LINKED ISSUE #1188: [12.0] stock_secondary_unit "secondary qty" value in picking not affecting "initial demand"
AFFECTED VERSIONS

12.0 (it works ok on 13.0)

STEPS TO REPRODUCE

Activate Units of Measure in general settings > inventory

Inventory > Master Data > Products > Set a secondary unit in a product

image

Create a new transfer > add product > select secondary UoM > input secondary qty

image

CURRENT BEHAVIOR

Value "Initial demand" is not affected by secondary qty input
In the same way, if "Initial demand" is set, "secondary qty" does not change - basically there is no relation between the two fields

image

REQUIRED BEHAVIOR 

When "secondary qty" is updated, also "initial demand" should update - and viceversa, as it happens in SO with secondary unit modules

VIDEO

https://recordit.co/zcuDUx6xco

### PR DESCRIPTION
**Pull request by GSLabIt**
fix #1188

### CODE REVIEW

**Review by francesco-ooops — APPROVED** [review]
@GSLabIt it works well

**Comment by GSLabIt** [comment]
@sergio-teruel, @enriquemartin any chance to review?

**Review by sergio-teruel — APPROVED** [review]
This code is not needed in v13.0

**Pull request merged**
