### PR TITLE
[16.0][ADD] Add stock_available module in v16

### PR DESCRIPTION
**Pull request by bvanjeelharia**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Thanks for the contribution.

Please preserve commit history following technical method explained in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0.

If the jump is between several versions, you have to modify the source branch in the main command to accommodate it to this circumstance.

**Comment by bvanjeelharia** [comment]
Hello Pedro,

Is it fine with the latest pull request or still some changes needed?

Thanks and Regards,
[image: Logo] <https://www.brainvire.com/> [image: Logo]
Anjeel Haria
Software Engineer
M: +91 00000 00000
P: +91-22-61163300 / *EXTN:* 100
E: ***@***.***
W: www.brainvire.com
[image: Facebook icon] <https://www.facebook.com/Brainvire> [image:
LinkedIn icon] <https://www.linkedin.com/company/brainvire-infotech-inc/>
[image:
Twitter icon] <https://twitter.com/Brainvire> [image: Blog]
<https://www.brainvire.com/blog/?utm_source=email-signature>
[image: Company of the Year]
<https://www.brainvire.com/brainvire-recognized-as-company-of-the-year/>
[image:
Reviewed on clutch]
<https://clutch.co/profile/brainvire-infotech#review-491817> [image:
Reviewed on clutch]
<https://clutch.co/profile/brainvire-infotech#reviews> [image:
Digital Best Commerce Development Company]
<https://www.brainvire.com/recognized-as-best-ecommerce-development-company/>
[image:
Good Firms Top Web Developers]
<https://www.goodfirms.co/companies/view/1512/brainvire-infotech-inc>

Disclaimer: The information transmitted by this email is intended only for
the person or entity to which it is addressed. This email may contain
proprietary, business-confidential and/or privileged material. Please
consider the environment before printing.

**Comment by pedrobaeza** [comment]
I'm afraid it's not. Please check instructions.

**Comment by bvanjeelharia** [comment]
I didn't get this point - If the jump is between several versions, you have
to modify the source branch in the main command to accommodate it to this
circumstance.

Can you please explain a bit in detail

Thanks and Regards,
[image: Logo] <https://www.brainvire.com/> [image: Logo]
Anjeel Haria
Software Engineer
M: +91 00000 00000
P: +91-22-61163300 / *EXTN:* 100
E: ***@***.***
W: www.brainvire.com
[image: Facebook icon] <https://www.facebook.com/Brainvire> [image:
LinkedIn icon] <https://www.linkedin.com/company/brainvire-infotech-inc/>
[image:
Twitter icon] <https://twitter.com/Brainvire> [image: Blog]
<https://www.brainvire.com/blog/?utm_source=email-signature>
[image: Company of the Year]
<https://www.brainvire.com/brainvire-recognized-as-company-of-the-year/>
[image:
Reviewed on clutch]
<https://clutch.co/profile/brainvire-infotech#review-491817> [image:
Reviewed on clutch]
<https://clutch.co/profile/brainvire-infotech#reviews> [image:
Digital Best Commerce Development Company]
<https://www.brainvire.com/recognized-as-best-ecommerce-development-company/>
[image:
Good Firms Top Web Developers]
<https://www.goodfirms.co/companies/view/1512/brainvire-infotech-inc>

Disclaimer: The information transmitted by this email is intended only for
the person or entity to which it is addressed. This email may contain
proprietary, business-confidential and/or privileged material. Please
consider the environment before printing.

**Comment by rousseldenis** [comment]
@bvanjeelharia As @pedrobaeza said, please follow migration guide especially 'Full process' part.

**Comment by pedrobaeza** [comment]
If you are catching the module from v14 instead of v15, on the instructions where it puts 15.0, put 14.0.

**Comment by florian-dacosta** [comment]
Hello @bvanjeelharia 

The modules regarding stock availability have changed repository, they should now be there : https://github.com/oca/stock-logistics-availability

And `stock_available` seems to be available in version 16 already.

**Comment by bvanjeelharia** [comment]
Hello Florian,

Thank you for your reply.Yes, the modules are available in the mentioned
repo.I would use those. But I needed one more module
sale_stock_available_info_popup - it is not available in version 16, can
you help me with that?

Thanks and Regards,
[image: Logo] <https://www.brainvire.com/> [image: Logo]
Anjeel Haria
Software Engineer
M: +91 00000 00000
P: +91-22-61163300 / *EXTN:* 100
E: ***@***.***
W: www.brainvire.com
[image: Facebook icon] <https://www.facebook.com/Brainvire> [image:
LinkedIn icon] <https://www.linkedin.com/company/brainvire-infotech-inc/>
[image:
Twitter icon] <https://twitter.com/Brainvire> [image: Blog]
<https://www.brainvire.com/blog/?utm_source=email-signature>
[image: Company of the Year]
<https://www.brainvire.com/brainvire-recognized-as-company-of-the-year/>
[image:
Reviewed on clutch]
<https://clutch.co/profile/brainvire-infotech#review-491817> [image:
Reviewed on clutch]
<https://clutch.co/profile/brainvire-infotech#reviews> [image:
Digital Best Commerce Development Company]
<https://www.brainvire.com/recognized-as-best-ecommerce-development-company/>
[image:
Good Firms Top Web Developers]
<https://www.goodfirms.co/companies/view/1512/brainvire-infotech-inc>

Disclaimer: The information transmitted by this email is intended only for
the person or entity to which it is addressed. This email may contain
proprietary, business-confidential and/or privileged material. Please
consider the environment before printing.

**Comment by florian-dacosta** [comment]
@bvanjeelharia 
Well, you have to follow the guidelines indicated by Pedro.
Since there is a change of repository, it is a bit more tricky, this should work : 

```
git clone https://github.com/OCA/stock-logistics-availability -b 16.0
cd stock-logistics-availability
git checkout -b 16.0-mig-sale_stock_available_info_popup origin/16.0
git remote add oca_wh https://github.com/OCA/stock-logistics-warehouse
git fetch oca_wh
git format-patch --keep-subject --stdout origin/16.0..oca_wh/15.0 -- sale_stock_available_info_popup | git am -3 --keep
pre-commit run -a
git add -A
git commit -m "[IMP] $module: pre-commit stuff"  --no-verify
```

Then migrate the module and keep following the guidelines, and once finished, make a PR against stock-logistics-availability repository

**Comment by bvanjeelharia** [comment]
Hello Florian,

Getting this issue - remote: Repository not found.
fatal: repository '
https://github.com/bvanjeelharia/stock-logistics-availability.git/' not
found

when trying to push content to github using git push bvanjeelharia
16.0-mig-sale_stock_available_info_popup --set-upstream

Can you please let me know what might be the issue here?

Thanks and Regards,
[image: Logo] <https://www.brainvire.com/> [image: Logo]
Anjeel Haria
Software Engineer
M: +91 00000 00000
P: +91-22-61163300 / *EXTN:* 100
E: ***@***.***
W: www.brainvire.com
[image: Facebook icon] <https://www.facebook.com/Brainvire> [image:
LinkedIn icon] <https://www.linkedin.com/company/brainvire-infotech-inc/>
[image:
Twitter icon] <https://twitter.com/Brainvire> [image: Blog]
<https://www.brainvire.com/blog/?utm_source=email-signature>
[image: Company of the Year]
<https://www.brainvire.com/brainvire-recognized-as-company-of-the-year/>
[image:
Reviewed on clutch]
<https://clutch.co/profile/brainvire-infotech#review-491817> [image:
Reviewed on clutch]
<https://clutch.co/profile/brainvire-infotech#reviews> [image:
Digital Best Commerce Development Company]
<https://www.brainvire.com/recognized-as-best-ecommerce-development-company/>
[image:
Good Firms Top Web Developers]
<https://www.goodfirms.co/companies/view/1512/brainvire-infotech-inc>

Disclaimer: The information transmitted by this email is intended only for
the person or entity to which it is addressed. This email may contain
proprietary, business-confidential and/or privileged material. Please
consider the environment before printing.

**Comment by bvanjeelharia** [comment]
Hello Florian,

Please ignore my last email, I figured that out

Thanks and Regards,
[image: Logo] <https://www.brainvire.com/> [image: Logo]
Anjeel Haria
Software Engineer
M: +91 00000 00000
P: +91-22-61163300 / *EXTN:* 100
E: ***@***.***
W: www.brainvire.com
[image: Facebook icon] <https://www.facebook.com/Brainvire> [image:
LinkedIn icon] <https://www.linkedin.com/company/brainvire-infotech-inc/>
[image:
Twitter icon] <https://twitter.com/Brainvire> [image: Blog]
<https://www.brainvire.com/blog/?utm_source=email-signature>
[image: Company of the Year]
<https://www.brainvire.com/brainvire-recognized-as-company-of-the-year/>
[image:
Reviewed on clutch]
<https://clutch.co/profile/brainvire-infotech#review-491817> [image:
Reviewed on clutch]
<https://clutch.co/profile/brainvire-infotech#reviews> [image:
Digital Best Commerce Development Company]
<https://www.brainvire.com/recognized-as-best-ecommerce-development-company/>
[image:
Good Firms Top Web Developers]
<https://www.goodfirms.co/companies/view/1512/brainvire-infotech-inc>

Disclaimer: The information transmitted by this email is intended only for
the person or entity to which it is addressed. This email may contain
proprietary, business-confidential and/or privileged material. Please
consider the environment before printing.

**Pull request closed without merging**
