### PR TITLE
[14.0][IMP] stock_available_unreserved make field optional in tree view

### PR DESCRIPTION
**Pull request by remi-filament**
Add optional attribute for tree view so that field can be hidden (like for the other ones in tree view)

### CODE REVIEW

**Comment by rousseldenis** [comment]
@remi-filament Could you check pre-commit ? You should install it prior committing locally.

**Comment by remi-filament** [comment]
Hi, I had no issue reported locally, the issue reported with pre-commit seems to come from JS file from stock_inventory_discrepancy...
I am not sure why this was not reported before that module was merged ?

**Comment by rousseldenis** [comment]
@remi-filament This is the real error : Can you fix it ?

image

**Comment by remi-filament** [comment]
Sure, sorry I missed it, the change was pending in my unstaged files !

**Review by rousseldenis — APPROVED** [review]

**Review by jordancoest — APPROVED** [review]

**Comment by pedrobaeza** [comment]
This should be reverted ASAP, as adding a computed field in the tree makes the view terribly slow, having to do the computation for the number of elements in the tree (usually 80), and it doesn't matter you have it hidden, it will always be computed.

**Comment by rousseldenis** [comment]
> This should be reverted ASAP, as adding a computed field in the tree makes the view terribly slow, having to do the computation for the number of elements in the tree (usually 80), and it doesn't matter you have it hidden, it will always be computed.

What are you talking about ? No field was added

**Comment by pedrobaeza** [comment]
Indeed, this PR is not adding it (only making it optional), sorry, but the rationale is the same, so I think the field should be removed from the view.

**Comment by rousseldenis** [comment]
> Indeed, this PR is not adding it (only making it optional), sorry, but the rationale is the same, so I think the field should be removed from the view.

There from all versions, so your ask is unrelevant. That should not be changed.

**Comment by pedrobaeza** [comment]
Then at least a note on the README can be added warning about that IMO.

**Pull request merged**
