### PR TITLE
[14.0] [IMP] stock_packaging_calculator - forward port

### PR DESCRIPTION
**Pull request by hiepnh97**

### CODE REVIEW

**Comment by rousseldenis** [comment]
@hiepnh97 Could you change PR title as this is not a migration but enhancement ?

**Comment by hiepnh97** [comment]
hi @rousseldenis , the title is updated.
If the new title is not right, please give me a guideline for changing the title (because I can't find any guideline for enhancement PR). Thank You.

**Comment by rousseldenis** [comment]
> hi @rousseldenis , the title is updated.
> If the new title is not right, please give me a guideline for changing the title (because I can't find any guideline for enhancement PR). Thank You.

The only guidelines are there https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst

For github PR's, the common sense is applying. Just make it with meaningful title and description. Usually with [MIG], [IMP], [ADD], ...

**Comment by hiepnh97** [comment]
Hi @rousseldenis , Please help me to recheck the new title! Thank you!

**Review by simahawk — APPROVED** [review]

**Pull request merged**
