### PR TITLE
[16.0][MIG] stock_free_quantity: Migration to 16.0

### PR DESCRIPTION
**Pull request by EvaSForgeFlow**
Correcting tests.

### CODE REVIEW

**Comment by rousseldenis** [comment]
@EvaSForgeFlow You created a duplicate PR here. You already created #1758 

As already said, this module should go there : https://github.com/OCA/stock-logistics-availability/

**Comment by LoisRForgeFlow** [comment]
@EvaSForgeFlow Also pay attention to the migration process, you are mixing "pre-commit stuff" and actual migration changes (in this case just the version bump).

**Comment by EvaSForgeFlow** [comment]
My apologies, the module is now on: https://github.com/OCA/stock-logistics-availability/pull/9 .

**Comment by rousseldenis** [comment]
> My apologies, the module is now on: [OCA/stock-logistics-availability#9](https://github.com/OCA/stock-logistics-availability/pull/9) .

No problem. Great !

**Pull request closed without merging**
