### PR TITLE
[14.0][FIX] stock_orderpoint_origin: AttributeError: 'stock.picking' object has no attribute 'procurement_group_id'

### PR DESCRIPTION
**Pull request by AlejandroBlueOrange**

### CODE REVIEW

**Comment by rousseldenis** [comment]
@AlejandroBlueOrange @dreispt This should deserves tests in order to avoid such regressions.

**Review by MiquelRForgeFlow — APPROVED** [review]
@AlejandroBlueOrange please, run pre-commit

**Comment by MiquelRForgeFlow** [comment]
Please, squash all in one commit with title "[FIX] stock_orderpoint_origin: correct procurement_group field for pickings"

**Comment by rousseldenis** [comment]
@AlejandroBlueOrange Please rearrange your commits as  @MiquelRForgeFlow said and add a test

**Review by flotho — CHANGES_REQUESTED** [review]
faced same issue locally and it fixed the issue.
Yet is double assignation mandatory ?

**Comment by flotho** [comment]
@AlejandroBlueOrange , any chance to adapt your code ?

**Review by flotho — APPROVED** [review]

**Comment by flotho** [comment]
hi @AlejandroBlueOrange , any chance to adapt your code as everything is mmostly accepted by the community

**Pull request closed without merging**
