### PR TITLE
[ADD] stock_move_location_purchase_uom

### PR DESCRIPTION
**Pull request by MarinaAForgeFlow**
* [x] : Depends on this open PR: https://github.com/OCA/stock-logistics-warehouse/pull/1945

### CODE REVIEW

**Review by AaronHForgeFlow — APPROVED** [review]
Code review LGTM

**Review by MiquelRForgeFlow — APPROVED** [review]
LGTM

**Review by AungKoKoLin1997 — APPROVED** [review]
LGTM: Code Review

**Review by LoisRForgeFlow — APPROVED** [review]
:+1:

**Comment by JohnMAllay011** [comment]
[👍](https://deliverredtransport.com/)

**Pull request merged**
