### PR TITLE
[14.0][MIG] stock_cycle_count

### PR DESCRIPTION
**Pull request by MateuGForgeFlow**
Standard Migration to v14.
cc @LoisRForgeFlow @JoanSForgeFlow

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
@MateuGForgeFlow can you cherry-pick this fix (https://github.com/OCA/stock-logistics-warehouse/pull/1185) here?

**Review by LoisRForgeFlow — APPROVED** [review]
Tested locally

**Review by JoanSForgeFlow — APPROVED** [review]
LGTM! :+1:

**Comment by rousseldenis** [comment]
@MateuGForgeFlow @LoisRForgeFlow There are a some warnings on runbot:

image


Could you please fix them as new builds are marked as errored. Thanks

**Comment by MateuGForgeFlow** [comment]
Hi @rousseldenis ! Thank you for the comment.
PR opened: https://github.com/OCA/stock-logistics-warehouse/pull/1283

**Pull request merged**
