### PR TITLE
[15.0][PORT] stock_location_tray: Porting from 14.0 to 15.0

### PR DESCRIPTION
**Pull request by GabbasovDinar**

### CODE REVIEW

**Comment by rousseldenis** [comment]
/ocabot migration stock_location_tray

@GabbasovDinar Thanks for this. Could you check your commit user (diga) as it seems not associated with your github account (GabbasovDinar) ?

**Comment by rousseldenis** [comment]
@GabbasovDinar Don't forget to follow migration guide https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0

Especially commit name (that should reflect a 'migration')

**Comment by Aldeigja** [comment]
@OCA/logistics-maintainers-psc-representative could you review?

**Comment by GabbasovDinar** [comment]
how to restore this PR?

**Comment by GabbasovDinar** [comment]
How to reopen this PR?

**Comment by rousseldenis** [comment]
> How to reopen this PR?

@GabbasovDinar Unfortiunately, you need to open a new PR

**Pull request closed without merging**
