### PR TITLE
[12.0][FIX] Stock Request Order purchase button fix

### PR DESCRIPTION
**Pull request by jarroyomorales**
Same as https://github.com/OCA/stock-logistics-warehouse/pull/754 for v12
@etobella @mreficent @hveficent @rousseldenis

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by etobella — APPROVED** [review]
LGTM :+1:

**Review by HviorForgeFlow — APPROVED** [review]

**Comment by HviorForgeFlow** [comment]
@OCA/logistics-maintainers merge this, Thanks!

**Review by LoisRForgeFlow — APPROVED** [review]
Thanks!

**Pull request merged**
