### PR TITLE
[14.0] [MIG] stock_orderpoint _move_link

### PR DESCRIPTION
**Pull request by DavidBForgeFlow**
Standard migration to v14.
One of the inherited views has been moved from "stock_warehouse_views.xml" to "stock_orderpoint_views.xml", but this causes no problem to the module proper functionality.

@LoisRForgeFlow

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]
Code review

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM

**Pull request merged**
