### PR TITLE
[FIX] stock_request: Allow users to delete stock requests

### PR DESCRIPTION
**Pull request by etobella**
Without this, users cannot delete lines of stock request orders. The unlink cannot be used unless the state is `draft`

@jbeficent

### CODE REVIEW

**Comment by bodedra** [comment]
@etobella Not blocking comment. Shouldn't we improve module description at https://github.com/OCA/stock-logistics-warehouse/tree/11.0/stock_request#group-stock-request-user ?

**Comment by etobella** [comment]
@bodedra sure! I added all the information of stock request orders on readmes.

**Comment by max3903** [comment]
@etobella @bodedra There is no need to make changes in the `README.rst` and `index.html`. Those are generated from the `readme/` folder.

**Review by max3903 — APPROVED** [review]

**Review by bodedra — APPROVED** [review]

**Review by JordiBForgeFlow — APPROVED** [review]
:+1: Tested on runbot.

**Pull request merged**
