### PR TITLE
[14.0] Migration of stock_secondary_unit

### PR DESCRIPTION
**Pull request by alan196**
### Proposed changes

Migration PR for module project_timeline_hr_timesheet.

### Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Migration Update

### Checklist

- [x] I have read the CONTRIBUTING doc
- [x] I have signed the CLA
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have updated the necessary documentation

### CODE REVIEW

**Comment by alan196** [comment]
The fail in test is related with stock_vertical_lift_storage_type module

**Comment by rousseldenis** [comment]
@alan196 Could you rebase ?

**Comment by alan196** [comment]
@rousseldenis rebased 👍

**Review by francesco-ooops — APPROVED** [review]
LGTM (functional review)

**Comment by francesco-ooops** [comment]
@rousseldenis can this be merged?

**Review by rousseldenis — APPROVED** [review]
Code review

**Pull request merged**
