### PR TITLE
[9.0][PORT] stock_available and stock_available_immediately

### PR DESCRIPTION
**Pull request by SodexisTeam**

### CODE REVIEW

**Comment by stephankeller** [comment]
@pedrobaeza what is the next step for this?  I don't seem to be able to apply a label.  Thanks.

**Comment by pedrobaeza** [comment]
No, I'm afraid GitHub doesn't allow it for non repository owners. I have applied it for you. Now you need some reviewers for the PR to get merged. You can ask for it on the contributors list or on the IRC channel, but for now there's not too much interest on v9, so maybe it can be quite difficult.

**Comment by stephankeller** [comment]
ok, understood.  How about if we want to review a PR that needs review?  Should we just put a comment in the PR that we reviewed and it is fine and/or give comments?  What will be the criteria for the PR to be accepted?  Thanks.

**Comment by pedrobaeza** [comment]
If there are no issues, you can put `:+1:` as comment. Please see more in depth in: https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#review

**Comment by pedrobaeza** [comment]
And also if you reviews other PRs, you can ask to the authors of these PRs to review yours as payback.

**Comment by gurneyalex** [comment]
:+1:

**Comment by gurneyalex** [comment]
I'll take @stephankeller comment as an implicit :+1: and merge

**Comment by stephankeller** [comment]
Yes, :+1: thanks.

**Pull request merged**
