### PR TITLE
[14.0][MIG] stock_request_submit (Version 13.0 to 14.0)

### PR DESCRIPTION
**Pull request by patrickrwilson**

### CODE REVIEW

**Comment by patrickrwilson** [comment]
If anyone can point me in the direction on how to create a unit test to test uninstall hooks, that would be helpful. Example modules that have it would help too if possible. Thanks

**Comment by bodedra** [comment]
@patrickrwilson https://github.com/OCA/sale-workflow/blob/07dbb6bbf1fa67cf35c25e5f8e11a72d162b5096/sale_isolated_quotation/tests/test_sale_isolated_quotation.py#L29 

https://github.com/OCA/sale-workflow/blob/07dbb6bbf1fa67cf35c25e5f8e11a72d162b5096/sale_isolated_quotation/tests/test_sale_isolated_quotation.py#L44

**Comment by patrickrwilson** [comment]
Thanks @bodedra I'll check it out.

**Review by rousseldenis — APPROVED** [review]
Code review

**Pull request merged**
