### PR TITLE
[DEL] stock_inventory_with_location, stock_inventory_extended, stock_inventory_existing_lines

### PR DESCRIPTION
**Pull request by clonedagain**
Unless I'm mistaken, these modules are not needed any more in v8 thanks to improvements in the standard WMS

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by rvalyi** [comment]
:+1:  LGTM

**Comment by clonedagain** [comment]
Do I need to update the project's README file?

**Comment by pedrobaeza** [comment]
No, it's done automatically

**Pull request merged**
