### PR TITLE
[16.0][MIG][FIX] stock_cycle_count

### PR DESCRIPTION
**Pull request by ArnauCForgeFlow**
Fix invalid attribute discrepancy_qty

### CODE REVIEW

**Comment by AungKoKoLin1997** [comment]
@ArnauCForgeFlow Can you rebase? `stock_inventory` have already merged.
https://github.com/OCA/stock-logistics-warehouse/pull/1861

**Comment by AlexPForgeFlow** [comment]
@ArnauCForgeFlow can you change the test-requirements to get this dependency PR https://github.com/OCA/stock-logistics-warehouse/pull/1962

**Review by AlexPForgeFlow — APPROVED** [review]
LGTM!

**Comment by LoisRForgeFlow** [comment]
Closed in favor of https://github.com/OCA/stock-logistics-warehouse/pull/2045

**Pull request closed without merging**
