### PR TITLE
[15.0][MIG] stock_move_location

### PR DESCRIPTION
**Pull request by BernatPForgeFlow**

### CODE REVIEW

**Comment by BernatPForgeFlow** [comment]
@ForgeFlow

**Review by JoanMForgeFlow — APPROVED** [review]
LGTM!

**Review by GuillemCForgeFlow — APPROVED** [review]
LGTM!

**Review by JoanMForgeFlow — COMMENTED** [review]
you should add this changes: https://github.com/OCA/stock-logistics-warehouse/pull/1338
Thanks!

**Comment by BernatPForgeFlow** [comment]
> you should add this changes: #1338 Thanks!

Done!

**Comment by LoisRForgeFlow** [comment]
> > you should add this changes: #1338 Thanks!
> 
> Done!

Could you keep original authorship in those commits?

**Comment by BernatPForgeFlow** [comment]
> > > you should add this changes: #1338 Thanks!
> > 
> > 
> > Done!
> 
> Could you keep original authorship in those commits?

Done

**Review by LoisRForgeFlow — APPROVED** [review]

**Pull request merged**
