### PR TITLE
[15.0][FIX] stock_move_location: Take into account owner for move quants

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa TT43025

ping @carlosdauden @ernestotejeda 

Missing commit from v13
- https://github.com/OCA/stock-logistics-warehouse/pull/1095

### CODE REVIEW

**Review by carlosdauden — APPROVED** [review]

**Review by AungKoKoLin1997 — APPROVED** [review]
Functional and code review: LGTM

**Comment by rousseldenis** [comment]
@sergio-teruel Could you cherry-pick those commits instead ? Thanks

https://github.com/OCA/stock-logistics-warehouse/pull/1459/files

**Comment by sergio-teruel** [comment]
Yes!!! better!!

**Comment by sergio-teruel** [comment]
Hi @rousseldenis cherry pick from v14 done!! Thanks.!

**Review by rousseldenis — APPROVED** [review]

**Pull request merged**
