### PR TITLE
[IMP] stock_request: Set Procurement Group

### PR DESCRIPTION
**Pull request by osi-scampbell**
When an order is confirmed, create a procurement group and set it on the lines

### CODE REVIEW

**Review by max3903 — APPROVED** [review]

**Review by rousseldenis — APPROVED** [review]
Makes sense.

**Review by LoisRForgeFlow — CHANGES_REQUESTED** [review]
What if you don't want procurement group on purpose?

**Comment by rousseldenis** [comment]
@max3903 @osi-scampbell Could you answer @lreficent question ?

**Comment by max3903** [comment]
@lreficent We can add an option in the settings to auto-create the procurement group. Would that work for you?

CC: @osi-scampbell

**Comment by LoisRForgeFlow** [comment]
@max3903 What do you think about using this module: [procurement_auto_create_group](https://github.com/OCA/stock-logistics-warehouse/tree/12.0/procurement_auto_create_group)? If the route used by your stock request has the "Auto-create Procurement Group" field set to true, I think you will get your desired behavior.

**Comment by max3903** [comment]
@osi-scampbell Can you try using procurement_auto_create_group?

**Comment by max3903** [comment]
@osi-scampbell Any progress on this?

**Comment by max3903** [comment]
Ping @osi-scampbell

**Comment by max3903** [comment]
@osi-scampbell Let's add the issue #897 in the roadmap.rst file and get this pull request closed...

**Comment by etobella** [comment]
@max3903 I don't think this is an issue as both behaviors are good, the original one and the new one. Have you tested the option that @LoisRForgeFlow proposed you? Maybe that fills your needs without breaking the behavior of the original module.

**Comment by max3903** [comment]
@etobella No we didn't test it and we are not planning to in the near future. Maybe we will revisit this later.

**Comment by etobella** [comment]
then I think this issue does not need to go the roadmap of the module.

**Comment by max3903** [comment]
@osi-scampbell Let's fix the Travis error and get this merged.

**Review by etobella — CHANGES_REQUESTED** [review]
this is changing the behavior of the module when other options are possible...

**Comment by max3903** [comment]
@etobella Like I said we'll get back to this when appropriate.

**Review by murtuzasaleh — APPROVED** [review]

**Comment by etobella** [comment]
As said in previous comments, this is changing the current behavior of the module, this should go to a new module or reuse the options that @LoisRForgeFlow showed.

People is using this module with the current version and they are expecting that.

**Comment by LoisRForgeFlow** [comment]
@max3903 I don't think this PR should be merged unilaterally, moreover you are not the main author and you are more than aware that this module is widely used by at least ForgeFlow and Creu Blanca... My suggestion takes 10 minutes to be tested, I don't think skipping it by adding to the roadmap while breaking existing implementations is the way to go here.

**Review by LoisRForgeFlow — CHANGES_REQUESTED** [review]
Just refreshing my red cross here, I don't want this to be merged by any "mistake".

**Comment by rousseldenis** [comment]
@max3903 @LoisRForgeFlow So, we agree not merging this ?

**Pull request closed without merging**
