### PR TITLE
[16.0][MIG] stock_inventory

### PR DESCRIPTION
**Pull request by rousseldenis**

### CODE REVIEW

**Comment by pfranck** [comment]
@rousseldenis Any help for this MR ?

**Comment by rousseldenis** [comment]
> @rousseldenis Any help for this MR ?

@pfranck We are currently testing this one.

Any review is appreciated.

**Comment by JordiBForgeFlow** [comment]
@rousseldenis Can you consider https://github.com/ForgeFlow/stock-logistics-warehouse/commit/81ba4dbd623a2af18ca3b585d98b91418d264b93?

**Comment by JordiBForgeFlow** [comment]
@rafaelbn please do not yet merge as I asked @rousseldenis https://github.com/OCA/stock-logistics-warehouse/pull/1861#issuecomment-1761372142

**Comment by rousseldenis** [comment]
@JordiBForgeFlow In fact, the commits are here:

image

**Comment by rousseldenis** [comment]
@JordiBForgeFlow

**Comment by rousseldenis** [comment]
@JordiBForgeFlow Could you update your review ?

**Review by DorianMAG — APPROVED** [review]
Tested in Runboat
LGTM

**Comment by flotho** [comment]
Hi @JordiBForgeFlow , any chance to update your review ?

**Review by flotho — APPROVED** [review]
tested on runboat, it rpockks !
LGTM

**Review by JordiBForgeFlow — APPROVED** [review]

**Pull request merged**
