### PR TITLE
[17.0] [MIG] stock_inventory: Migration to 17.0

### PR DESCRIPTION
**Pull request by bizzappdev**

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
Hi @bizzappdev 

Could you include recent changes in v16?

- https://github.com/OCA/stock-logistics-warehouse/pull/2087
- https://github.com/OCA/stock-logistics-warehouse/pull/2017

Thanks!

**Comment by LoisRForgeFlow** [comment]
Hi again @bizzappdev 

One more:

- https://github.com/OCA/stock-logistics-warehouse/pull/2089

Looks like today became the stock_inventory's PRs cleaning day :smile:

**Comment by bizzappdev** [comment]
@LoisRForgeFlow, now we have those fixes also

**Review by LoisRForgeFlow — COMMENTED** [review]
Looking good, just a minor comment:

image

Could you move the menu to be under "Adjustments"? (it is a new submenu in v17)

**Comment by bizzappdev** [comment]
@LoisRForgeFlow Done changes to the menu changes.

**Review by LoisRForgeFlow — APPROVED** [review]
Thanks! LGTM :+1:

**Review by JoanSForgeFlow — APPROVED** [review]
Functional test, LGTM!

**Pull request merged**
