### PR TITLE
[10.0][IMP]stock_valuation_account_manual_adjustment

### PR DESCRIPTION
**Pull request by AaronHForgeFlow**
* multi company friendly

cc @ForgeFlow

### CODE REVIEW

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM!

**Comment by AaronHForgeFlow** [comment]
I am still pending to commit another improvement, please do not merge this yet.

**Comment by rousseldenis** [comment]
@AaronHForgeFlow Is this still applicable ?

**Comment by rousseldenis** [comment]
@AaronHForgeFlow

**Comment by rousseldenis** [comment]
@AaronHForgeFlow Could you rebase?

**Comment by AaronHForgeFlow** [comment]
Sorry, I missed your comments @rousseldenis . I use this PR, but I guess no one else uses this in a multicompany environment. I will keep in open anyway.

**Comment by rousseldenis** [comment]
@AaronHForgeFlow I've tested your changes and this one is not correct as:

- both queries return no result (in tests) with your changes:

https://github.com/OCA/stock-logistics-warehouse/pull/1029/files#diff-60aa742486f80d064707e306d0065051a3443e601b0d1d5c0617b99fa771a9fcR45

Previous state of this module works correctly (queries return result).

Do you plan to fix it or can we close ?

**Comment by AaronHForgeFlow** [comment]
@rousseldenis  we can close, no more work expected.

**Pull request closed without merging**
