### PR TITLE
[FIX] stock_inventory: warning on invalid tracking field

### PR DESCRIPTION
**Pull request by Tisho99**
FW PORT OF #2069

T-6102

### CODE REVIEW

**Comment by Tisho99** [comment]
@ValentinVinagre @HaraldPanten @pedrobaeza 

The module is not migrated to v17 so this is the last FW PORT

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Comment by ValentinVinagre** [comment]
@pedrobaeza

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge patch

**Pull request merged**
