### PR TITLE
[ADD] Add stock_location_inactive module

### PR DESCRIPTION
**Pull request by ehdem**
- [x] #68 
- Check if a location is empty (no product)
- and a location has no active sub-locations

### CODE REVIEW

**Comment by max3903** [comment]
@ehdem can you create a models and views subdirectories and split the source code by objects ?
It will be easier for @clonedagain to migrate it in #69

**Comment by ehdem** [comment]
@max3903 : ok

**Comment by max3903** [comment]
Tested on runbot
Travis fails due to other modules
:+1:

**Comment by max3903** [comment]
@clonedagain Module needs review and is ready for migration.

**Comment by qtheuret** [comment]
:+1:

**Comment by clonedagain** [comment]
@lbellier can we try to find a bit of time to port this to v8 ?

**Pull request merged**
