### PR TITLE
Backport stock_inventory_discrepancy from 9.0 to 8.0

### PR DESCRIPTION
**Pull request by daramousk**

### CODE REVIEW

**Comment by daramousk** [comment]
@NL66278 Not sure why this fails, the button is obviously there.
https://github.com/OCA/OCB/blob/8.0/addons/stock/stock_view.xml#L92

**Comment by NL66278** [comment]
@daramousk The button is renamed here:
https://github.com/OCA/stock-logistics-warehouse/blob/8.0/stock_inventory_exhaustive/views/stock_inventory_view.xml#L20

Note: this is a link to the latest part of the code. In our (pinned) version of stock-logistics-warehouse, the module stock_inventory_exhaustive is called stock_inventory_location.

Renaming buttons is a terribly bad idea. You will now understand why. But seems we have to live with the fact.

I think we should update the pin on stock-logistics-warehouse and test very well everything after that still works, but otherwise we will have a growing discrepancy with the oca code.

**Comment by LoisRForgeFlow** [comment]
@daramousk Don't forget to change the version number on the manifest file.

@NL66278 Indeed renaming buttons is a very bad idea, the module you pointed might need to be refactored to avoid it.

**Comment by LoisRForgeFlow** [comment]
Pleas check travis, tests are failing.

**Comment by daramousk** [comment]
@lreficent I fixed the issue with the tests but it seems to be crashing for different reasons now, not related to this module.

**Comment by daramousk** [comment]
@hbrunn Any ideas on travis?

**Comment by hbrunn** [comment]
lint checks are indeed not caused by this. You probably can speedup reviews however by fixing those two in a separate commit - people have a tendency to prefer spanding their time reviewing green PRs

The failure in the actual test running is some travis glitch, I restarted the build, we'll see what happens there.

**Comment by hbrunn** [comment]
this looks better now. You might want to fix https://travis-ci.org/OCA/stock-logistics-warehouse/jobs/397732531#L1299 however. The other test failure is unrelated.

**Comment by daramousk** [comment]
@hbrunn The failure of this test doesn't have to do anything with this module. I installed the module `stock_traceability_operation` and run the tests without `stock_inventory_discrepancy` installed. The first time the tests fail, while all the other times they succeed. This is a rather odd situation which requires drilling down to the quants code which I am very happy to do but still I do not think this module is involved into this.

**Comment by hbrunn** [comment]
that's what `The other test failure is unrelated.` was meant to say. The problem I linked to is the warning `WARNING openerp_test openerp.models: stock.change.product.qty.create() with unknown fields: product_tmpl_id`

**Comment by daramousk** [comment]
Ah my mistake, It is fixed now.

**Comment by rousseldenis** [comment]
@daramousk Please fix flake8 error
https://travis-ci.org/OCA/stock-logistics-warehouse/jobs/400970837#L575

**Comment by daramousk** [comment]
@rousseldenis Fixed the pylint issue. This next one does not seem to come from this module.

**Comment by rousseldenis** [comment]
@daramousk You can try to rebase? Fix was done by @pedrobaeza here : https://github.com/OCA/OCB/commit/087733682d0dee7297b2e645db95943cf2c4e941

**Comment by pedrobaeza** [comment]
Just restarting the build should be enough. I have done it. Thanks for the follow-up.

**Comment by rousseldenis** [comment]
@daramousk

**Comment by daramousk** [comment]
@rousseldenis I have rebased this PR but I am not sure why it still fails. 
I have been unable to:
1) reproduce the error locally
2) Find an offending rule in the testing instance (http://3340757-420-c5cb50.runbot2.odoo-community.org)
3) Trigger the error myself from the web client.

Any ideas are welcome.

**Comment by rousseldenis** [comment]
@daramousk This is due to security update in orm. You cannot use a wizard created by another user. Fix your test. See https://github.com/OCA/stock-logistics-warehouse/commit/02e9084a95d80630fb4cc5986fdcfba60b17a611

**Comment by daramousk** [comment]
@rousseldenis Thanks, this looks fine now.

**Comment by rousseldenis** [comment]
Ok, remove the WIP

**Review by rousseldenis — APPROVED** [review]
Code review

**Review by LoisRForgeFlow — APPROVED** [review]
Code review LGTM, let's move forward.

**Pull request merged**
