### PR TITLE
[14.0][FIX] stock_available_unreserved: dict.record.type is undefined

### PR DESCRIPTION
**Pull request by zamberjo**
Same error as: https://github.com/OCA/stock-logistics-warehouse/pull/1585

### CODE REVIEW

**Review by LoisRForgeFlow — CHANGES_REQUESTED** [review]
This doesn't seem to be working. Just tested it in runboat:

image

**Comment by LoisRForgeFlow** [comment]
BTW, in the original PR it is not described what is being fixed, could post here the steps to reproduce what you are fixing?

Thanks!

**Comment by zamberjo** [comment]
Hi @LoisRForgeFlow ! 

For reproduce, with [odoo](https://github.com/odoo/odoo/commit/322a89e16fe41e64b8d944327b15587105a323f9) updated (or [OCB)](https://github.com/OCA/OCB/commit/322a89e16fe41e64b8d944327b15587105a323f9) and stock_available_unreserved installed go to menu `Sales > Product > Products` (product.template) rendering the Kanban view gives an error as the `type` field is no longer available in the view.

**Comment by LoisRForgeFlow** [comment]
@zamberjo I see now, thanks for the pointer, indeed after that Odoo change there is an issue. However, your fix seems to have some problems too, could you try to fix it?

Thanks for contributing.

**Comment by zamberjo** [comment]
It seems that odoo is out of date on the runboat instance.
image

Works with oca/oca-ci image? The last build was 15 days ago (2022-12-07), while the odoo commit was last week (2022-12-16)

**Comment by pedrobaeza** [comment]
@sbidoul which is the frequency of update of the image?

**Comment by zamberjo** [comment]
Also I just noticed that there is a last module with the same error: [stock_free_quantity](https://github.com/OCA/stock-logistics-warehouse/blob/14.0/stock_free_quantity/views/product_template_view.xml#L44
)
@LoisRForgeFlow If you see it correct I will do another PR fixing it

**Comment by LoisRForgeFlow** [comment]
@zamberjo Yes, I think the fix is correct, you can already open the PR for the last one. In order to merge though, I would like to understand what's the procedure to deal with this cases in the OCA CI - let's wait @sbidoul input.

**Comment by sbidoul** [comment]
> which is the frequency of update of the image?

Nightly but they the builds have been failing due to the chrome installation. Not had time to investigate yet.

**Comment by zamberjo** [comment]
Hi @LoisRForgeFlow the image seems to have been updated:
[image
](https://github.com/OCA/oca-ci/pkgs/container/oca-ci%2Fpy3.6-odoo14.0)
so you can try it again

---

Edit:
I have recreated the instance. When testing it, it gave an error since both modules (`stock_free_quantity` and `stock_available_unreserved`) are installed. You would have to uninstall the `stock_free_quantity` module to test this PR.

**Review by LoisRForgeFlow — APPROVED** [review]
Thanks for following up. LGTM :+1:

**Comment by LoisRForgeFlow** [comment]
@zamberjo Is the fix needed in version 15? if so, could you forward port this?

**Pull request merged**
