### PR TITLE
[12.0][FIX] stock_request: Remove Inventory User bypass, not needed in v12

### PR DESCRIPTION
**Pull request by HviorForgeFlow**
fixup! #692 #704

### CODE REVIEW

**Comment by HviorForgeFlow** [comment]
@lreficent @ageficent @aheficent could you review?

**Review by AaronHForgeFlow — APPROVED** [review]
LGTM

**Comment by HviorForgeFlow** [comment]
@ageficent tested again, you were right, Record rule not needed anymore.

**Comment by HviorForgeFlow** [comment]
Reverting changes of #692 here

**Review by rousseldenis — APPROVED** [review]
Seems make sense

**Review by AdriaGForgeFlow — APPROVED** [review]
:+1:

**Pull request merged**
