### PR TITLE
[MIG][10.0] stock_putaway_product

### PR DESCRIPTION
**Pull request by rousseldenis**
Migration of stock_putaway_product

### CODE REVIEW

**Comment by rousseldenis** [comment]
Work done. Need review

**Review by Cedric-Pigeon — APPROVED** [review]
Code review

**Review by LoisRForgeFlow — APPROVED** [review]
Tested on runbot + light code review :+1:

**Comment by pedrobaeza** [comment]
Please squash together all "OCA Transbot" commits following this guide: https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests

**Comment by rousseldenis** [comment]
@pedrobaeza Ok, I'll do it ASAP

**Comment by lmignon** [comment]
@pedrobaeza squash done... ready to merge

**Review by lmignon — APPROVED** [review]

**Pull request merged**
