### PR TITLE
[17.0] [MIG] stock_quant_reservation_info: Migration to 17.0

### PR DESCRIPTION
**Pull request by MeritxellAForgeFlow**
Migration to 17.0
@ForgeFlow

### CODE REVIEW

**Review by DavidJForgeFlow — APPROVED** [review]
LGTM!

**Comment by rousseldenis** [comment]
@MeritxellAForgeFlow What's the aim of this duplicate ?

**Comment by DavidJForgeFlow** [comment]
Hi @rousseldenis, my mistake, @MeritxellAForgeFlow please close this PR

**Pull request closed without merging**
