### PR TITLE
[10.0] Add module stock_inventory_pos_category

### PR DESCRIPTION
**Pull request by alexis-via**
See README for more info.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This should be in OCA/pos, isn't it?

**Comment by alexis-via** [comment]
haha, I was expecting this one :) I'm sure that if I had proposed it in OCA/pos, someone would have said "Shouldn't it be in OCA/stock-xxx" :) I really don't care.

**Review by gurneyalex — APPROVED** [review]

**Comment by rousseldenis** [comment]
@alexis-via Shouldn't this be included in stock_inventory_preparation_filter ?

**Comment by gurneyalex** [comment]
@rousseldenis @alexis-via is the last question blocking from merging this PR?

**Comment by rousseldenis** [comment]
@alexis-via

**Comment by alexis-via** [comment]
@rousseldenis the module stock_inventory_preparation_filter only depends on "stock", it doesn't depend on "point_of_sale", so it can't use pos categories. So my answer would be "no"... but maybe I didn't understand your question...

**Comment by rousseldenis** [comment]
@alexis-via What I wanted to say is that you could extend stock_inventory_preparation_filter with stock_inventory_preparation_filter_pos as it covers the same functionnal perimeter.

Moreover, that makes repository more readable for people looking for some modules

**Comment by rousseldenis** [comment]
@alexis-via Could you rebase ?

**Comment by alexis-via** [comment]
@rousseldenis  I took into account your remark while porting the feature to v14: new module stock_inventory_preparation_filter_pos for v14 here: https://github.com/OCA/stock-logistics-warehouse/pull/1224

**Pull request closed without merging**
