### PR TITLE
[14.0][MIG] stock_available_mrp

### PR DESCRIPTION
**Pull request by florian-dacosta**
Standard Migration.
Mainly fix demo data and tests
Depends on : 
- [ ] https://github.com/OCA/stock-logistics-warehouse/pull/1037

### CODE REVIEW

**Comment by chienandalu** [comment]
We just added some changes https://github.com/OCA/stock-logistics-warehouse/pull/1099/files to provide compatibility due to Odoo's upstream changes. Please, take it into cosideration

**Comment by atchuthan** [comment]
Dependent PR: https://github.com/OCA/stock-logistics-warehouse/pull/1037 is already merged

**Review by atchuthan — APPROVED** [review]

**Comment by rousseldenis** [comment]
@florian-dacosta Could you check Travis ans pre-commit ?

**Review by chienandalu — COMMENTED** [review]
@florian-dacosta take a look at our migration to v13. Maybe you can rebase with those commits and it will pass CI: https://github.com/OCA/stock-logistics-warehouse/commit/6ad6a36495c3963ad5dcfa2f49aec1e110cb4cc1#diff-6c5af2923efaad294113ed678f2711e8da130147cbf99aac710a16160d2f860a

**Comment by florian-dacosta** [comment]
This PR actually comes from v12 and differ from the v13 module because it was done before the v13 PR.
I've redone a migration from the v13 module  in this PR https://github.com/OCA/stock-logistics-warehouse/pull/1162

I close this one, please review the other one @chienandalu @atchuthan @rousseldenis

**Pull request closed without merging**
