### PR TITLE
[14.0][MIG] migration of module stock_request_purchase

### PR DESCRIPTION
**Pull request by alan196**
### Proposed changes

I've migrated the module stock_request_purchase and its functionalities from Odoo 13.0 to 14.0. I've checked if all unit tests are still running.

### Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Migration Update

### Checklist

- [x] I have read the CONTRIBUTING doc
- [x] I have signed the CLA
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have updated the necessary documentation

### Further comments

This module depends on PR https://github.com/OCA/stock-logistics-warehouse/pull/985 https://github.com/OCA/stock-logistics-warehouse/pull/1345

### CODE REVIEW

**Comment by Freni-OSI** [comment]
Hi @alan196, can you complete it ASAP?

**Comment by alan196** [comment]
@Freni-OSI I just rebase it and make the changes needed to make this module works. It passes the Test 👍

**Comment by alan196** [comment]
The tests for this module failed because it has installed MRP module, I have tested in my local without MRP, and the test passes.  Do I need to add the group to the user in order to allow to pass the test?

**Review by olveracuenca — APPROVED** [review]
LGTM

**Review by dreispt — APPROVED** [review]

**Review by olgamarcocb — APPROVED** [review]
LGTM 👍

**Comment by alan196** [comment]
I make a PR to fix this issue for stock_request module. https://github.com/OCA/stock-logistics-warehouse/pull/1345

After this PR is merged the issues of this PR will be fixed

**Comment by LoisRForgeFlow** [comment]
Fix merged.

/ocabot merge nobump

**Pull request merged**
