### PR TITLE
[12.0][MIG] stock_request_kanban

### PR DESCRIPTION
**Pull request by kittiu**
Done migrated

### CODE REVIEW

**Review by etobella — APPROVED** [review]
squash translation commits please :smile:

**Comment by kittiu** [comment]
> squash translation commits please

Yes, I see lots of pot commit here. Question is, do squash only what is before the meaningful one, i..e, 801bea44 or find all in the history and quash all .pot (now sure you understand my question, sorry)
```
1329fcd6 (HEAD -> 12.0-mig-stock_request_kanban, origin/12.0-mig-stock_request_kanban) [12.0][MIG] stock_request_kanban
3487d283 Update translation files
2b4ed27a [UPD] Update stock_request_kanban.pot
d9b5f56a Update translation files
17419cb9 [UPD] Update stock_request_kanban.pot
8587373b [UPD] README.rst
801bea44 fixup! [IMP] Stock_request_kanban: Set barcode configuration on parameters
49bdf007 [IMP] Stock_request_kanban: Set barcode configuration on parameters
2fbf0231 Update translation files
f5e3f26f [UPD] Update stock_request_kanban.pot
9eb7b333 Update translation files
180eaca5 [UPD] Update stock_request_kanban.pot
744d3f84 Update translation files
1a3f97b3 [UPD] Update stock_request_kanban.pot
ce06051e Update translation files
```

**Review by rousseldenis — APPROVED** [review]
LGTM

**Comment by LoisRForgeFlow** [comment]
@kittiu I think you can squash all automatics commits that contain .pot files, as long as you keep the non-automatic ones (done by developers) it is fine and we keep history less noisy.

**Review by jarroyomorales — APPROVED** [review]

**Review by LoisRForgeFlow — APPROVED** [review]
Code review LG. I just did a rebase in order to go ahead with the merge.

**Comment by MiquelRForgeFlow** [comment]
Bitches! You did a merge with a red runbot! Solved in https://github.com/OCA/stock-logistics-warehouse/pull/659.

shame

**Pull request merged**
