### PR TITLE
[16.0][FIX] stock_move_location: correct method _get_putaway_strategy name

### PR DESCRIPTION
**Pull request by pilarvargas-tecnativa**
fw-port https://github.com/OCA/stock-logistics-warehouse/pull/1968

cc @Tecnativa TT48457

@pedrobaeza @sergio-teruel please review

### CODE REVIEW

**Review by sergio-teruel — APPROVED** [review]

**Comment by rousseldenis** [comment]
@pilarvargas-tecnativa Thanks for this. Could you check tests as there is one for putaways ?

**Review by pedrobaeza — APPROVED** [review]

**Comment by pilarvargas-tecnativa** [comment]
> @pilarvargas-tecnativa Thanks for this. Could you check tests as there is one for putaways ?

Hello! this doesn't really affect the tests.

**Comment by rousseldenis** [comment]
> > @pilarvargas-tecnativa Thanks for this. Could you check tests as there is one for putaways ?
> 
> Hello! this doesn't really affect the tests.

What about this ???? https://github.com/OCA/stock-logistics-warehouse/blob/16.0/stock_move_location/tests/test_move_location.py#L195

**Comment by pilarvargas-tecnativa** [comment]
> What about this ???? https://github.com/OCA/stock-logistics-warehouse/blob/16.0/stock_move_location/tests/test_move_location.py#L195

Sorry, I misunderstood you. The test did not detect the fault because the transfer was not being made.

This would be the mistake:
```
>>> wizard.action_move_location()
AttributeError: AttributeError("'stock.location' object has no attribute 'get_putaway_strategy'")
```

**Review by sergio-teruel — CHANGES_REQUESTED** [review]
Finish the test
https://github.com/OCA/stock-logistics-warehouse/pull/1968/files#diff-fb46b0534b57d40230d0c50c60d9960b066b0d92aba53727fb4359dcc17b6b47R182-R187

**Comment by pilarvargas-tecnativa** [comment]
> Finish the test https://github.com/OCA/stock-logistics-warehouse/pull/1968/files#diff-fb46b0534b57d40230d0c50c60d9960b066b0d92aba53727fb4359dcc17b6b47R182-R187

Done, thanks!

**Review by sergio-teruel — APPROVED** [review]

**Review by rousseldenis — APPROVED** [review]
Great! Thanks

**Pull request merged**
