### PR TITLE
[IMP] Warn WRT stock available to promise

### PR DESCRIPTION
**Pull request by clonedagain**
Hook into sale_stock to make it warn salespersons when the stock available
to promise is insufficient.
This is an extension of https://github.com/OCA/stock-logistics-warehouse/pull/5 .
## Code trick: context to override the virtual stock

The new module also has a context trick that lets it return the value of the stock available to promise in the field "virtual stock". This lets future sub-modules change the behavior of modules that were written to use the virtual stock, to use the new value instead with minimal impact.
## Merge blockers

This cannot be merged just yet because:
- [x] https://github.com/odoo/odoo/issues/2559 must be fixed
- [ ] I must add a test to check whether this actually works (must fail now, must succeed when previous bug is fixed in Odoo)

### CODE REVIEW

**Comment by clonedagain** [comment]
Please tag this PR "blocked" until odoo/odoo#2559 is fixed

**Comment by clonedagain** [comment]
The blocking bug seems fixed, we still need to prove it and then we can merge.

**Comment by clonedagain** [comment]
I've just read about https://github.com/OCA/sale-workflow/tree/7.0/sale_exceptions, maybe we should remix this patch to reuse this framework.
I'm undecided, opinions welcome.

**Comment by gurneyalex** [comment]
@clonedagain I agree that sale_exceptions is a good way to achieve what you want.

**Comment by clonedagain** [comment]
OK closing then, I'll look into it again this and sale_exceptions this summer as we migrate to v8.
Thanks for the advice.

**Comment by clonedagain** [comment]
For the records, it's indeed very easy to implement using sale_exceptions, and directions have been added in https://github.com/OCA/stock-logistics-warehouse/pull/81

**Pull request closed without merging**
