### PR TITLE
Added the translation template files and Finnish translations

### PR DESCRIPTION
**Pull request by mlaitinen**
Added the translation template files and Finnish translations to stock_reserve and stock_reserve_sale.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by yvaucher** [comment]
Technically :+1: 
Thanks

**Comment by yvaucher** [comment]
@mlaitinen Is it wanted to add those 2 last non translation commits ?

Maybe you could add them in another PR

**Comment by mlaitinen** [comment]
No, sorry. It's unintentional and happened because I'm a bit noobish with
GitHub pull requests. Should I cancel this pull request and create separate
pull requests using feature branching, or do you have a better idea?

**Comment by pedrobaeza** [comment]
Please rebase and solve the current issues

**Comment by mlaitinen** [comment]
Yes! Finally made it. My first rebase and I didn't even get hurt.

**Pull request merged**
