### PR TITLE
[16.0][MIG] stock_packaging_calculator_packaging_type + rename stock_packaging_calculator_packaging_level

### PR DESCRIPTION
**Pull request by gaelTorrecillas**

### CODE REVIEW

**Comment by marielejeune** [comment]
Hi, could you please follow the OCA migration guidelines to keep commits history?
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0#how-to

**Comment by marielejeune** [comment]
Hi @gaelTorrecillas ! 
Thanks for the modification. However to ease reviewing and history clean-up, you should have a commit "pre-commit stuff" with ONLY pre-commit stuff, then a second commit "[MIG] stock_packaging_calculator_packaging_type: Migration to 16.0" with the migration modifications and finally a third commit for module renaming.

**Comment by marielejeune** [comment]
Hi @gaelTorrecillas 
I'm sorry but I need this module to be migrated and the installation to run for my project, so I opened a second PR on the same subject.
Feel free to ping me if you plan to fix your PR, I'll close mine.
https://github.com/OCA/stock-logistics-warehouse/pull/1860

**Comment by rousseldenis** [comment]
@gaelTorrecillas Do you mind if we switch to #1860 ?

**Comment by gaelTorrecillas** [comment]
@rousseldenis hello, no problem.

**Pull request closed without merging**
