### PR TITLE
MIG 12.0 stock available unreserved

### PR DESCRIPTION
**Pull request by ougc27**
Hello @pedrobaeza  this module is a dependence of the mrp_production_request, I tested it and works fine.

Could you review it or contact me with someone to review it please?

Best Regards!

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Sorry, I'm not a user of this module. Other reviewers should check it.

**Review by bealdav — APPROVED** [review]
I've just reviewed the code and tested the module.

It works nicely, thanks

**Review by alexis-via — APPROVED** [review]
Code review, no test

**Comment by LoisRForgeFlow** [comment]
Can you consider the changes proposed here: https://github.com/OCA/stock-logistics-warehouse/pull/511?

**Comment by ray-odoo** [comment]
Tested today on v12EE.  

Works well.  The UoM isn't shown on the Smart Button on the form view, but everything else looks good.

**Comment by bealdav** [comment]
@lreficent as there is no activity on #511 since 2.5 months (everybody are busy), maybe we can merge this module as it (3 approve here).
Then as #511 is an improvement and the upgrade path is good (computed field), it can be applied after merged in v11. I could help to accomplish this task. Thanks
cc @jbeficent

**Review by rousseldenis — APPROVED** [review]

**Comment by rousseldenis** [comment]
Relaunched Travis to complete jobs

**Comment by rousseldenis** [comment]
@ougc27 Could you squash last two commits ?

**Comment by bealdav** [comment]
no answer of @ougc27 

@rousseldenis may be you could squash with github merge builtin feature ?

Thanks

**Comment by rousseldenis** [comment]
@bealdav Nope, it will merge the 15 commits. Wait a little, if no answer, will merge and squash myself on 12.0 branch

**Comment by bealdav** [comment]
Ok thanks

**Comment by tbaden** [comment]
pr https://github.com/OCA/stock-logistics-warehouse/pull/562 depends on this.
@rousseldenis maybe you can do the squashing

**Comment by tbaden** [comment]
❤️ @rousseldenis

**Pull request merged**
