### PR TITLE
[IMP] reason code location set as a scrap location if set

### PR DESCRIPTION
**Pull request by bodedra**
Issue Ref: https://github.com/OCA/stock-logistics-warehouse/issues/914

### CODE REVIEW

**Review by CasVissers-360ERP — APPROVED** [review]
LGTM, tnnx!

**Review by rousseldenis — APPROVED** [review]
LGTM

**Comment by bodedra** [comment]
@OCA/logistics-maintainers Are we good to merge this?

**Comment by bodedra** [comment]
minor?

**Comment by bodedra** [comment]
@Cedric-Pigeon 
> /ocabot merge patch

Would you please try with /ocabot merge minor

**Review by BT-cserra — APPROVED** [review]
Tested in the wild. Works like a charm.

**Pull request merged**
