### PR TITLE
[14.0][MIG] stock available base exclude location xbo

### PR DESCRIPTION
**Pull request by xavier-bouquiaux**

### CODE REVIEW

**Comment by sbejaoui** [comment]
Travis is red

**Comment by rousseldenis** [comment]
@xavier-bouquiaux You need to add 'odoo_test_helper' in test-requirements.txt

**Comment by rousseldenis** [comment]
@xavier-bouquiaux

**Comment by xavier-bouquiaux** [comment]
rebased and add 'odoo_test_helper' in test-requirements.txt

**Review by rousseldenis — APPROVED** [review]
Code review

**Pull request merged**
