### PR TITLE
show reservation location in tree and groupby

### PR DESCRIPTION
**Pull request by lepistone**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by jgrandguillaume** [comment]
:+1:

**Comment by gurneyalex** [comment]
@lepistone can you check why the red build with OCB?

**Comment by lepistone** [comment]
I restarted the build.

**Comment by laetitia-gangloff** [comment]
:+1:

**Comment by pedrobaeza** [comment]
Tests are incorrect, but not due to this change, so I merge. We will deal with the error in another PR.

**Pull request merged**
