### PR TITLE
[15.0] [MIG] stock_quant_reservation_info_mrp: Migration to 15.0

### PR DESCRIPTION
**Pull request by bizzappdev**
Dependency MR for module stock_quant_reservation_info https://github.com/OCA/stock-logistics-warehouse/pull/2028

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]
Code review.

Even if a little test even for actions should be great

**Comment by LoisRForgeFlow** [comment]
@bizzappdev The dependency has been merged, could you rebase this PR?

**Comment by bizzappdev** [comment]
@LoisRForgeFlow removed test requirements.

**Review by LoisRForgeFlow — APPROVED** [review]
Great, Thank you!

**Pull request merged**
