### PR TITLE
WIP: [10.0] backport stock_request module

### PR DESCRIPTION
**Pull request by ovnicraft**
First main points TODO:
* [x] rewrite in order to user procurement rules according v10.0 design.
* [x] review if remove `stock.move.line` has no side effects
* [x] check computed fields, needs refactor in `models/procurement_rule.py`
* [x] check qty_done, in v11 use stock.move.line; needs refactor
* [ ] search best match for procurement rule for run procurement
* [ ] refactor tests

### CODE REVIEW

**Comment by ovnicraft** [comment]
@jbeficent hi ! your help here would be appreciated !

**Comment by rousseldenis** [comment]
@ovnicraft I think you should keep v11 commit history (2)

**Comment by ovnicraft** [comment]
@rousseldenis yes, my fault i will check to pick up commits to this.

**Comment by ovnicraft** [comment]
@rousseldenis backport commits its done, now i start with changes

**Comment by ovnicraft** [comment]
@rousseldenis now i made it installable and i am looking for help to understand run() method, over 10.0

**Comment by rousseldenis** [comment]
The great change that happened in v11 is that procurement orders have disappeared. I think the good lead is instead of calling run method on procurement group, is to look into product stock request in product form in v10. The idea should be creating procurement orders on each request line.

**Comment by rousseldenis** [comment]
@ovnicraft Any news on this ?

**Comment by CasVissers-360ERP** [comment]
Just tried to test the module got a traceback after confirming the request:
```
Traceback (most recent call last):
  File "/opt/odoo/customer/odoo/odoo/http.py", line 642, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/customer/odoo/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/customer/odoo/odoo/http.py", line 334, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/customer/odoo/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/customer/odoo/odoo/http.py", line 327, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/customer/odoo/odoo/http.py", line 942, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/customer/odoo/odoo/http.py", line 507, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/customer/odoo/addons/web/controllers/main.py", line 896, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/customer/odoo/addons/web/controllers/main.py", line 884, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/customer/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/customer/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/customer/community/stock_request/models/stock_request.py", line 208, in action_confirm
    self._action_confirm()
  File "/opt/odoo/customer/community/stock_request/models/stock_request.py", line 203, in _action_confirm
    self._action_launch_procurement_rule()
  File "/opt/odoo/customer/community/stock_request/models/stock_request.py", line 293, in _action_launch_procurement_rule
    procurement = self.env["procurement.order"].create(values)
  File "/opt/odoo/customer/odoo/addons/procurement/models/procurement.py", line 136, in create
    procurement = super(ProcurementOrder, self).create(vals)
  File "/opt/odoo/customer/odoo/addons/mail/models/mail_thread.py", line 228, in create
    thread = super(MailThread, self).create(values)
  File "/opt/odoo/customer/odoo/odoo/models.py", line 3847, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo/customer/odoo/odoo/models.py", line 3996, in _create
    field.write(self.with_context(rel_context), vals[name])
  File "/opt/odoo/customer/odoo/odoo/fields.py", line 2448, in write
    link([act[1]])
  File "/opt/odoo/customer/odoo/odoo/fields.py", line 2418, in link
    cr.execute(query, (records.ids, list(sub_ids), tuple(records.ids)))
  File "/opt/odoo/customer/odoo/odoo/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo/customer/odoo/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
ProgrammingError: EXCEPT types boolean and integer cannot be matched
LINE 3: ...                   EXCEPT (SELECT procurement_id, route_id F...
```

**Comment by ovnicraft** [comment]
@CasVissers @rousseldenis Hi, sorry for delay i recently identify the error:

In 11.0 procurement.group implement  `run()` [method at addons/stock/models/procurement.py#L177](https://github.com/odoo/odoo/blob/64a219bd0694c6e7f79692f8d1dfd2201f6125e1/addons/stock/models/procurement.py#L177) so method call this and pass arguments, `run()` internally look for the best match rule with `_search_rule` [method at addons/stock/models/procurement.py#L190](https://github.com/odoo/odoo/blob/64a219bd0694c6e7f79692f8d1dfd2201f6125e1/addons/stock/models/procurement.py#L190)

For this case in v10 we have no procurement.group with this method and when create procurement.order raise the error.

Possible solution is before to create procurement.order look for procurement.rule and pass to create procurement.order, it include _search_rule, _get_rule method to be backported too.

Help is welcome to do the best here.

**Comment by ovnicraft** [comment]
I am closing by now this, i have no time to continue in this month.

**Pull request closed without merging**
