### PR TITLE
[FIX] stock_mts_mto_rule: add mts_rule_id and mto_rule_id on stock ru…

### PR DESCRIPTION
**Pull request by kos94ok-3D**
…le form view

### CODE REVIEW

**Comment by kos94ok-3D** [comment]
Hi @jaredkipe.
Can you review it?

**Review by rousseldenis — APPROVED** [review]
Code and functional review

**Comment by ougc27** [comment]
Hello @rousseldenis, could you help us to notify another reviewer to merge it asap please? :pray:

**Review by jaredkipe — APPROVED** [review]

**Review by bodedra — APPROVED** [review]

**Review by rousseldenis — APPROVED** [review]
Code review

**Pull request merged**
