### PR TITLE
[13.0][MIG] stock_warehouse_orderpoint_stock_info_unreserved

### PR DESCRIPTION
**Pull request by ps-tubtim**
This PR is waiting for https://github.com/OCA/stock-logistics-warehouse/pull/800, you can always use this for readability.
- [x] [13.0][MIG] stock_warehouse_orderpoint_stock_info

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]
Code review

**Comment by rousseldenis** [comment]
@ps-tubtim Could you rebase ?

**Comment by ps-tubtim** [comment]
@rousseldenis I read from https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0
and it's suggest that.

**Comment by rousseldenis** [comment]
> @rousseldenis I read from https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0
> and it's suggest that.

Don't understand what you mean

**Comment by ps-tubtim** [comment]
> Don't understand what you mean

@rousseldenis I mean I do follow topic **How to: Technical method to migrate a module from "12.0" to "13.0" branch** in this wiki then create 2 commits (_[IMP] $MODULE: black, isort_ and _[MIG] $MODULE: Migration to 13.0_)

**Comment by rousseldenis** [comment]
> > Don't understand what you mean
> 
> @rousseldenis I mean I do follow topic **How to: Technical method to migrate a module from "12.0" to "13.0" branch** in this wiki then create 2 commits (_[IMP] $MODULE: black, isort_ and _[MIG] $MODULE: Migration to 13.0_)

Ok. As the depending module '...info' is now merged in 13.0, you have to rebase your branch on 13.0 and force push to make runbot happy (see error description in runbot logs)

**Comment by ps-tubtim** [comment]
@rousseldenis Sorry, I misunderstand. Thanks.

**Review by rousseldenis — APPROVED** [review]
Code review

**Review by JoanSForgeFlow — APPROVED** [review]
Functional review, LGTM  :+1:

**Pull request merged**
