### PR TITLE
[12.0][IMP] Add domain filter on inventory adjustment

### PR DESCRIPTION
**Pull request by ivantodorovich**
Added a new filter type: domain
This enables more complex searches, like searching based on a related field's field.

image

Superseeds https://github.com/OCA/stock-logistics-warehouse/pull/745

### CODE REVIEW

**Review by pedrobaeza — COMMENTED** [review]
Tried on runbot and working. Please add in the README a comment about the new option.

**Comment by rousseldenis** [comment]
Am I missing something ?

image

**Comment by pedrobaeza** [comment]
@rousseldenis there shouldn't be any stock for that product

**Review by rousseldenis — APPROVED** [review]
Code and functional review

**Comment by pedrobaeza** [comment]
Adding the comment in the README I can proceed to merge if you want.

**Comment by ivantodorovich** [comment]
I added the comment a few mins ago, it should be there ^^

**Review by pedrobaeza — APPROVED** [review]
Sorry, I didn't see them. Going then!

**Pull request merged**
