### PR TITLE
[11.0][FIX] Number Sequence and some uppercases

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
This PR fixes:

- [x]  Error with the sequence number.
- [x]  Visible texts that should be in uppercases.
- [x]  `order_id` should only be visible if `group_stock_request_order` option is enabled.
- [x]  adds more tests
- [x]  adds consistency between models company-wise

@jbeficent @etobella @lreficent

### CODE REVIEW

**Comment by JordiBForgeFlow** [comment]
@mreficent @etobella I have added significant changes in my last commit. Fixes the problem with the sequence,  adds consistency between models company-wise and adds more tests.

**Comment by JordiBForgeFlow** [comment]
BTW the problem with the sequence was caused because you are not supposed to change directly the vals in the create method, as vals is passed by reference and changes will afect subsequent uses of vals outside of the scope of the create method. Instead use copy() to copy vals to a new variable, and then change the new variable.

**Comment by JordiBForgeFlow** [comment]
@lreficent @mreficent @etobella This one is ready to review & merge.

**Review by etobella — APPROVED** [review]
LGTM :+1:

**Review by MiquelRForgeFlow — COMMENTED** [review]
LGTM :+1:

**Pull request merged**
