### PR TITLE
[12.0][IMP] stock_secondary_unit: Use secondary units directly in pickings

### LINKED ISSUE #1188: [12.0] stock_secondary_unit "secondary qty" value in picking not affecting "initial demand"
AFFECTED VERSIONS

12.0 (it works ok on 13.0)

STEPS TO REPRODUCE

Activate Units of Measure in general settings > inventory

Inventory > Master Data > Products > Set a secondary unit in a product

image

Create a new transfer > add product > select secondary UoM > input secondary qty

image

CURRENT BEHAVIOR

Value "Initial demand" is not affected by secondary qty input
In the same way, if "Initial demand" is set, "secondary qty" does not change - basically there is no relation between the two fields

image

REQUIRED BEHAVIOR 

When "secondary qty" is updated, also "initial demand" should update - and viceversa, as it happens in SO with secondary unit modules

VIDEO

https://recordit.co/zcuDUx6xco

### PR DESCRIPTION
**Pull request by GSLabIt**
Fix  #1188

### CODE REVIEW

**Comment by GSLabIt** [comment]
Fix #1188

**Comment by GSLabIt** [comment]
@sergio-teruel, @enriquemartin any chance to review?

**Comment by sergio-teruel** [comment]
@GSLabIt Do you know that in v13 exists a product_secondary_unit_mixin??
I only comment this because this PR must be not forward to v13..

**Review by sergio-teruel — APPROVED** [review]

**Comment by GSLabIt** [comment]
> @GSLabIt Do you know that in v13 exists a product_secondary_unit_mixin??
> I only comment this because this PR must be not forward to v13..
> 

Sorry i dont understand the comment, in v 13 already exists the functionality. Why should this PR fw to 13?
Other than that, should product_secondary_unit_mixin be backported to 12?

**Comment by sergio-teruel** [comment]
> Other than that, should product_secondary_unit_mixin be backported to 12?

@GSLabIt I was going to tell you... but I think that it is not needed...

**Review by francesco-ooops — APPROVED** [review]
@GSLabIt works good

**Comment by GSLabIt** [comment]
@oca-mainteiners, @rousseldenis any change to get this merged?

**Comment by elvise** [comment]
@sergio-teruel , @enriquemartin  any chance to review?

**Comment by enriquemartin** [comment]
If the picking is blocked, you can't modify the initial demand (`product_uom_qty`) but you can edit the secondary unit and qty; because of that, the onchange is trigered and initial demand is "changed" until you save (normal behaviour without `force_save`).
I think that the `secondary_uom_qty` and `secondary_uom_id` fields must have the same behaviour about readonly state as `product_uom_qty` and `product_uom_id` respectively.
Otherwise works good.

**Comment by GSLabIt** [comment]
> If the picking is blocked, you can't modify the initial demand (`product_uom_qty`) but you can edit the secondary unit and qty; because of that, the onchange is trigered and initial demand is "changed" until you save (normal behaviour without `force_save`).
> I think that the `secondary_uom_qty` and `secondary_uom_id` fields must have the same behaviour about readonly state as `product_uom_qty` and `product_uom_id` respectively.
> Otherwise works good.

@enriquemartin done, could you please double check and confirm?

**Comment by elvise** [comment]
@sergio-teruel , @enriquemartin  it would be great if it were possible to merge it :)

**Comment by sergio-teruel** [comment]
ping @rousseldenis

**Comment by GSLabIt** [comment]
@rousseldenis any chance to merge this one?

**Pull request merged**
