### PR TITLE
 Migrate stock_inventory_location to v8

### PR DESCRIPTION
**Pull request by clonedagain**
This is the last step to fixing https://github.com/OCA/stock-logistics-warehouse/issues/134
# Module renamed

Rename stock_inventory_location to stock_inventory_exhaustive, and stock_inventory_hierarchical_location to stock_inventory_hierarchical_exhaustive (Odoo now has a location for inventories already)
# Functional change

Removed the feature to lock down locations during inventories: it's now split into an new dedicated module `stock_inventory_lockdown` - see https://github.com/OCA/stock-logistics-warehouse/pull/149
Dropped the extra state 'open' in inventories: Odoo now has a decent logic where the state 'confirm' represents running inventories.
# Migration to v8

Adjust the notes displayed at the bottom of the inventory form, to reflect the change implied by exhaustive inventories
Take packages and owners into account during exhaustive inventory validation
Take into account transit locations
Drop the control forbiding inventories in the future (Odoo already ensures this)
Drop the definition of stock.inventory.location_id and the corresponding client-side handling (Odoo provides it)
Drop the custom exception ExhaustiveInventoryException (Odoo provides ValidationError)
Drop the fill-inventory wizard (dropped from the Odoo)
Drop the complex modularity workaround to copy data from parent inventories to their sub-inventories (v8 API provides a cleaner syntax)
Bump version to 8.0.1.0.0
Updated screenshots
Update translation into French
# Refactoring and coding standards

Translate to API v8
Add a test for test_confirm_missing_locations.
Move the creation of missing inventory lines to stock.inventory.action_done()
Adopt the newest OCA standards for licences, README
Rewrite tests in python.
Add a context key `force_exhaustive` to force default value

### CODE REVIEW

**Comment by clonedagain** [comment]
@laetitia-gangloff this is the last part of the inventory modules @lbellier and I ported to v8. Your review would be appreciated.

**Comment by clonedagain** [comment]
@lmignon your opinion on this is welcome too, it's the v8 for other part of one of the modules you use in v7.

**Comment by clonedagain** [comment]
Rebased on the latest upstream 8.0.
Now that the prerequisites are merged, the commit history here is clean.
Reviewers wanted!

**Comment by andhit-r** [comment]
LGTM :+1:

**Comment by lbellier** [comment]
LGTM :+1:

**Review by gurneyalex — APPROVED** [review]

**Pull request merged**
