### PR TITLE
[MIG] stock_available_immediately: Migration to 11.0

### PR DESCRIPTION
**Pull request by dmsergio**

### CODE REVIEW

**Comment by dmsergio** [comment]
Hello @pedrobaeza, have I preserved correctly the history commit?

**Comment by pedrobaeza** [comment]
Yes, thanks. Check now why Travis is red.

**Comment by pedrobaeza** [comment]
I think it's not your fault, but `stock_request` one. @lreficent are you aware of this error?

**Comment by dmsergio** [comment]
> Yes, thanks. Check now why Travis is red.

The tests of `stock_available_immediately` addon has passed correctly. Travis found errors in another addons.

**Comment by dmsergio** [comment]
Any news about this PR?

**Comment by pedrobaeza** [comment]
You have to find reviewers of the PR. You can review others and ask in exchange that they review yours.

**Comment by jesuspablo** [comment]
@dmsergio, I think the changes made are correct, we have missed the migration of this module

**Comment by maurochip** [comment]
I tested It and it works properly on my Odoo dev

**Comment by pedrobaeza** [comment]
Please use GitHub's approval mechanism for proper visibility.

**Review by maurochip — APPROVED** [review]
I tested It and it works properly on my Odoo dev

**Review by jesuspablo — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Although none of the reviewers is PSC of this repo, I think we can trust being a migration and of something very confined, so

/ocabot merge

**Pull request merged**
