### PR TITLE
[16.0][MIG] stock_putaway_product_template: Migration to version 16.0

### PR DESCRIPTION
**Pull request by carolinafernandez-tecnativa**
Standard migration to v16.

@Tecnativa

TT44369

@pedrobaeza

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
Please squash administrative commits

**Comment by carolinafernandez-tecnativa** [comment]
> Please squash administrative commits

@pedrobaeza done!

**Review by carlosdauden — APPROVED** [review]

**Pull request merged**
