### PR TITLE
[14.0][FIX] stock_request: set stock request order state to done when partially delivered

### PR DESCRIPTION
**Pull request by OriolMForgeFlow**

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]
Code review

**Comment by rousseldenis** [comment]
@OriolMForgeFlow I will fix queue job problem

**Review by DavidJForgeFlow — APPROVED** [review]
LGTM!

**Review by JoanSForgeFlow — APPROVED** [review]
LGTM!

**Review by LoisRForgeFlow — APPROVED** [review]
Makes sense

**Comment by LoisRForgeFlow** [comment]
@OriolMForgeFlow does this fix need to be fwported?

**Pull request merged**
