### PR TITLE
[12.0][MIG] stock_inventory_lockdown

### PR DESCRIPTION
**Pull request by osimallen**
#487 
Superseeds #627
Migration of stock_inventory_lockdown to version 12

### CODE REVIEW

**Comment by bodedra** [comment]
@mreficent @jbeficent @lreficent @lmignon Would you please review these ?

**Review by max3903 — APPROVED** [review]

**Comment by rousseldenis** [comment]
Hi @osimallen, thanks for your PR.

Do you plan to add test for the unlink() on stock.location to cover 100% ?

**Review by AdriaGForgeFlow — APPROVED** [review]
Tested on runbot and code review :+1:

**Review by MiquelRForgeFlow — APPROVED** [review]
LGTM

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM, tested on runbot

**Pull request closed without merging**
