### PR TITLE
[MIG] stock_free_quantity: Migration to 15.0

### PR DESCRIPTION
**Pull request by glitchov**

### CODE REVIEW

**Comment by leemannd** [comment]
Hello @glitchov , runboat seems stuck. Is it possible to rebase on 15.0 and push it again?

**Comment by rousseldenis** [comment]
> Hello @glitchov , runboat seems stuck. Is it possible to rebase on 15.0 and push it again?

Hi @leemannd, all runboat instances are dead ...

**Comment by leemannd** [comment]
Hello @rousseldenis , I wasn't aware of it.

**Review by leemannd — APPROVED** [review]
I don't know much about the module, but the migration looks good

**Pull request merged**
