### PR TITLE
[14.0] [MIG] stock_move_location: Port PR 12.0 to 14.0

### PR DESCRIPTION
**Pull request by sonhd91**
PR Port:
* [[IMP][12.0] stock_move_location: add posibility empty location with stock.picking](https://github.com/OCA/stock-logistics-warehouse/pull/885)

### CODE REVIEW

**Review by LoisRForgeFlow — CHANGES_REQUESTED** [review]
~Could you keep original authorship on those commits?~ EDIT: It is actually correct, I got confused by github showing a different profile picture.

**Review by LoisRForgeFlow — APPROVED** [review]
Tested, works as expected :+1:

**Review by BernatPForgeFlow — APPROVED** [review]

**Review by BernatPForgeFlow — APPROVED** [review]
LGTM!

**Pull request merged**
