### PR TITLE
[13.0][IMP] stock_location_position: Add barcode field to location view in same group like as v12.0

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa TT24428
please @carlosdauden @pedrobaeza review....

### CODE REVIEW

**Comment by pedrobaeza** [comment]
But this module is not adding such `barcode` field. Why adding it here?

**Comment by sergio-teruel** [comment]
Bacode only is removed in the stock location view...., Yhea!! Mybe I can add directly in stock_barcodes module...

**Comment by pedrobaeza** [comment]
Yes, I think it could be a better place for that.

**Comment by sergio-teruel** [comment]
OK... so close this PR---- :sob:

**Pull request closed without merging**
