### PR TITLE
[15.0][ADD] stock_physical_count_lockdown

### PR DESCRIPTION
**Pull request by TheerayutEncoder**
This PR aim to add module stock_physical_count_lockdown.
After install this module, User can go to menu Inventory -> Operations  -> Update Stock Locations Lock, then select internal location to lock and click update button.
These selected location will not allow to move any product.

### CODE REVIEW

**Comment by ps-tubtim** [comment]
@TheerayutEncoder Please update your tests.

**Comment by TheerayutEncoder** [comment]
> @TheerayutEncoder Please update your tests.

Updated

**Comment by rousseldenis** [comment]
@TheerayutEncoder IMHO, this has duplicate functionality with https://github.com/OCA/stock-logistics-warehouse/tree/15.0/stock_location_lockdown

At this difference, you want to block quantity modification. But maybe both functionalities could be merged ?

@alexis-via @florian-dacosta

**Comment by TheerayutEncoder** [comment]
Hi @rousseldenis 
I got the idea from module stock_location_lockdown.
Thanks @alexis-via @florian-dacosta 

Please feel free to let me know.

**Pull request closed without merging**
