### PR TITLE
[10.0][IMP] add sum attribute to inventory & accounting value field

### PR DESCRIPTION
**Pull request by bodedra**
With this PR, we can see total of inventory value and accounting value.

### CODE REVIEW

**Comment by bodedra** [comment]
@AaronHForgeFlow @LoisRForgeFlow

**Review by AaronHForgeFlow — APPROVED** [review]

**Comment by rousseldenis** [comment]
@bodedra Could you rebase ?

**Comment by bodedra** [comment]
@rousseldenis I am no longer with the organization. Probably that's why we face repo permission issues.

**Review by rousseldenis — APPROVED** [review]

**Pull request merged**
