### PR TITLE
[12.0][REW] stock_warehouse_calendar: add plan days helper method

### PR DESCRIPTION
**Pull request by LoisRForgeFlow**
the method `wh_plan_days` can be used in any place where planning
or scheduling needs to be done in a given warehouse context,
considering the working days if set.

@Eficent

### CODE REVIEW

**Review by JordiBForgeFlow — APPROVED** [review]

**Review by HviorForgeFlow — APPROVED** [review]
Interesting change! Code review. LGTM :+1:

**Comment by lreficent** [comment]
Thanks for reviews!

ocabot merge patch

**Comment by LoisRForgeFlow** [comment]
Thanks for reviews!

/ocabot merge patch

**Pull request closed without merging**
