### PR TITLE
13.0 mig stock location lockdown

### PR DESCRIPTION
**Pull request by manuelregidor**
Standard migration.

### CODE REVIEW

**Comment by HaraldPanten** [comment]
@manuelregidor could you recheck pre-commit?

**Review by HaraldPanten — APPROVED** [review]
Functional review 👍

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍

**Comment by HaraldPanten** [comment]
@OCA/logistics-maintainers could this one be merged?

**Comment by rousseldenis** [comment]
> @OCA/logistics-maintainers could this one be merged?

You're in a hurry ? 7 days old. A baby :smiley:

**Review by rousseldenis — APPROVED** [review]

**Comment by HaraldPanten** [comment]
Lately, I'm always in a hurry. Thanks @rousseldenis 👍

**Comment by rousseldenis** [comment]
@manuelregidor Could you rebase ?

**Comment by manuelregidor** [comment]
@rousseldenis Rebase done

**Comment by manuelregidor** [comment]
@rousseldenis Travis has failed due to an unrelated travis error. Apparently there is something wrong with a test in module 'stock_vertical_lift_storage_type module', which has no relation with the module I have migrated. How should we proceed? Thank you.

**Comment by pedrobaeza** [comment]
We are suffering the same in #998. Either you fix it and put a new PR or put an issue pinging the authors/maintainers of such module. It will be probably a change upstream that has impacted in the module.

**Comment by rousseldenis** [comment]
@pedrobaeza If I have time to test I will objectivate it but I think this is due to https://github.com/odoo/odoo/commit/51b7960f7e30aab471bb846cb890efd95c7b2dcc

@jgrandguillaume

**Comment by HaraldPanten** [comment]
Here seems to be the fix for the issue https://github.com/OCA/stock-logistics-warehouse/pull/1000

**Review by MiquelRForgeFlow — APPROVED** [review]

**Comment by HaraldPanten** [comment]
What's going on? 🤔

**Comment by rousseldenis** [comment]
pre-commit is stuck on install. Try to solve.

/ocabot merge patch

**Pull request merged**
