### PR TITLE
[10.0][mig][stock_demand_estimate]

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
Migration from https://github.com/OCA/stock-logistics-warehouse/pull/293

There's now an issue, where the quantities updated by the user in the widget `x2many_2d_matrix` are not being considered.

image

After pressing 'Validate':
image

### CODE REVIEW

**Comment by JordiBForgeFlow** [comment]
@lmignon @pedrobaeza Can you help me to resolve why the quantities updated by the user in the x2many_2d_matrix are not being considered?

**Review by LoisRForgeFlow — APPROVED** [review]
Tested locally, working perfectly for me :+1:

**Review by MiquelRForgeFlow — APPROVED** [review]

**Comment by JordiBForgeFlow** [comment]
Can you rebase?

**Comment by MiquelRForgeFlow** [comment]
@jbeficent Done!

**Comment by JordiBForgeFlow** [comment]
Rebase with OCA/10.0

**Comment by MiquelRForgeFlow** [comment]
That's what I did.

I think that the runbot problem is not our problem. The runbot is working if you try it.

**Pull request merged**
