### PR TITLE
[12.0][MIG] stock_reserve_rule

### PR DESCRIPTION
**Pull request by AdriaGForgeFlow**
Standard back-port of module stock_reserve_rule from v13.

Depends on:

- [x]  [OCA/product-attribute/647](https://github.com/OCA/product-attribute/pull/647)

cc ~ @ForgeFlow @guewen @jgrandguillaume

### CODE REVIEW

**Comment by guewen** [comment]
@AdriaGForgeFlow could you cherry-pick this commit: https://github.com/OCA/stock-logistics-warehouse/pull/797/commits/f1c4afc82408312e1709aa283dec2d8b9b77f751

Which can prevent to make tests of other modules fail?

**Comment by AdriaGForgeFlow** [comment]
> @AdriaGForgeFlow could you cherry-pick this commit: [f1c4afc](https://github.com/OCA/stock-logistics-warehouse/commit/f1c4afc82408312e1709aa283dec2d8b9b77f751)
> 
> Which can prevent to make tests of other modules fail?

Done :+1:

**Comment by AdriaGForgeFlow** [comment]
ping @guewen @jgrandguillaume

**Review by guewen — APPROVED** [review]

**Review by JordiBForgeFlow — APPROVED** [review]
:+1: Functional tests. Thanks @guewen and @AdriaGForgeFlow !

**Pull request merged**
