### PR TITLE
[MIG][9.0] Migrate stock_mts_mto_rule

### PR DESCRIPTION
**Pull request by Garamotte**
Superseds #157 :
- Add missing commits from changes in 8.0 branch
- Includes changes made in #157
- Updated README.rst
#203 was based on #157, and has already been merged, so I think this one can be quickly merged.

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Some tests that don't reduce coverage would be good.

**Comment by Garamotte** [comment]
Updated unit tests.

I didn't achieve to reach this line : https://coveralls.io/builds/8367627/source?filename=stock_mts_mto_rule/model/procurement.py#L95

**Comment by pedrobaeza** [comment]
Well, it's a lot. If you don't want to be faulted by that line and it's an strange condition that is rarely given, you can bypass coverage using `# pragma: no cover` comment in the `if` sentence.

**Comment by Garamotte** [comment]
I think this is better to know that this line isn't tested than adding a no cover, isn't it ?

**Comment by pedrobaeza** [comment]
OK, good to me. Let's wait for a second reviewer to merge.

**Comment by Doscaal** [comment]
:+1:

**Comment by pedrobaeza** [comment]
We need a third one before 5 working days for merging. Please ping me if there's no one but 5 working days has past.

**Review by andhit-r — APPROVED** [review]
:+1:

**Pull request merged**
