### PR TITLE
[16.0] [MIG] stock_packaging_calculator_packaging_type + Rename stock_packaging_calculator_packaging_level

### PR DESCRIPTION
**Pull request by marielejeune**

### CODE REVIEW

**Comment by marielejeune** [comment]
Duplicate with https://github.com/OCA/stock-logistics-warehouse/pull/1816 but pipeline is not green there ...

**Review by cyrilmanuel — APPROVED** [review]

**Review by cyrilmanuel — APPROVED** [review]

**Review by cyrilmanuel — APPROVED** [review]

**Review by rousseldenis — APPROVED** [review]
Code review

**Review by simahawk — APPROVED** [review]
LG

**Pull request merged**
