### PR TITLE
[14.0][ADD] stock_inventory_tier_validation

### PR DESCRIPTION
**Pull request by patrickrwilson**
Adds tier validation to stock inventory adjustments.

### CODE REVIEW

**Comment by marcelsavegnago** [comment]
Hey, @patrickrwilson, could you please do a rebase for me? thanks

**Comment by bosd** [comment]
Can someone rebase again, to trigger runboat??

**Comment by rousseldenis** [comment]
@patrickrwilson

**Review by rousseldenis — APPROVED** [review]

**Comment by rousseldenis** [comment]
@patrickrwilson Could you rebase ?

**Comment by patrickrwilson** [comment]
@rousseldenis rebase complete, all checks passed

**Review by bosd — APPROVED** [review]
LGTM

**Review by AungKoKoLin1997 — APPROVED** [review]

**Comment by bosd** [comment]
🚀 Let's go and merge this! Someone has the super powers here?

**Pull request merged**
