### PR TITLE
[17.0][MIG] stock_reserve: Migration to 17.0

### PR DESCRIPTION
**Pull request by chrisandrewmann**

### CODE REVIEW

**Review by milinsoft — APPROVED** [review]

**Comment by chrisandrewmann** [comment]
Hi @bodedra and @pedrobaeza 
Any chance of getting this merged pleased?

**Comment by pedrobaeza** [comment]
/ocabot migration stock_reserve

It should be reviewed by a PSC or module maintainer for being merged.

**Review by celm1990 — APPROVED** [review]
Please squash commits

**Comment by chrisandrewmann** [comment]
> Please squash commits

@celm1990 Sorry not sure which commits you mean, I thought i'd followed the procecdure. 
Also not sure why codecov/project is failing, looking at the analysis it's referring to files i've not even touched.

**Comment by rousseldenis** [comment]
> Sorry not sure which commits you mean, I thought i'd followed the procecdure.

No, that's ok like that.

**Comment by chrisandrewmann** [comment]
I've rebased with 17.0 and then squashed any duplicate "weblate" italian translations to clean it up a bit.
Hope this works ok. 
Update: Still failing codecov/project. @rousseldenis any idea why this is?

**Pull request merged**
