### PR TITLE
Updated from template - Switch to Github actions

### PR DESCRIPTION
**Pull request by rousseldenis**

### CODE REVIEW

**Comment by rousseldenis** [comment]
Detected licenses issues:

- stock_pull_list: @LoisRForgeFlow Your module is LGPL and depends on AGPL one. It is forbidden. What do you want for this ?
- stock_request_analytic: @LoisRForgeFlow @AaronHForgeFlow
- stock_vertical_lift_qty_by_packaging @simahawk @sebalix 

Thanks for your answers

**Comment by rousseldenis** [comment]
@LoisRForgeFlow @AaronHForgeFlow @simahawk @sebalix

**Comment by simahawk** [comment]
@rousseldenis maybe we should move fwd w/ https://github.com/OCA/oca-addons-repo-template/pull/124

**Comment by rousseldenis** [comment]
> @rousseldenis maybe we should move fwd w/ [OCA/oca-addons-repo-template#124](https://github.com/OCA/oca-addons-repo-template/pull/124)

Mmmh, maybe, but that does not change the fact licenses are wrongs

**Comment by max3903** [comment]
@rousseldenis Can you bump `setuptools-odoo` to `3.0.3` and avoid the following error:
```
FileNotFoundError: [Errno 2] No such file or directory: '$HOME/.cache/pre-commit/repoxjtox4sd/py_env-python3/lib/python3.6/site-packages/setuptools_odoo/addons-7c.txt'

```

**Comment by rousseldenis** [comment]
> 

What are you doing to have this error ?

**Comment by rousseldenis** [comment]
> @rousseldenis Can you bump `setuptools-odoo` to `3.0.3` and avoid the following error:
> 
> ```
> FileNotFoundError: [Errno 2] No such file or directory: '$HOME/.cache/pre-commit/repoxjtox4sd/py_env-python3/lib/python3.6/site-packages/setuptools_odoo/addons-7c.txt'
> ```

As I see here : https://github.com/OCA/oca-addons-repo-template/commit/f30ea60a2d33211e1febb162e17319e89e8002ce

This is needed only for Odoo >= 15

**Comment by rousseldenis** [comment]
@simahawk @LoisRForgeFlow I have changed licenses and development statuses in order not to block this anymore.

**Pull request merged**
