### PR TITLE
[11.0][IMP] stock_orderpoint_purchase_link: action view purchase

### PR DESCRIPTION
**Pull request by HviorForgeFlow**
Shows non-direct linked purchases

CC @Eficent

### CODE REVIEW

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: Code review LGTM

**Review by AdriaGForgeFlow — APPROVED** [review]
Code review :+1:

**Review by MiquelRForgeFlow — APPROVED** [review]
code review :+1:

**Comment by LoisRForgeFlow** [comment]
@hveficent seem this is making stock_request tests to fail :thinking: can you rebase and have a look?

**Comment by HviorForgeFlow** [comment]
@lreficent stock_request test are too rigid, error is not related with this PR. Sometimes stock_request tests pass and sometimes they fail, depends of the CI Build.

**Comment by LoisRForgeFlow** [comment]
How can that be? maybe that's something we have to address in a different PR. For now, let's try to merge again.

/ocabot merge minor

**Pull request closed without merging**
