### PR TITLE
[16.0][ADD] stock_valuation_layer_accounting_date

### PR DESCRIPTION
**Pull request by kanda999**
Odoo standard function of inventory valuation calculate depends on create_date of valuation layer. So, inventory quantities and amounts in the inventory valuation report does not necessarily reflect the real balances.

For example, if we create delivery order with post date and also accounting date for this delivery valuation entry as same post date, the valuation report that is calculated before post date should not count that quantities and amounts but odoo default does.

This module provides to calculate inventory valuation with accounting date and will reflect the real balances since accounting date is considered.

@qrtl

### CODE REVIEW

**Review by AungKoKoLin1997 — APPROVED** [review]

**Review by rinaldifirdaus — APPROVED** [review]

**Review by rousseldenis — APPROVED** [review]
LGTM

**Comment by rousseldenis** [comment]
@kanda999 Could you rebase ?

**Comment by kanda999** [comment]
@rousseldenis 
I rebased it but there seems to be an error somewhere unrelated to this PR. I will rebase again when the error is fixed.

**Pull request merged**
