### PR TITLE
[14.0][MIG] stock_request_direction

### PR DESCRIPTION
**Pull request by Freni-OSI**

### CODE REVIEW

**Comment by kittiu** [comment]
Hello. Already a migration here, https://github.com/OCA/stock-logistics-warehouse/pull/1126

**Comment by Freni-OSI** [comment]
> Hello. Already a migration here, #1126

Hi, Asked you to add tests ASAP. But Got no update from you.

**Comment by etobella** [comment]
In that case, you could have taken the same history and make a superseed keeping his commits

**Comment by kittiu** [comment]
> > Hello. Already a migration here, #1126
> 
> Hi, Asked you to add tests ASAP. But Got no update from you.

Yes, if you are in urgency, you can pull commit history and add more test on top of it. So we can respect commit history.
Sometime, we are just too busy with other work. Sorry!

**Comment by Freni-OSI** [comment]
#1223

**Pull request closed without merging**
