### PR TITLE
[stock_request_kanban][FIX] _get_inventory_kanban_domain

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
Small fix to greenify Travis in base branch 11.0

### CODE REVIEW

**Comment by JordiBForgeFlow** [comment]
cc @etobella

**Review by rousseldenis — APPROVED** [review]
Of course !

**Comment by rousseldenis** [comment]
@jbeficent Please wait for all green before merging next time :grin:

**Comment by JordiBForgeFlow** [comment]
@rousseldenis Agreed. I somehow got confused and thought it was already green ;)

**Comment by etobella** [comment]
LGTM :+1:

**Pull request merged**
