### PR TITLE
[13.0] [MIG] stock account internal move

### PR DESCRIPTION
**Pull request by rajkumar-py**
Adapted and implemented new concept of stock valuation layer for stock account internal move as well. Needs review for this migration.

### CODE REVIEW

**Comment by ThijsvOers** [comment]
Hi,

I have been testing this module in Odo0 13 CE  (i am not sure if the module is ready for testing but it has the label 'needs review'.  

I have added 2 stock evaluation accounts in a pre-production location.

I then created a BOM with 2 lines (both raw materials). The final produc has a route with the extra pre-production picking step.

When I validate the picking of the materials (from stock to the pre-production location), I get the following error. I do not get the error if I have a BOM with only one line.

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/models.py", line 4971, in ensure_one
    _id, = self._ids
ValueError: too many values to unpack (expected 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/odoo/odoo-server/odoo/http.py", line 664, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 909, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 1323, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 1311, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 395, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 382, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/odoo/odoo-server/addons/stock/wizard/stock_backorder_confirmation.py", line 31, in process_cancel_backorder
    self._process(cancel_backorder=True)
  File "/odoo/odoo-server/addons/stock/wizard/stock_backorder_confirmation.py", line 25, in _process
    confirmation.pick_ids.with_context(cancel_backorder=cancel_backorder).action_done()
  File "/odoo/odoo-server/addons/mrp_subcontracting/models/stock_picking.py", line 46, in action_done
    res = super(StockPicking, self).action_done()
  File "/odoo/odoo-server/addons/stock/models/stock_picking.py", line 705, in action_done
    todo_moves._action_done(cancel_backorder=self.env.context.get('cancel_backorder'))
  File "/odoo/odoo-server/addons/stock_account/models/stock_move.py", line 238, in _action_done
    valued_moves = {valued_type: self.env['stock.move'] for valued_type in self._get_valued_types()}
  File "/opt/odoo/odoo/custom/addons/stock_account_internal_move/models/stock_move.py", line 13, in _get_valued_types
    if self._is_internal():
  File "/opt/odoo/odoo/custom/addons/stock_account_internal_move/models/stock_move.py", line 96, in _is_internal
    self.ensure_one()
  File "/odoo/odoo-server/odoo/models.py", line 4974, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: stock.move(48, 49)

**Comment by rajkumar-py** [comment]
@ThijsvOers  check now error is fixed

**Comment by ThijsvOers** [comment]
@Rajkumar-pondy  tested and I do not get the error any more, thank you for fixing

**Comment by rajkumar-py** [comment]
@ThijsvOers 👍👍

**Comment by rousseldenis** [comment]
@Rajkumar-pondy Could you follow migration guide for 13.0 : https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0#technical-method-to-migrate-a-module-from-120-to-130-branch

and specifically lines about pre-commit as adopted for >= v13.0 branches

**Comment by rajkumar-py** [comment]
@rousseldenis Yes I followed migration steps according to migration guide. Is that anything wrong please let me know. I followed pre-commit steps according to the migration guide document.

**Comment by rousseldenis** [comment]
See Travis pre-commit errors. You need to run pre-commit

**Comment by rajkumar-py** [comment]
Ok I will run pre-commit..

**Comment by rousseldenis** [comment]
@Rajkumar-pondy This is still red.

**Comment by bachpham** [comment]
Somehow, this is still runing

**Comment by rousseldenis** [comment]
@Rajkumar-pondy Could you install pre-commit on your local env (pre-commit install) before committing? This will help you to get pre-commit test green on travis and let the real tests running

**Comment by ShivamS-SerpentCS** [comment]
@Rajkumar-pondy , 

Are you working on this PR?

**Pull request closed without merging**
