### PR TITLE
[ENH][11.0] stock_orderpoint_uom

### PR DESCRIPTION
**Pull request by bodedra**
Need to review:

- check context to avoid twice quantity calculation.

### CODE REVIEW

**Review by max3903 — APPROVED** [review]

**Comment by LoisRForgeFlow** [comment]
@bodedra could you explain a little why are you doing this?

**Comment by bodedra** [comment]
@lreficent sorry for late response on these. Would you please review new updated change on it and also https://github.com/OCA/stock-logistics-warehouse/pull/396

**Review by rousseldenis — APPROVED** [review]

**Review by LoisRForgeFlow — CHANGES_REQUESTED** [review]
This is not the way to fix the issue. see https://github.com/OCA/stock-logistics-warehouse/pull/396#pullrequestreview-105699909

**Comment by LoisRForgeFlow** [comment]
This is not needed, proper fix is being done at https://github.com/OCA/stock-logistics-warehouse/pull/396

**Pull request closed without merging**
