### PR TITLE
[14.0] [MIG] procurement_auto_create_group

### PR DESCRIPTION
**Pull request by DavidBForgeFlow**
Standard migration to v14.

@LoisRForgeFlow

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]
Code review

**Comment by LoisRForgeFlow** [comment]
@DavidBForgeFlow Looks good! Just one comment, could you fix the commit history? It seems some commits are duplicated 
image

I usually expect 2 commits in a migration, the black, isort one and the acutual migration one.

**Comment by DavidBForgeFlow** [comment]
> @DavidBForgeFlow Looks good! Just one comment, could you fix the commit history? It seems some commits are duplicated
> image
> 
> I usually expect 2 commits in a migration, the black, isort one and the acutual migration one.

Fixed

**Review by mariadforgeflow — APPROVED** [review]
LGTM

**Review by LoisRForgeFlow — APPROVED** [review]

**Pull request merged**
