### PR TITLE
[16.0][IMP] Add packaging and packaging qty done to move line tree detailed

### PR DESCRIPTION
**Pull request by EmilioPascual**
Add packaging and packaging qty done to move line tree detailed.

https://www.loom.com/share/f6bf4e9295164bc3af76ca83c3dcb1f1

@yajo @shide please review.

MT-5810 @moduon

### CODE REVIEW

**Review by Shide — APPROVED** [review]
Code review

**Review by yajo — APPROVED** [review]
/ocabot merge minor

**Comment by rousseldenis** [comment]
@EmilioPascual Don't forget for the next time to set in your commit message the module name you modified (`[IMP] stock_move_packaging_qty: (...)`)

**Comment by EmilioPascual** [comment]
> @EmilioPascual Don't forget for the next time to set in your commit message the module name you modified (`[IMP] stock_move_packaging_qty: (...)`)

It's true, I forgot it. Thank you.

**Pull request merged**
