### PR TITLE
[10.0][MIG] stock_available & stock_available_immediately

### PR DESCRIPTION
**Pull request by SodexisTeam**
Moved commit history with PR https://github.com/OCA/stock-logistics-warehouse/pull/192

cc: @gurneyalex @pedrobaeza @sylvain-garancher

### CODE REVIEW

**Comment by atchuthan** [comment]
Needs label change to "Needs Review"

**Comment by pedrobaeza** [comment]
Can you take care of the coverage drop?

**Comment by atchuthan** [comment]
@pedrobaeza fixed coverage drop

**Review by pedrobaeza — APPROVED** [review]
OK, enough for me

**Review by dvdhinesh — APPROVED** [review]
Code review :+1:

**Pull request merged**
