### PR TITLE
[14.0][IMP] stock_move_location: packages support

### PR DESCRIPTION
**Pull request by Abranes**
Implement support for move packages.

### CODE REVIEW

**Comment by rousseldenis** [comment]
@Abranes Thanks for this.

To be complete, I would add owner_id too.

**Comment by rousseldenis** [comment]
@Abranes Do you plan to attend comments ?

**Comment by hildickethan** [comment]
@rousseldenis He no longer works in this company so he can't continue on this branch, but he sent me the changes needed. I need to check everything is OK, I am a bit busy the next couple days, but I will see if I can get it done within the week and we can merge

**Comment by hildickethan** [comment]
@rousseldenis Owner support added in the 2nd commit

**Review by rousseldenis — APPROVED** [review]
Code review

**Comment by rousseldenis** [comment]
@joao-p-marques @mathieuvatel

**Comment by rousseldenis** [comment]
@sebalix @grindtildeath @LoisRForgeFlow @jbaudoux

**Review by jbaudoux — APPROVED** [review]
LGTM

**Pull request merged**
