### PR TITLE
[FIX] fix a bug when iterate the data with call create

### PR DESCRIPTION
**Pull request by nicomacr**
Fix a bug when call the create method with data dict, in each iteration modify data dict.

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]
Makes sense.

**Comment by rousseldenis** [comment]
@nicomacr Can you put maybe a stack trace you had or a little bit explain what happen.

Because data is a copy yet. And just the product_id is modified on each itearation.

**Comment by nicomacr** [comment]
@rousseldenis what is happening is that when you call the create in each iteration the value "data" is overwritten somewhere in the create method and brings values ​​that then give error, like for example the followers of the models.

**Comment by rousseldenis** [comment]
@nicomacr Ok, that makes sense obviously!

**Review by jjscarafia — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Do you know why Travis is red?

**Review by zaoral — APPROVED** [review]
+1
Thanks @nicomacr 

@pedrobaeza  It seems like this error is in 11.0 branch already, is not introduced by this change. You can see this in [travis](https://travis-ci.org/OCA/stock-logistics-warehouse/builds/419619256?utm_source=github_status&utm_medium=notification) 

Best Regards

**Comment by zaoral** [comment]
Who has permissions to re run travis 9.0 branch? 
the last 9.0 run was a month ago. There is a change that this error was introduced in this month and that we do not notice?

It seems like this PR solve it https://github.com/OCA/stock-logistics-warehouse/pull/467
Thanks @rousseldenis

**Comment by pedrobaeza** [comment]
Yes, it's OK, thanks.

**Pull request merged**
