### PR TITLE
[8.0] partner_location_auto_create: translation and security update

### PR DESCRIPTION
**Pull request by zimbora69**
Portuguese Brazilian translation and updated smart button group to warehouse manager

### CODE REVIEW

**Comment by Cedric-Pigeon** [comment]
@zimbora69 Hello, do you plan to achieve this PR? Is it still usefull ? thanks

**Comment by rousseldenis** [comment]
@zimbora69

**Comment by LoisRForgeFlow** [comment]
This has been inactive for a long time, has conflicts and modified translations directly. Better to close it I think.

**Comment by rousseldenis** [comment]
Agree

**Pull request closed without merging**
