### PR TITLE
[14.0][MIG] stock_request_kanban

### PR DESCRIPTION
**Pull request by BernatPForgeFlow**

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]

**Comment by rousseldenis** [comment]
@BernatPForgeFlow Could you rebase ?

**Comment by BernatPForgeFlow** [comment]
> @BernatPForgeFlow Could you rebase ?

Done!

**Review by olgamarcocb — APPROVED** [review]
LGTM 👍

**Pull request merged**
