### PR TITLE
[14.0][imp] discrepancy by product avg

### PR DESCRIPTION
**Pull request by dnplkndll**
group products to see discrepancy across locations

### CODE REVIEW

**Review by JordiBForgeFlow — APPROVED** [review]

**Comment by dnplkndll** [comment]
is there a trick to update the totals? or that an OWL thing?
image

**Comment by LoisRForgeFlow** [comment]
> is there a trick to update the totals? or that an OWL thing? image

Yes, the group totals does not update automatically, that would probably need some JS/owl patch. As a workaround, you can just tap enter on the search bar to refresh the totals.

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM

**Comment by rousseldenis** [comment]
@dnplkndll Could you include a fix for these warnings too ? Thanks

image

**Comment by dnplkndll** [comment]
> @dnplkndll Could you include a fix for these warnings too ? Thanks

Is there a trick to access the runbot log?

or is the travis sufficient?
https://app.travis-ci.com/github/OCA/stock-logistics-warehouse/jobs/548717325

**Review by JordiBForgeFlow — APPROVED** [review]

**Comment by JordiBForgeFlow** [comment]
@LoisRForgeFlow can you merge?

**Review by etobella — APPROVED** [review]

**Comment by LoisRForgeFlow** [comment]
@JordiBForgeFlow you can too!

/ocabot merge minor

**Pull request merged**
