### PR TITLE
[10.0][MIG] stock change qty reason

### PR DESCRIPTION
**Pull request by GillesTephaneMeyomesse**

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]

**Comment by rousseldenis** [comment]
@GillesTephaneMeyomesse don't forget to squash for the fix commit

**Comment by GillesTephaneMeyomesse** [comment]
@rousseldenis yes, thank you !

**Review by lmignon — APPROVED** [review]
:+1:  Code review + Functional tests

**Review by Cedric-Pigeon — CHANGES_REQUESTED** [review]
+1

**Review by Cedric-Pigeon — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Please squash commits before merging

**Comment by lmignon** [comment]
@pedrobaeza Transbot commits squashed

**Pull request merged**
