### PR TITLE
[10.0][MIG] port stock_available_mrp to 10.0 with fixup

### PR DESCRIPTION
**Pull request by tschanzt**
**Requires #474**

Superseeds #280 
@rafaelbn I created a new pr as the original one doesn't seem to be active anymore. Could you recheck? 
Your issues with the duplicate button and wrong immediately available quantity should be fixed now.

/cc @Cedric-Pigeon

### CODE REVIEW

**Comment by rousseldenis** [comment]
@tschanzt Please be aware of this https://github.com/OCA/stock-logistics-warehouse/pull/474/files

Your commit https://github.com/OCA/stock-logistics-warehouse/pull/494/commits/a87ab89c84cde99495eb7683558edfd8d170c9b3 has to take it into account

**Comment by rousseldenis** [comment]
Moreover, the original PR is not inactive. Why not proposing your changes in a PR in author's repo ?

**Comment by tschanzt** [comment]
@rousseldenis ah yeah I can change that. It is mentioned nowhere, so when you checkout the pr the display of the product form fails with an exception, which lead to the change. Ill drop the commit and add a comment to the pr that it bases on this.
Also since Cedric didn't respond, so I assumed it was, but as you respond i can change it.

**Comment by rousseldenis** [comment]
Ok, I'll stay aware on this. Don't hesitate to ping me for further review

**Comment by tschanzt** [comment]
@closed as per discussion with @rousseldenis I will open a pr on the acsone branch.

**Pull request closed without merging**
