### PR TITLE
[13.0][MIG] stock_request_direction

### PR DESCRIPTION
**Pull request by ps-tubtim**
Standard migration.

### CODE REVIEW

**Review by dreispt — APPROVED** [review]

**Review by etobella — APPROVED** [review]

**Comment by brian10048** [comment]
@ps-tubtim The Travis build is red when attempting to merge this PR.  [https://travis-ci.org/github/OCA/stock-logistics-warehouse/jobs/736077426#L301](https://travis-ci.org/github/OCA/stock-logistics-warehouse/jobs/736077426#L301)  Can apply prettier formatting so this can be merged?

**Review by bodedra — APPROVED** [review]

**Pull request merged**
