### PR TITLE
Added openerp path to imports in order to stick on strict import

### PR DESCRIPTION
**Pull request by agb80**
Just a minor change to import using absolute import and prevent the warning messages on Pydev

### CODE REVIEW

**Comment by pedrobaeza** [comment]
You don't need this. You can put relative import: `from .stock_inventory_hierarchical import HierarchicalInventoryException`

**Comment by gurneyalex** [comment]
I agree with @pedrobaeza. Can you change your PR to do a relative import?

**Comment by agb80** [comment]
Sorry for being so late in fix this, didn't notice your original comment @pedrobaeza

**Comment by bealdav** [comment]
:+1:

**Review by Cedric-Pigeon — APPROVED** [review]

**Pull request merged**
