### PR TITLE
[12.0][MIG] stock_move_location

### PR DESCRIPTION
**Pull request by JoanSForgeFlow**
Also improves lines creation in the wizard.
cc @Eficent

### CODE REVIEW

**Review by AaronHForgeFlow — APPROVED** [review]
Functional tests + Code review

**Review by NuriaXifre — APPROVED** [review]
Functional review done!

**Review by rousseldenis — APPROVED** [review]
Code review

**Comment by rousseldenis** [comment]
@joansis Do you plan to squash commits or let like this ?

**Comment by JoanSForgeFlow** [comment]
@rousseldenis I think like this is fine. One commit is for the migration, other for an improvement, and the other one is a separate fix.

**Pull request merged**
