### PR TITLE
[FIX] stock_secondary_unit: Compute secondary_unit_qty_available field with sudo

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa TT25561
In kanban view also the user has not inventory user group the available quantities has been computed.
I have tried adding compute_sudo=True to field but this is not working

ping @carlosdauden ping  @victoralmau

### CODE REVIEW

**Comment by pedrobaeza** [comment]
The potential problem I see is that in a multi-company environment, if the product is used by both companies, qty_available will be correct?

**Comment by sergio-teruel** [comment]
Ok... And with a force_company??

**Comment by sergio-teruel** [comment]
Maybe I can use company_owned context..

https://github.com/odoo/odoo/blob/dd160aa0ac4512a498a002e21c74e9546de371f8/addons/stock/models/product.py#L234

**Comment by pedrobaeza** [comment]
Yeah, maybe, although I don't get the problem if all views already have inventory user group for avoiding salesman to see them.

**Comment by sergio-teruel** [comment]
Please read the initial comment

**Comment by sergio-teruel** [comment]
Closed by https://github.com/OCA/stock-logistics-warehouse/pull/1005

**Pull request closed without merging**
