### PR TITLE
[16.0][MIG] stock_vlm_mgmt: Migration to 16.0

### PR DESCRIPTION
**Pull request by chienandalu**
Migrated from

- #2022

Tasks:

- Standard migration
- Bug fixing
- Refactor of the tray matrix widget to OWL trimming it to the minimum

cc @Tecnativa TT48109

please review @pedrobaeza 

fyi @ValentinVinagre

### CODE REVIEW

**Comment by ValentinVinagre** [comment]
@chienandalu Interesting We'll give it a look 😃.  Initially we plan to bring our development for vertical warehouses to the end of the year or the beginning of next year for v.17-18.

**Review by Deriman-Alonso — APPROVED** [review]
LGTM 👍

**Review by pedrobaeza — APPROVED** [review]
Code review + test in the real instance

/ocabot merge nobump

**Comment by rousseldenis** [comment]
> @chienandalu Interesting We'll give it a look 😃. Initially we plan to bring our development for vertical warehouses to the end of the year or the beginning of next year for v.17-18.

@ValentinVinagre You can also look at the whole ecosystem on a more complex flows with all the stock_vertical_lift* modules still in v14 : https://github.com/OCA/stock-logistics-warehouse/tree/14.0

**Pull request merged**
