### PR TITLE
[9.0] [FIX] Purchase Packaging: purchase line product qty should be stored

### PR DESCRIPTION
**Pull request by ThomasBinsfeld**
Backport of https://github.com/OCA/stock-logistics-warehouse/pull/493

It fixes a bug with order line prices computation.

### CODE REVIEW

**Comment by rousseldenis** [comment]
@ThomasBinsfeld Could you rebase? Travis configuration is fixed

**Comment by ThomasBinsfeld** [comment]
@rousseldenis Are you sure? The last commit on 9.0 branch is from the 29th of July. My branch is already based on 9.0 HEAD. 

EDIT: waiting #748 to be merged to rebase.

**Comment by ThomasBinsfeld** [comment]
Rebased

**Comment by rousseldenis** [comment]
@pedrobaeza Are all runbot for former versions (v10, 9,..) deactivated ('skipped' results) ?

**Comment by pedrobaeza** [comment]
Maybe rebasing over latest main branch with updated .travis.yml fixes it.

**Pull request closed without merging**
