### PR TITLE
[17.0][MIG] account_move_line_stock_info

### PR DESCRIPTION
**Pull request by StefanRijnhart**
Superseding https://github.com/OCA/stock-logistics-warehouse/pull/1967

### CODE REVIEW

**Review by astirpe — APPROVED** [review]
LGTM!

**Review by rousseldenis — APPROVED** [review]
LGTM

**Review by sebalix — APPROVED** [review]

**Comment by sebalix** [comment]
/ocabot merge minor

EDIT: oops, canceled the merge

**Pull request merged**
