### PR TITLE
[11.0][MIG] stock reserve sale

### PR DESCRIPTION
**Pull request by RodrigoBM**
Standard migration

This PR depend to approval this other #883 

Thanks

### CODE REVIEW

**Comment by rousseldenis** [comment]
Have you seen that some other branches have this (maybe you are missing some commits) ?

**Comment by RodrigoBM** [comment]
Hi @rousseldenis,

I do not understand your comment. Can you explain me with more details?

Thanks

**Comment by rousseldenis** [comment]
See https://github.com/OCA/stock-logistics-warehouse/commits/9.0/stock_reserve_sale for example.

There are some commits missing here

**Comment by RodrigoBM** [comment]
it is possible, I have migrated from v10, I will review the commits from v9

https://github.com/OCA/stock-logistics-warehouse/commits/10.0/stock_reserve_sale

**Pull request closed without merging**
