### PR TITLE
[14.0][FIX] stock_pull_list: do not show any lines when there's no quantity needed

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
Added tests

cc @ForgeFlow @LoisRForgeFlow

### CODE REVIEW

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM

**Comment by JordiBForgeFlow** [comment]
@NuriaXForgeFlow

**Review by cubells — APPROVED** [review]
:+1: 

LGTM

Code review and test

**Pull request merged**
