### PR TITLE
[MIG] [13.0] stock_mts_mto_rule

### PR DESCRIPTION
**Pull request by ludolelarge**

### CODE REVIEW

**Comment by ludolelarge** [comment]
**Commented  'propagate': True, in this function so the module could be installed**

    def _get_global_route_rules_values(self):
        rule = self.get_rules_dict()[self.id][self.delivery_steps]
        rule = [r for r in rule if r.from_loc == self.lot_stock_id][0]
        location_id = rule.from_loc
        location_dest_id = rule.dest_loc
        picking_type_id = rule.picking_type
        res = super(StockWarehouse, self)._get_global_route_rules_values()
        res.update({
            'mts_mto_rule_id': {
                'depends': ['delivery_steps', 'mto_mts_management'],
                'create_values': {
                    'action': 'pull',
                    'procure_method': 'make_to_order',
                    'company_id': self.company_id.id,
                    'auto': 'manual',
                    #'propagate': True,
                    'route_id': self._find_global_route(
                        'stock_mts_mto_rule.route_mto_mts',
                        _('Make To Order + Make To Stock')).id,
                },
                'update_values': {
                    'active': self.mto_mts_management,
                    'name': self._format_rulename(location_id,
                                                  location_dest_id,
                                                  'MTS+MTO'),
                    'location_id': location_dest_id.id,
                    'location_src_id': location_id.id,
                    'picking_type_id': picking_type_id.id,
                }
            },
        })
        return res

**Comment by ludolelarge** [comment]
**Error when i confirm the sales order**

  File "/home/ludovic/workspace/odoo13/odoo/addons/sale_stock/models/sale_order.py", line 98, in _action_confirm
    self.order_line._action_launch_stock_rule()
  File "/home/ludovic/workspace/odoo13/odoo/addons/procurement_jit/sale.py", line 11, in _action_launch_stock_rule
    res = super(SaleOrderLine, self)._action_launch_stock_rule(previous_product_uom_qty=previous_product_uom_qty)
  File "/home/ludovic/workspace/odoo13/odoo/addons/sale_stock/models/sale_order.py", line 504, in _action_launch_stock_rule
    self.env['procurement.group'].run(procurements)
  File "/home/ludovic/workspace/odoo13/odoo/addons/mrp/models/stock_rule.py", line 141, in run
    return super(ProcurementGroup, self).run(procurements_without_kit)
  File "/home/ludovic/workspace/odoo13/odoo/addons/stock/models/stock_rule.py", line 381, in run
    getattr(self.env['stock.rule'], '_run_%s' % action)(procurements)
TypeError: _run_split_procurement() missing 6 required positional arguments: 'product_qty', 'product_uom', 'location_id', 'name', 'origin', and 'values'

**Comment by ludolelarge** [comment]
**Help needed ...**

In this part of function the setattr fonction return me a set attribute Error
The code I want to run is in comment

    def _run_split_procurement(self,procurements):
        for procurement, rule in procurements :
            precision = self.env['decimal.precision']\
                .precision_get('Product Unit of Measure')
            needed_qty = self.get_mto_qty_to_order(procurement.product_id, procurement.product_qty,
                                               procurement.product_uom, procurement.values)

            if float_is_zero(needed_qty, precision_digits=precision):
                getattr(self.mts_rule_id, '_run_%s' % rule.mts_rule_id.action)(procurements)
            elif float_compare(needed_qty, procurement.product_qty,
                           precision_digits=precision) == 0.0:
                getattr(self.mto_rule_id,  '_run_%s' % rule.mto_rule_id.action)(procurements)
            else:
                qty = procurement.product_qty - needed_qty
                **setattr(procurement, 'product_qty', qty)
                #procurement.product_qty = procurement.product_qty - needed_qty**
                getattr(self.mts_rule_id, '_run_%s' % rule.mts_rule_id.action)(procurements)
                setattr(procurement, 'product_qty', needed_qty)
                **#procurement.product_qty = needed_qty
                getattr(self.mto_rule_id, '_run_%s' % rule.mto_rule_id.action)(procurements)**
                
        return True

THX

**Comment by ludolelarge** [comment]
> 
> 
> **Help needed ...**
> 
> In this part of function the setattr fonction return me a set attribute Error
> The code I want to run is in comment
> 
> ```
> def _run_split_procurement(self,procurements):
>     for procurement, rule in procurements :
>         precision = self.env['decimal.precision']\
>             .precision_get('Product Unit of Measure')
>         needed_qty = self.get_mto_qty_to_order(procurement.product_id, procurement.product_qty,
>                                            procurement.product_uom, procurement.values)
> 
>         if float_is_zero(needed_qty, precision_digits=precision):
>             getattr(self.mts_rule_id, '_run_%s' % rule.mts_rule_id.action)(procurements)
>         elif float_compare(needed_qty, procurement.product_qty,
>                        precision_digits=precision) == 0.0:
>             getattr(self.mto_rule_id,  '_run_%s' % rule.mto_rule_id.action)(procurements)
>         else:
>             qty = procurement.product_qty - needed_qty
>             setattr(procurement, 'product_qty', qty)
>             #procurement.product_qty = procurement.product_qty - needed_qty
>             getattr(self.mts_rule_id, '_run_%s' % rule.mts_rule_id.action)(procurements)
>             setattr(procurement, 'product_qty', needed_qty)
>             #procurement.product_qty = needed_qty
>             getattr(self.mto_rule_id, '_run_%s' % rule.mto_rule_id.action)(procurements)
>             
>     return True
> ```
> 
> THX

HERE IS THE FIXED CODE

    def _run_split_procurement(self,procurements):
        for procurement, rule in procurements :
            precision = self.env['decimal.precision']\
                .precision_get('Product Unit of Measure')
            needed_qty = self.get_mto_qty_to_order(procurement.product_id, procurement.product_qty,
                                               procurement.product_uom, procurement.values)

            if float_is_zero(needed_qty, precision_digits=precision):
                getattr(self.mts_rule_id, '_run_%s' % rule.mts_rule_id.action)(procurements)
            elif float_compare(needed_qty, procurement.product_qty,
                           precision_digits=precision) == 0.0:
                getattr(self.mto_rule_id,  '_run_%s' % rule.mto_rule_id.action)(procurements)
            else:
                mts_qty = procurement.product_qty - needed_qty
                procurement = procurement._replace(product_qty = mts_qty)
                procurements = [[procurement,rule]]
                getattr(self.mts_rule_id, '_run_%s' % rule.mts_rule_id.action)(procurements)
                procurement = procurement._replace(product_qty = needed_qty)
                procurements = [[procurement,rule]]
                getattr(self.mto_rule_id, '_run_%s' % rule.mto_rule_id.action)(procurements)
                
        return True

**Comment by ludolelarge** [comment]
HELP WANTED

The module works but when I create an order form and I have 5 in stock for the product.
It creates 2 MO with 5 quantities, the normal behavior would be that it takes 5 quantity in stock and creates an MO of 5 quantities

**Comment by ludolelarge** [comment]
> 
> 
> HELP WANTED
> 
> The module works but when I create an order form and I have 5 in stock for the product.
> It creates 2 MO with 5 quantities, the normal behavior would be that it takes 5 quantity in stock and creates an MO of 5 quantities

Here is the fix (this module work like a charm)

    def _run_split_procurement(self,procurements):
        for procurement, rule in procurements :
            precision = self.env['decimal.precision']\
                .precision_get('Product Unit of Measure')
            needed_qty = self.get_mto_qty_to_order(procurement.product_id, procurement.product_qty,
                                               procurement.product_uom, procurement.values)

            if float_is_zero(needed_qty, precision_digits=precision):
                getattr(self.mts_rule_id, '_run_%s' % rule.mts_rule_id.action)(procurements)
            elif float_compare(needed_qty, procurement.product_qty,
                           precision_digits=precision) == 0.0:
                getattr(self.mto_rule_id,  '_run_%s' % rule.mto_rule_id.action)(procurements)
            else:
                mts_qty = procurement.product_qty - needed_qty
                procurement = procurement._replace(product_qty = mts_qty)
                rule.procure_method = 'make_to_stock'
                procurements = [[procurement,rule]]
                getattr(self.mts_rule_id, '_run_%s' % rule.mts_rule_id.action)(procurements)
                procurement = procurement._replace(product_qty = needed_qty)
                rule.procure_method = 'make_to_order'
                procurements = [[procurement,rule]]
                getattr(self.mto_rule_id, '_run_%s' % rule.mto_rule_id.action)(procurements)
                
        return True

**Comment by ps-tubtim** [comment]
Code LGTM. Could you do follow this wiki https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0 ?

**Review by AaronHForgeFlow — CHANGES_REQUESTED** [review]
Commit history missing and file number also not ok, manifest missing and only 2 files here. Please follow the steps here: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0 Just ask for help if you are unsure. Regards.

**Comment by pedrobaeza** [comment]
Already migrated.

**Pull request closed without merging**
