### PR TITLE
[12.0][ADD] stock_production_lot_quantity_tree

### PR DESCRIPTION
**Pull request by rousseldenis**

### CODE REVIEW

**Comment by nikul-serpentcs** [comment]
@rousseldenis Please Update **README.rs**t file

**Comment by rousseldenis** [comment]
> @rousseldenis Please Update **README.rs**t file

Oops, wrong DESCRIPTION. So fast :smile:

**Review by HaraldPanten — APPROVED** [review]

**Review by apollet — APPROVED** [review]
LGTM

**Pull request merged**
