### PR TITLE
[MIG] stock_move_auto_assign: Migration to 14.0

### PR DESCRIPTION
**Pull request by phuctranfxvn**
Standard as-is migration.

### CODE REVIEW

**Comment by sebalix** [comment]
@phuctranerp you included the migration commits of `stock_location_tray` by mistake I think, there is already a PR for that module here: https://github.com/OCA/stock-logistics-warehouse/pull/1079

**Review by sebalix — CHANGES_REQUESTED** [review]
@phuctranerp you included the migration commits of `stock_location_tray` by mistake I think, there is already a PR for that module here: https://github.com/OCA/stock-logistics-warehouse/pull/1079

**Comment by hailangvn** [comment]
Thanks @sebalix for your comment. We will work on this.

**Comment by hailangvn** [comment]
Thanks @sebalix for your comment. The PR has been updated.

**Review by sebalix — APPROVED** [review]

**Review by simahawk — APPROVED** [review]

**Review by TDu — APPROVED** [review]

**Comment by sebalix** [comment]
Runbot is still red, the only error/warning I found in its logs are related to the use of `track_visibility` parameter in one module, I fixed it here: https://github.com/OCA/stock-logistics-warehouse/pull/1274

**Comment by sebalix** [comment]
@hailangvn can you rebase on last 14.0 version? https://github.com/OCA/stock-logistics-warehouse/pull/1274 has been merged

**Comment by hailangvn** [comment]
Thanks @sebalix for the fix. This PR has been updated.

**Pull request merged**
