### PR TITLE
[10.0][MIG] stock_inventory_exclude_sublocation

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Standard migration.

Added:
- [x] Cherry-pick of https://github.com/OCA/stock-logistics-warehouse/pull/310/commits/82dce589412168fc718fd47eef0d4d91906fad81 (https://github.com/OCA/stock-logistics-warehouse/pull/310)

Depends of:
- [x] stock_inventory_chatter (https://github.com/OCA/stock-logistics-warehouse/pull/319)

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
functionally tested and not working properly:

selection_147

**Comment by MiquelRForgeFlow** [comment]
Now works properly 😉

**Comment by LoisRForgeFlow** [comment]
Great! :ok_hand: Would you now improve the tests with the new filter by category to improve coverage?

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: It works ok. Would you add some tests?

**Comment by gurneyalex** [comment]
closing to trigger a rebuild and get a codecov report.

**Review by rousseldenis — APPROVED** [review]
Code review. LGTM apart codecoverage (add test on inventory with category)

**Pull request merged**
