### PR TITLE
[FIX] stock_location_orderpoint/source_relocate: Use recordset for trap_jobs evaluation

### PR DESCRIPTION
**Pull request by rousseldenis**
…ap_jobs evaluation

Due to https://github.com/OCA/queue/pull/537/commits/299cf4d82a68614fb6cf376601ed5bbdee680753

### CODE REVIEW

**Comment by rousseldenis** [comment]
@OriolMForgeFlow

**Review by OriolMForgeFlow — APPROVED** [review]
Code review

**Review by mt-software-de — APPROVED** [review]
LGTM

**Review by mt-software-de — APPROVED** [review]
LGTM

**Pull request merged**
