### PR TITLE
11.0 mig stock quant merge

### PR DESCRIPTION
**Pull request by reynaldiyosfino**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This module has no sense now, as there's no quant fragmentation

**Comment by rousseldenis** [comment]
@reynaldiyosfino Please confirm @pedrobaeza comments.

This contains modification on other modules too. Dirty.

**Comment by rousseldenis** [comment]
@pedrobaeza The tests are showing that is not the case. You know why ?

**Comment by pedrobaeza** [comment]
This is because you can still create several quants for same values, but this is only done on a rare concurrency case, and amended on core on next touch, so definitively not needed. I close it as this even contains other unwanted files.

**Pull request closed without merging**
