### PR TITLE
[8.0][BACK] Backport of the stock_inventory_chatter

### PR DESCRIPTION
**Pull request by fkantelberg**
This is the backport of the mentioned module from the branch 9.0. The only required change was the version in the manifest.

### CODE REVIEW

**Comment by rousseldenis** [comment]
@fkantelberg Please preserve commit history

**Comment by fkantelberg** [comment]
@rousseldenis Do you mean that I should split the commit into the 2 steps I did? Copy from 9.0 branch and changing of the version. If not can you provide further explanation?

**Comment by rousseldenis** [comment]
@fkantelberg What I wanted to say that you have to take the commit history from 9.0 branch and then make a commit for the backport.
Example : https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0

In this case, I think you have just to have your clean migration branch and then launch the good git format patch command (inversing source and destination in the example).

`git format-patch --stdout origin/8.0..origin/9.0 -- stock_inventory_chatter | git am -3` 

Tested and it worked like a charm

**Comment by rousseldenis** [comment]
@fkantelberg I think this is not correct yet. The two first commits ('Add backport of stock inventory chatter' and the revert one) shouldn't exist

**Comment by fkantelberg** [comment]
@rousseldenis Sorry for the delay. I removed the mentioned commits. Thank you for the great help.

**Review by rousseldenis — APPROVED** [review]
LGTM

**Comment by rousseldenis** [comment]
@OCA/logistics-maintainers

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM

**Pull request merged**
