### PR TITLE
[8.0][stock_inventory_revaluation] -  Users in group 'inventory valuation' should be able to change quants

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
The application writes price changes in quants. Currently users in group "Inventory valuation" do not have permission to do that.

### CODE REVIEW

**Comment by JordiBForgeFlow** [comment]
cc @lreficent

**Review by andhit-r — APPROVED** [review]
:+1:

**Review by LoisRForgeFlow — APPROVED** [review]
:+1:

**Review by AaronHForgeFlow — APPROVED** [review]
LGTM :+1:

**Pull request merged**
