### PR TITLE
[13.0] Add module stock_move_common_dest

### PR DESCRIPTION
**Pull request by grindtildeath**
This module adds a M2m field `common_dest_move_ids` on `stock.move` in order
to compute all the moves having a chained destination move sharing the same
picking as the actual move's destination move.

### CODE REVIEW

**Review by Tonow-c2c — APPROVED** [review]

**Comment by rousseldenis** [comment]
@grindtildeath IMHO, this does not need Alpha as it is common use case. It seems ok for me. We can merge it soon.

**Comment by rousseldenis** [comment]
Could you check pre-commit ?

**Comment by grindtildeath** [comment]
@rousseldenis pre-commit run, and dropped the alpha status in manifest :wink:

**Review by simahawk — APPROVED** [review]
quick code review only

**Review by rousseldenis — APPROVED** [review]
Code review

**Comment by rousseldenis** [comment]
@grindtildeath So, ready for this ?

**Comment by grindtildeath** [comment]
@rousseldenis Sure, let's merge ! :+1:  :tada:

**Pull request merged**
