### PR TITLE
[15.0][MIG] procurement_auto_create_group

### PR DESCRIPTION
**Pull request by BernatPForgeFlow**
Migration of _procurement_auto_create_group_ .
Afterwards, _auto_create_group_ added for push rules using _push_rule_auto_create_group_ module from OCA/stock-logistics-warehouse version 11.

### CODE REVIEW

**Review by JoanMForgeFlow — APPROVED** [review]
Functional review ok! Thanks

**Review by AaronHForgeFlow — APPROVED** [review]
Functional tests :+1:

**Review by LoisRForgeFlow — APPROVED** [review]
Code review LGTM

**Pull request merged**
