### PR TITLE
[12.0][MIG] stock_picking_procure_method

### PR DESCRIPTION
**Pull request by kittiu**
Migratee to v12

### CODE REVIEW

**Comment by kittiu** [comment]
Ready for review and merge.

**Review by chienandalu — APPROVED** [review]
Looks good to me :+1:  thanks!

**Review by rousseldenis — CHANGES_REQUESTED** [review]
LGTM.
@kittiu Could you amend your commit message ?

**Comment by kittiu** [comment]
> LGTM.
> @kittiu Could you amend your commit message ?

Done

**Review by gurneyalex — APPROVED** [review]

**Review by rousseldenis — APPROVED** [review]
LGTM

**Pull request merged**
