### PR TITLE
[FIX] stock_request: Losing partner_id and origin (#664)

### PR DESCRIPTION
**Pull request by max3903**
#664

### CODE REVIEW

**Comment by rousseldenis** [comment]
Seems make sense.

Could you add a test that cover that behaviour ?

**Review by rousseldenis — APPROVED** [review]
Code review

**Review by etobella — APPROVED** [review]

**Comment by rousseldenis** [comment]
@max3903 Could you check travis ?

**Review by osi-scampbell — APPROVED** [review]

**Comment by rousseldenis** [comment]
Maybe  a rebase in this?

**Comment by rousseldenis** [comment]
Hope 12 branch will remain green

**Comment by rousseldenis** [comment]
@max3903 Could you check 12.0 branch? It is red now...

Did you rebase on it before creating this PR ?

**Comment by LoisRForgeFlow** [comment]
branch 12 is red after this merge (as the oca-bot anticipated btw).

**Comment by rousseldenis** [comment]
@lreficent Solved by #668

**Comment by rousseldenis** [comment]
Oups. Nearly. @max3903 See https://travis-ci.org/OCA/stock-logistics-warehouse/jobs/565401075

It's on stock_request_purchase level now

**Comment by max3903** [comment]
@rousseldenis This is fixed in https://github.com/OCA/stock-logistics-warehouse/pull/605/files#diff-91c1e592a1c1871b3f3b312df157e81eR85

**Pull request merged**
