### PR TITLE
[17.0][MIG] stock_location_lockdown: Migration to 17.

### PR DESCRIPTION
**Pull request by celm1990**

### CODE REVIEW

**Comment by celm1990** [comment]
ping @OCA/logistics-maintainers

**Review by jbaudoux — APPROVED** [review]

**Review by rousseldenis — APPROVED** [review]

**Review by jfialloss — APPROVED** [review]
Great job!!!...

**Comment by ced-adhoc** [comment]
@rousseldenis @pedrobaeza could you please check this PR? thanks!

**Pull request merged**
