### PR TITLE
[10.0] stock_quant_merge: add company_id and owner_id in merge domain

### PR DESCRIPTION
**Pull request by alexis-via**

### CODE REVIEW

**Comment by alexis-via** [comment]
company_id is present in merge domain in v8:
https://github.com/OCA/stock-logistics-warehouse/blob/8.0/stock_quant_merge/models/stock.py#L22
owner_id is an addition, but it's absolutely needed when that feature is used !

**Review by rousseldenis — APPROVED** [review]
Code review. A test can help

**Pull request merged**
