### PR TITLE
[IMP] stock_request_purchase: Add Stock request orders. Change logo

### PR DESCRIPTION
**Pull request by etobella**
Following the previous PR, Orders are added on `stock_request_purchase`.
Also, logo is changed so it follows v11 style.

### CODE REVIEW

**Comment by etobella** [comment]
@jbeficent

**Comment by JordiBForgeFlow** [comment]
Pending fix on https://github.com/etobella/stock-logistics-warehouse/pull/1

**Comment by etobella** [comment]
Fix applied

**Review by JordiBForgeFlow — APPROVED** [review]

**Comment by JordiBForgeFlow** [comment]
@mreficent can you review?

**Review by MiquelRForgeFlow — COMMENTED** [review]
There is a big error detected with the name and the sequence numbers. I told @jbeficent and he said he will fix it.

Minor comments:

- In https://github.com/OCA/stock-logistics-warehouse/blob/11.0/stock_request/views/stock_request_views.xml#L85
add <code>groups="group_stock_request_order"</code>

- In https://github.com/OCA/stock-logistics-warehouse/blob/11.0/stock_request/views/stock_request_menu.xml#L16
-> "Stock Requests Orders"

- In https://github.com/OCA/stock-logistics-warehouse/blob/11.0/stock_request/views/res_config_settings_views.xml#L11
medical?

- In https://github.com/OCA/stock-logistics-warehouse/blob/11.0/stock_request/views/stock_request_order_views.xml#L54
-> Stock Requests

- In https://github.com/OCA/stock-logistics-warehouse/blob/11.0/stock_request/models/stock_request_order.py#L72
->'Expected Date'

- In https://github.com/OCA/stock-logistics-warehouse/blob/11.0/stock_request/models/stock_request.py#L105
->'Expected Date'

- In https://github.com/OCA/stock-logistics-warehouse/blob/11.0/stock_request/models/res_config_settings.py#L14
-> Stock Requests for Purchases

- In https://github.com/OCA/stock-logistics-warehouse/blob/11.0/stock_request/views/res_config_settings_views.xml#L25
-> Enable Orders

- In https://github.com/OCA/stock-logistics-warehouse/blob/11.0/stock_request/views/stock_request_order_views.xml#L54
-> Stock Requests

- In https://github.com/OCA/stock-logistics-warehouse/blob/11.0/stock_request/views/stock_request_order_views.xml#L130
-> Stock Request Orders

- Before this line https://github.com/OCA/stock-logistics-warehouse/blob/11.0/stock_request/views/res_config_settings_views.xml#L19
add ```<h2>Orders</h2>```

- Before this line https://github.com/OCA/stock-logistics-warehouse/blob/11.0/stock_request/views/res_config_settings_views.xml#L32
add
```
<h2>Purchases</h2>
    <div class="row mt16 o_settings_container" id="stock_request_purchase">
```

- In https://github.com/OCA/stock-logistics-warehouse/blob/11.0/stock_request/views/res_config_settings_views.xml#L47
add
```
<xpath expr="//div[hasclass('settings')]/div[@data-key='purchase']" position="inside">
    <h2>Stock Requests</h2>
    <div class="row mt16 o_settings_container" id="stock_request_purchase">
        <div class="col-xs-12 col-md-6 o_setting_box">
            <div class="o_setting_left_pane">
                <field name="module_stock_request_purchase"/>
            </div>
            <div class="o_setting_right_pane">
                <label string="Enable Purchase for Stock Requests"
                       for="module_stock_request_purchase"/>
                <div class="text-muted">
                    Use Stock Requests with Purchases
                </div>
            </div>
        </div>
    </div>
</xpath>
```

**Comment by JordiBForgeFlow** [comment]
@mreficent these changes are all related to the module stock_request. I will open a separate PR.

**Review by MiquelRForgeFlow — APPROVED** [review]
Let be this changes for another PR :wink:

**Pull request merged**
