### PR TITLE
[13.0][FIX] stock_cubiscan: Default packaging quantity

### PR DESCRIPTION
**Pull request by rousseldenis**

### CODE REVIEW

**Comment by rousseldenis** [comment]
@jgrandguillaume @grindtildeath It seems weird to create default packaging with qty = 0.

I've problem with packaging_uom module with that. It seems your tests are running fine with this change.

**Comment by grindtildeath** [comment]
@rousseldenis I don't have the context here, but I poked @jgrandguillaume on our internal chat :wink:

**Review by jgrandguillaume — APPROVED** [review]
@rousseldenis I think it's ok. We did that to easily spot the lines that needs info (0 means not fulfilled). But If you prefer to set to 1 let's do this.

**Review by grindtildeath — APPROVED** [review]

**Pull request merged**
