### PR TITLE
[12.0][MIG] stock_secondary_unit

### PR DESCRIPTION
**Pull request by kittiu**
Migration to v12 (WIP)

Dependencies
- [x] product-attributes/product_secondary_unit https://github.com/OCA/product-attribute/pull/444

### CODE REVIEW

**Comment by bealdav** [comment]
product_secondary_unit is merged in v12. yeah !

**Comment by pedrobaeza** [comment]
Please add oca_dependencies.txt with `product-attribute` for proper Travis/Runbot

**Comment by kittiu** [comment]
@bealdav @pedrobaeza thank you so much.
Now this is done.

**Review by bealdav — APPROVED** [review]
OK just code review, thanks

ready to merge

**Review by rousseldenis — APPROVED** [review]
Code review

**Comment by kittiu** [comment]
More test added

**Pull request merged**
