### PR TITLE
[16.0][MIG] stock_location_orderpoint

### PR DESCRIPTION
**Pull request by mt-software-de**
Declare orderpoint on a location allowing to replenish any product with the same criteria

This forward ports https://github.com/OCA/stock-logistics-warehouse/pull/1636

### CODE REVIEW

**Comment by mt-software-de** [comment]
@jbaudoux and @rousseldenis could you also review this one?

**Comment by rousseldenis** [comment]
> @jbaudoux and @rousseldenis could you also review this one?

Yes, I think I can do it today or tomorrow

**Comment by rousseldenis** [comment]
@mt-software-de Could you move this to https://github.com/OCA/stock-logistics-orderpoint/ ?

Thanks

**Comment by mt-software-de** [comment]
> @mt-software-de Could you move this to https://github.com/OCA/stock-logistics-orderpoint/ ?
> 
> Thanks

Yes i will do this.

**Pull request closed without merging**
