### PR TITLE
[IMP] stock_cycle: save field readonly(warehouse_ids)

### PR DESCRIPTION
**Pull request by celm1990**
OCA conteo cliclico

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]
Seems legit indeed

**Review by HaraldPanten — APPROVED** [review]

**Comment by celm1990** [comment]
@pedrobaeza I see the problem is another module, you can retry please?
image

**Comment by pedrobaeza** [comment]
If the problem is still there, the retry will fail again.

**Pull request merged**
