### PR TITLE
[12.0][FIX] user can delete lines

### PR DESCRIPTION
**Pull request by jarroyomorales**
Unlink permision of stock_requests was missing for stock request users.

@HviorForgeFlow @etobella

### CODE REVIEW

**Review by HviorForgeFlow — APPROVED** [review]
Could you add module name that is commit modifying, Thanks!

**Comment by jarroyomorales** [comment]
@HviorForgeFlow Done!

**Review by rousseldenis — APPROVED** [review]

**Review by bodedra — APPROVED** [review]
LGTM :+1:

**Review by AaronHForgeFlow — APPROVED** [review]

**Comment by jarroyomorales** [comment]
@rousseldenis Hi! Can this be merged?

**Pull request merged**
