### PR TITLE
[14.0][ADD] stock_procurement_group_hook

### PR DESCRIPTION
**Pull request by LoisRForgeFlow**
This module adds a Hook to Procurement Group run method.

This is a technical module and does not provide any functionally by itself.

@ForgeFlow

### CODE REVIEW

**Comment by rousseldenis** [comment]
@LoisRForgeFlow Could you also do a PR to Odoo as this could be avoided ?

**Comment by LoisRForgeFlow** [comment]
@rousseldenis Yes, I would do that too, but for newer versions. They won't accept changes in v14.

**Comment by rousseldenis** [comment]
> @rousseldenis Yes, I would do that too, but for newer versions. They won't accept changes in v14.

If you look at commit history in v14, the amount of them last weeks is impressive... :sweat_smile:

**Comment by LoisRForgeFlow** [comment]
> > @rousseldenis Yes, I would do that too, but for newer versions. They won't accept changes in v14.
> 
> If you look at commit history in v14, the amount of them last weeks is impressive... sweat_smile

I have started with the PR in master https://github.com/odoo/odoo/pull/129389. If the feedback is positive, I'll propose the needed backports.

**Review by AaronHForgeFlow — APPROVED** [review]
Code review LG!

**Review by JoanSForgeFlow — APPROVED** [review]
LGTM!

**Pull request merged**
