### PR TITLE
[IMP] account_move_line_product: The product position on the line loo

### PR DESCRIPTION
**Pull request by nhomar**
…ks better at the end of the list view, for the sake of usability following the guideline XXXYYY http://wikipoedia says that

### CODE REVIEW

**Comment by bodedra** [comment]
@nhomar link is not working for me. Does it redirect to correct page ?

**Comment by rousseldenis** [comment]
@jbeficent What do you think ?

**Review by JordiBForgeFlow — APPROVED** [review]

**Review by rousseldenis — APPROVED** [review]

**Comment by rousseldenis** [comment]
@nhomar could you update module version?

**Comment by rousseldenis** [comment]
@nhomar

**Pull request merged**
