### PR TITLE
[11.0][MIG] stock_inventory_lockdown

### PR DESCRIPTION
**Pull request by LoisRForgeFlow**
Migration to v11.

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
@sbidoul FYI, I ran oca-gen-addon-readme in my local for this module and I got an error due to an author with a non-ascii name ("Numérigraphe"). I don't know whether this was only a local issue or it can happen after merge.

**Comment by pedrobaeza** [comment]
That's because you have installed maintainer-tools for Python 2 instead of Python 3.

**Comment by LoisRForgeFlow** [comment]
@pedrobaeza You are right! Thanks. pre-generated README added.

**Comment by sbidoul** [comment]
As Lucky @pedrobaeza Luke says :)

image

**Review by rousseldenis — APPROVED** [review]
Code review

**Review by gurneyalex — APPROVED** [review]
code looks good, tested ok

**Pull request merged**
