### PR TITLE
New module stock_inventory_lockdown

### PR DESCRIPTION
**Pull request by clonedagain**
This module is a feature extracted from stock_inventory_location, as part of fixing https://github.com/OCA/stock-logistics-warehouse/issues/134.

Ported to v8 and new API
Adopted latest OCA standards
Added tests

### CODE REVIEW

**Comment by jgrandguillaume** [comment]
Hi,

Thanks for the contribs ! I've done a functional review and it works perfectly.

:+1: 

Regards,

**Comment by gurneyalex** [comment]
:+1:

**Comment by gurneyalex** [comment]
@clonedagain could you commit --amend + push -f? It seems travis did not build this PR.

**Comment by clonedagain** [comment]
I think it did, it's just that I had to push the same commit in this PR and https://github.com/OCA/stock-logistics-warehouse/pull/155.
So maybe it shows only in the other PR.

**Comment by clonedagain** [comment]
Rebased, squashed and amended to include @lbellier in author name (unfortunately it doesn't show in github)

**Comment by clonedagain** [comment]
AAAAAAh now the tests run red! I'm undoing the squash

**Comment by clonedagain** [comment]
@gurneyalex you were right, I had to force Travis to rebuild this branch - and we found bugs thanks to that.
They're fixed now so hopefully all is fine now.

**Comment by clonedagain** [comment]
@laetitia-gangloff @lmignon your opinion is welcome, as this is a partial port to v8 of a module you use in v7

**Comment by clonedagain** [comment]
Can we merge this please ?

**Pull request merged**
