### PR TITLE
[10.0][mig] stock_reserve_sale

### PR DESCRIPTION
**Pull request by BetaUliansyah**
Modified from #190 only adjust the icon to font awesome
Works well with stock_reserve v10 #239

### CODE REVIEW

**Comment by gurneyalex** [comment]
@BetaUliansyah I just merged #239, can you rebase your PR for the CI to run?

**Review by gurneyalex — CHANGES_REQUESTED** [review]
There are errors caused by missing xmlids in the travis logs.

**Comment by rousseldenis** [comment]
@BetaUliansyah Do you plan to fix this ?

**Comment by rousseldenis** [comment]
@BetaUliansyah

**Comment by rousseldenis** [comment]
@BetaUliansyah I will close this in few days.

**Comment by rousseldenis** [comment]
Closing as no answer

**Pull request closed without merging**
