### PR TITLE
[15.0][MIG] stock_request_kanban

### PR DESCRIPTION
**Pull request by BernatPForgeFlow**

### CODE REVIEW

**Review by rousseldenis — COMMENTED** [review]
@BernatPForgeFlow Thanks for this. Could you check tests?

Do you think js changes can be backported ? If yes, could you isolate those changes in a separate commit ?

Thanks

**Comment by BernatPForgeFlow** [comment]
> @BernatPForgeFlow Thanks for this. Could you check tests?
> 
> Do you think js changes can be backported ? If yes, could you isolate those changes in a separate commit ?
> 
> Thanks

@rousseldenis No, I tried this changes in v14 and is not working. I think the migration to Owl in v15 is enough. Thank you for the review.

**Review by rousseldenis — APPROVED** [review]

**Review by LoisRForgeFlow — APPROVED** [review]

**Pull request merged**
