### PR TITLE
[13.0][ADD] stock_picking_manual_package: New module to select or create the package to do "put in pack"

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa TT37103

ping @CarlosRoca13 @victoralmau

### CODE REVIEW

**Comment by sergio-teruel** [comment]
Tests are failing due to sale_automatic_workflow_reserve_sale_stock with freezegun load module

**Review by victoralmau — APPROVED** [review]
Code review OK

**Review by CarlosRoca13 — APPROVED** [review]
Code and functional review :+1:

**Comment by rousseldenis** [comment]
@sergio-teruel @pedrobaeza Have you ever check this ? https://github.com/OCA/stock-logistics-tracking/pull/27

**Comment by pedrobaeza** [comment]
No, but I see that it's still a bit restricted: only last pack or a new one. You can't freely choose any other packs (which is our case).

**Comment by rousseldenis** [comment]
> No, but I see that it's still a bit restricted: only last pack or a new one. You can't freely choose any other packs (which is our case).

Indeed. For a further version, maybe it will be a good idea to merge concepts and move to that too less used repo :-)

**Comment by pedrobaeza** [comment]
We can still move it if you prefer.

**Comment by rousseldenis** [comment]
> We can still move it if you prefer.

That make sense in order to find convergence on that. Thanks

**Comment by pedrobaeza** [comment]
@sergio-teruel can you move the module to that repo?

**Comment by pedrobaeza** [comment]
I deleted the branch. Don't know how it got merged?!!

**Pull request merged**
