### PR TITLE
Merge the history of stock_inventory_hierarchical and stock_inventory_location

### PR DESCRIPTION
**Pull request by clonedagain**
These modules were added to the 7.0 branch after we forked the 8.0 branch.
As a first step to resolve https://github.com/OCA/stock-logistics-warehouse/issues/134, we reintroduce them with their history unchanged, and mark them un-installable.

By merging this now, you would make it easier to review the upcoming PRs regarding the migration of the modules to v7: reviewers will get a before/after view of the migration.

The merged branch was produced using `git filter-branch -f --tree-filter 'rm -rf <file or directory>' --prune-empty HEAD` on the 7.0 branch, for each file that was ever added there outside stock_inventory_hierarchical, stock_inventory_location and the link module.

### CODE REVIEW

**Comment by clonedagain** [comment]
@laetitia-gangloff I noticed that your commits on these modules were squashed when we set up the merge proposal on Launchpad, so maybe you were not credited as you should have been.
I'll make sure you are correctly credited during the v8 migration.

**Comment by laetitia-gangloff** [comment]
@clonedagain no problem ;)

:+1:

**Comment by clonedagain** [comment]
@lbellier for your information

**Comment by gurneyalex** [comment]
:+1: I'm merging this now.

**Pull request merged**
