### PR TITLE
[WIP] product cost evaluation

### PR DESCRIPTION
**Pull request by sergiocorato**
[WIP] this module add the ability to evaluate stock with different methodology (FIFO, LIFO, AVERAGE, STANDARD, LIST PRICE) for the same period, regardless of which method was chosen previously, storing in records that will be re-used for next period evaluation
[TODO]:
- use sql to reduce time of execution for large databases
- stop searching moves when previous period has already an evaluation
- create report for one single evaluation at a time

### CODE REVIEW

**Comment by dcorio** [comment]
@sergiocorato shouldn't it be wiser to have those methods elsewhere rather than stock.inventory? You'll soon end up needing the very same on other models like manufacturing order & C.

For instance, you could move those on stock.move to be more reusable.

IMO.

**Comment by sergiocorato** [comment]
> @sergiocorato shouldn't it be wiser to have those methods elsewhere rather than stock.inventory? You'll soon end up needing the very same on other models like manufacturing order & C.
> 
> For instance, you could move those on stock.move to be more reusable.
> 
> IMO.

@dcorio ok for move in the same new object created with this PR

**Comment by rousseldenis** [comment]
@sergiocorato What's the status of this ?

**Comment by sergiocorato** [comment]
@rousseldenis There is another module in testing in production, it will be proposed within 1 month probably.

**Comment by rousseldenis** [comment]
> @rousseldenis There is another module in testing in production, it will be proposed within 1 month probably.

So, closing this ?

**Comment by sergiocorato** [comment]
Yes, I close it.

**Pull request closed without merging**
