### PR TITLE
Initial inventory values to be allowed and inserted in below grid

### PR DESCRIPTION
**Pull request by dmsmkd**
This fix allows to filter and then create initial inventory values for products which did not had any inventory move before this is used.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
As explained in https://github.com/OCA/stock-logistics-warehouse/issues/76, I'm not sure if this is a good idea.

**Comment by dmsmkd** [comment]
Thanks Pedro for the quick answer. What i intend to do here is to make a initial stock values to the filtered products. This is allowed originally from Odoo and is even presented in a official video. Only thing to make sure is to set new value and not leave it to zero, since it won't make sense.

**Comment by pedrobaeza** [comment]
I would suggest then to add an option to select if you want to add zero quantity products or not before starting inventory (with a selection field or a boolean).

**Comment by ybofr** [comment]
Hi Pedro,
The logic of Odoo is wrong from a functional point of view. When preparing the list of products to inventory, I should be able to select all products from my warehouse. If some exclusion should be done, then not based on the on hand quantity, but based on the fact that the product has never been moved in the system.

So, best would be to have a checkbox asking if products with stock zero should be selected in order to keep the (wrong) odoo behaviour and to allow the standard warehouse behaviour.

Thanks and regards
Eva P.

**Comment by pedrobaeza** [comment]
OK, that what I was asking for: please add a flag or a selection to decide if you want products with zero quantity or not. These are the tasks to do in order to achieve this:
- Add the flag.
- Document this new use case on README.
- Include all possible selection cases (standard ones plus the added by this module).
- Make tests for each new possible scenario.

**Comment by jjscarafia** [comment]
Any news on this PR? Can I take it and add the flag?

**Comment by gurneyalex** [comment]
@jjscarafia If you want to for the PR, please do.

**Comment by jjscarafia** [comment]
We have make a new PR (https://github.com/OCA/stock-logistics-warehouse/pull/153) to replace this one as suggested here.

Please check functionality and then we improove README and test cases

**Comment by jjscarafia** [comment]
@dmsmkd we have made this new pr #153 of yours as suggested by @pedrobaeza and @gurneyalex.
 @ybofr For now it options are all products (new one) and default odoo one (products with stock). I agree with you that it makes more sence to use "products with moves in the location", but I think that this should be fixed on odoo with another PR. 
What do you think? We keep going with PR #153?

**Comment by rousseldenis** [comment]
Closing this as it is quite old and superseeded by #153. But closed too.

**Pull request closed without merging**
