### PR TITLE
16.0 mig stock secondary unit

### PR DESCRIPTION
**Pull request by lk-eska**
Here's another PR for stock_secondary unit

supersedes https://github.com/OCA/stock-logistics-warehouse/pull/1769

### CODE REVIEW

**Comment by rrebollo** [comment]
@lk-eska what's the current status of this??? how can I help to get this done???

**Comment by lk-eska** [comment]
you can review and merge.

**Comment by rrebollo** [comment]
@lk-eska I can't merge but I'll be doing some functional test

**Review by jbaudoux — APPROVED** [review]

**Pull request merged**
