### PR TITLE
[10.0][FIX] stock_orderpoint_uom: product_uom not stored

### PR DESCRIPTION
**Pull request by LoisRForgeFlow**
Fixes https://github.com/OCA/stock-logistics-warehouse/issues/364

`product_uom` is a related field of `product_id` so replacing for it in the constrain

cc @rousseldenis @jbeficent

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]

**Comment by LoisRForgeFlow** [comment]
@rousseldenis re-review please, I restricted to the field we are interested in

**Comment by rousseldenis** [comment]
@lreficent Aaaah yes! I missed it.

**Review by rousseldenis — APPROVED** [review]

**Comment by LoisRForgeFlow** [comment]
Ok, I swear this is the last one :laughing:, the `product_id` is also needed because you can change the product of the orderpoint to a different one with a wrong uom with impunity.

**Review by JordiBForgeFlow — APPROVED** [review]

**Comment by rousseldenis** [comment]
@lreficent Don't swear! Next time, let's have a drink ;-)

**Review by rousseldenis — APPROVED** [review]

**Comment by rousseldenis** [comment]
@lreficent Warning in runbot :

method stock.warehouse.orderpoint._check_procure_uom: @constrains parameter 'product_id.uom_id' is not a field name

**Comment by LoisRForgeFlow** [comment]
@rousseldenis may it be that the `uom_id` is efectively in the product.template, don't you think?

**Review by JordiBForgeFlow — APPROVED** [review]

**Review by rousseldenis — APPROVED** [review]

**Pull request merged**
