### PR TITLE
[14.0] [MIG] stock_location_route_description

### PR DESCRIPTION
**Pull request by JasminSForgeFlow**
Standard Migration

@ForgeFlow

### CODE REVIEW

**Review by GuillemCForgeFlow — APPROVED** [review]
LGTM! :+1:

**Review by flotho — APPROVED** [review]
LGTM, easy migration

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by LoisRForgeFlow — CHANGES_REQUESTED** [review]
Before merging, @JasminSForgeFlow can you include the fix done in v13 here https://github.com/OCA/stock-logistics-warehouse/pull/1465 ?

**Comment by JasminSForgeFlow** [comment]
> Before merging, @JasminSForgeFlow can you include the fix done in v13 here #1465 ?

done, thanks

**Review by LoisRForgeFlow — APPROVED** [review]
Thanks!

/ocabot merge nobump

**Pull request merged**
