### PR TITLE
[MIG] stock_location_warehouse: 16.0

### PR DESCRIPTION
**Pull request by ferran-S73**

### CODE REVIEW

**Review by Abranes — APPROVED** [review]
LGTM

**Review by hildickethan — APPROVED** [review]

**Comment by rousseldenis** [comment]
@ferran-S73 This is not needed anymore IMHO as already included in core : https://github.com/odoo/odoo/blob/16.0/addons/stock/models/stock_location.py#L93

**Comment by ferran-S73** [comment]
> @ferran-S73 This is not needed anymore IMHO as already included in core : https://github.com/odoo/odoo/blob/16.0/addons/stock/models/stock_location.py#L93

Hi, I'll check it out and close the PR if not needed, thanks!

**Comment by ferran-S73** [comment]
Closed as it is no longer needed in 16.0

**Pull request closed without merging**
