### PR TITLE
[12.0][MIG] stock_request_analytic

### PR DESCRIPTION
**Pull request by LoisRForgeFlow**
Standard migration.

### CODE REVIEW

**Review by AaronHForgeFlow — APPROVED** [review]
:+1:  Functional tests good. Please check travis

**Comment by LoisRForgeFlow** [comment]
Travis is good, the other travis build was a push to the wrong remote which is already fixed, but... there it is the red cross to remember for the eternity that it happened :laughing:

**Review by HviorForgeFlow — APPROVED** [review]
Code review :+1:

**Pull request closed without merging**
