### PR TITLE
[MIG] stock_vertical_lift_kardex: Migration to 14.0

### PR DESCRIPTION
**Pull request by dzungtran89**
Dependencies:
- stock_vertical_lift: https://github.com/OCA/stock-logistics-warehouse/pull/1090
- stock_location_position: https://github.com/OCA/stock-logistics-warehouse/pull/1076

### CODE REVIEW

**Review by sebalix — APPROVED** [review]
LG, waiting for dependencies to be merged (will need to update them here after)

**Review by mmequignon — APPROVED** [review]
Waiting for dependencies but LG

**Review by simahawk — CHANGES_REQUESTED** [review]
blocking only for test deps

**Review by simahawk — APPROVED** [review]

**Comment by simahawk** [comment]
@dzungtran89 build is :red_circle:

**Comment by dzungtran89** [comment]
> 
> 
> @dzungtran89 build is 🔴

hi @simahawk , I'm checking

**Comment by dzungtran89** [comment]
@simahawk I rebased the branch, the build is good now

**Pull request merged**
