### PR TITLE
[15.0][MIG] stock_putaway_method

### PR DESCRIPTION
**Pull request by Vandan-OSI**

### CODE REVIEW

**Comment by rousseldenis** [comment]
@Vandan-OSI Thanks for this. Don't forget to follow migration guide https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0

Especially commit messages.

**Comment by grindtildeath** [comment]
Is this module still used by another module?

**Comment by Vandan-OSI** [comment]
> Is this module still used by another module?

this module is Used in  OCA/field-service/fieldservice_vehicle_stock

**Review by max3903 — APPROVED** [review]

**Comment by max3903** [comment]
Deprecated. Replaced by `stock_putaway_hook`:
https://github.com/OCA/stock-logistics-workflow/tree/15.0/stock_putaway_hook

**Pull request closed without merging**
