### PR TITLE
[13.0][IMP] stock_cycle_count: auto link inventories to planned cycle counts

### PR DESCRIPTION
**Pull request by LoisRForgeFlow**
Forward port of https://github.com/OCA/stock-logistics-warehouse/pull/1159.

@ForgeFlow

### CODE REVIEW

**Comment by etobella** [comment]
Travis is failing @LoisRForgeFlow

**Comment by LoisRForgeFlow** [comment]
@etobella It is now fixed!

**Review by etobella — APPROVED** [review]

**Review by AaronHForgeFlow — APPROVED** [review]
LGTM!

**Pull request merged**
