### PR TITLE
[16.0][MIG] stock_demand_estimate_matrix: Migration to 16.0

### PR DESCRIPTION
**Pull request by kaynnan**
cc @marcelsavegnago 

#1494

### CODE REVIEW

**Comment by JordiBForgeFlow** [comment]
@kaynnan Can you add the following commit? https://github.com/ForgeFlow/stock-logistics-warehouse/commit/f890a867db1601cdcc1b38bc1ffe94ee84862af3

Improves the user interface. Otherwise the matrix and product list are not seen in full width in the wizard.

image

image

**Comment by kaynnan** [comment]
> @kaynnan Can you add the following commit? [ForgeFlow@f890a86](https://github.com/ForgeFlow/stock-logistics-warehouse/commit/f890a867db1601cdcc1b38bc1ffe94ee84862af3)
> 
> Improves the user interface. Otherwise the matrix and product list are not seen in full width in the wizard.
> 
> image
> 
> image

@JordiBForgeFlow Thanks for the improvement, I just updated the pull request including your commit

**Comment by kaynnan** [comment]
@JordiBForgeFlow Thanks for the improvement. I just updated the pull request, including your commit, and i squashed it with my commit "MIG" to keep the history more organized and clean.

**Review by LoisRForgeFlow — APPROVED** [review]
Functional review, LGTM

**Pull request merged**
