### PR TITLE
[IMP] stock_helper: add location._get_location_source_by_route

### PR DESCRIPTION
**Pull request by mt-software-de**
returns the next source location of a location by the given route

### CODE REVIEW

**Comment by mt-software-de** [comment]
@rousseldenis @jbaudoux

**Comment by rousseldenis** [comment]
@mt-software-de Maybe a little test for this ?

**Comment by mt-software-de** [comment]
> @mt-software-de Maybe a little test for this ?

done

**Review by rousseldenis — APPROVED** [review]
Code review

**Comment by mt-software-de** [comment]
@jbaudoux could you please review this one.

**Review by lmignon — APPROVED** [review]
LGTM (Code review)

**Pull request merged**
