### PR TITLE
[10.0][PYLINT] packaging_uom, sale_packaging, purchase_packaging

### PR DESCRIPTION
**Pull request by rousseldenis**

### CODE REVIEW

**Comment by rousseldenis** [comment]
Pylint fixing. Target modules are in commit message (some other are still failing).
Fast-tracking one.

**Comment by LoisRForgeFlow** [comment]
Still not :green_apple:, are you going to fix it further?

**Comment by rousseldenis** [comment]
@lreficent No, I've just fixed what's in commit message. If you are ok with this, merge it !

**Review by LoisRForgeFlow — APPROVED** [review]
Ok, those modules pylints are fixed :+1:

**Comment by rousseldenis** [comment]
@lreficent Maybe you can check stock_inventory_exclude_sublocation and account_move_line_stock_info  errors ?

**Comment by LoisRForgeFlow** [comment]
@rousseldenis yes, I saw them when checking this. Definitely, I should have a look, just noted in my to-do list.

**Pull request merged**
