### PR TITLE
14.0 mig stock production lot quantity tree

### PR DESCRIPTION
**Pull request by dani-xtendoo**
stock_production_lot_quantity_tree migraton to v 14

### CODE REVIEW

**Comment by rousseldenis** [comment]
@dani-xtendoo It seems you missed the migration commit.

See https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0#technical-method-to-migrate-a-module-from-130-to-140-branch

**Comment by kaynnan** [comment]
@dani-xtendoo Could you rebase following the  [Migration 14.0](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0) because the commit history is messed up and wrong.

**Comment by rousseldenis** [comment]
@dani-xtendoo

**Comment by rousseldenis** [comment]
@dani-xtendoo

**Pull request closed without merging**
