### PR TITLE
[13.0][MIG] stock_orderpoint_uom

### PR DESCRIPTION
**Pull request by JoanSForgeFlow**
stock_orderpoint_uom migration to v13.

cc ~ @ForgeFlow @LoisRForgeFlow

### CODE REVIEW

**Review by AaronHForgeFlow — COMMENTED** [review]
I tried on runbot to purchase dozens for a product with units uom and a reordering rule specified in units too. But the PO was created in Units, not in dozens. 
This is the reordering rule:
http://3405111-832-09a95e.runbot2.odoo-community.org/web#id=5&action=222&model=stock.warehouse.orderpoint&view_type=form&cids=&menu_id=97

and this is the PO:
http://3405111-832-09a95e.runbot2.odoo-community.org/web#id=5&action=343&model=purchase.order&view_type=form&cids=&menu_id=200


BTW Odoo has some problem with the units conversion because it is buying 200.04 units instead of 200.0 (16 dozens)

**Comment by JoanSForgeFlow** [comment]
Thank you for your review @AaronHForgeFlow !

It is necessary to define the 'Purchase measure unit' of the product as dozens for creating de PO in dozens.

In your case, 'Rounding precision' of dozens is set as 0.01: 200 units are 16.666667 dozens, this is rounded to 16.67 dozens which are 200.04 units. 
Setting 'Rounding precision' of dozens to 1.0 solves this problem.

**Review by AaronHForgeFlow — APPROVED** [review]
:+1:  LGTM

**Review by rousseldenis — APPROVED** [review]
Code review

**Review by ps-tubtim — APPROVED** [review]
Code LGTM

**Pull request merged**
