### PR TITLE
Add stock_available_lot_locked

### PR DESCRIPTION
**Pull request by clonedagain**
New module to let users "ignore" locked lots when computing the quantity available for sale.
Uses "stock_lock_lot" from https://github.com/OCA/stock-logistics-workflow/

### CODE REVIEW

**Comment by clonedagain** [comment]
@lbellier @pedrobaeza your reviews are welcome regarding this proposal.

**Comment by elicoidal** [comment]
LGTM

**Comment by clonedagain** [comment]
I've just added the translation into French, and a checkbox to install the menu from the Warehouse settings.

**Comment by clonedagain** [comment]
@gurneyalex This branch runs green on Travis but red on Runbot because it doesn't have the needed repository.
Can you give me a hint about what I should do to fix this please?

**Comment by gurneyalex** [comment]
@clonedagain I fixed this and restarted the build.

**Comment by gurneyalex** [comment]
:+1:

**Comment by clonedagain** [comment]
@lbellier is it OK for you?

**Comment by lbellier** [comment]
LGTM

**Comment by rousseldenis** [comment]
:+1: Tested on runbot

**Comment by rousseldenis** [comment]
@clonedagain Can we consider merging this and close PR ?

**Comment by clonedagain** [comment]
I haven't touched this in quite a while but I think it was fine , go ahead and merge it if it's useful.

**Comment by rousseldenis** [comment]
@gurneyalex @jbeficent

**Pull request merged**
