### PR TITLE
[15.0][MIG] account_move_line_stock_info

### PR DESCRIPTION
**Pull request by JoanMForgeFlow**
[MIG] standard migration to v. 15
@AaronHForgeFlow 
@mariadforgeflow
@bernatpforgeflow

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
@JoanMForgeFlow could you attend precommit?

**Review by AaronHForgeFlow — APPROVED** [review]
Functional tests :+1:

**Comment by JoanMForgeFlow** [comment]
> @JoanMForgeFlow could you attend precommit?

@LoisRForgeFlow  Done!

**Review by LoisRForgeFlow — APPROVED** [review]
All good! Thanks

**Pull request merged**
