### PR TITLE
[11.0][FIX] mute logger for expected Exceptions in tests

### PR DESCRIPTION
**Pull request by HviorForgeFlow**
Fix a few test on stock-logistics-warehouse report that are failing due to https://github.com/odoo/odoo/commit/1f1fa35c07299dd3940c47ac13f966ddbb1c875b

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Can you be a bit more specific in the scope of the mute and localized in the tests that is failing. All of them are failing?

**Comment by AaronHForgeFlow** [comment]
what happened here? :confused:

**Comment by HviorForgeFlow** [comment]
I tried to push a clean 11.0 branch and PR has been auto-closed. Good to know.

**Comment by yajo** [comment]
If https://github.com/odoo/odoo/pull/31699 is merged, we won't need this.

**Pull request closed without merging**
