### PR TITLE
[13.0][FIX] stock_move_location: Error on onchange origin location

### PR DESCRIPTION
**Pull request by HviorForgeFlow**
Solving error when putaway strategy is enabled on wizard.

CC @rousseldenis @LoisRForgeFlow @AdriaGForgeFlow @JoanSForgeFlow 

@ForgeFlow

### CODE REVIEW

**Review by AdriaGForgeFlow — APPROVED** [review]
Code review :+1:

**Review by AaronHForgeFlow — APPROVED** [review]
Code review :+1:

**Comment by pedrobaeza** [comment]
Please wait to merge it until @sergio-teruel confirms that this works for us.

**Comment by HviorForgeFlow** [comment]
It is just a missing underscore in a method, other changes are tests to cover it.

**Comment by pedrobaeza** [comment]
Any way, we had problems with putaway strategies. Please wait until the confirmation.

**Review by sergio-teruel — APPROVED** [review]
Yes of course!!!

**Comment by pedrobaeza** [comment]
/ocabot merge patch

Thanks!

**Pull request merged**
