### PR TITLE
[16.0] [FIX] stock_picking_product_interchangeable: Fix banner

### PR DESCRIPTION
**Pull request by Bearnard21**
Fix banner

### CODE REVIEW

**Comment by Aldeigja** [comment]
LGTM

**Review by Aldeigja — APPROVED** [review]
LGTM!

**Review by dessanhemrayev — APPROVED** [review]
LGTM

**Comment by ivs-cetmix** [comment]
/ocabot merge nobump
Merged by @ivs-cetmix 

no, not by a bot
..
.....
no, this was not triggered automatically
......
yes, I swear: it was me....
...really

8CBF0427-4C41-43B2-A05B-95A64945823F_1_102_a
D01A50CD-38DD-44E7-A8E3-2252166033FD_1_102_a
2C301076-07EC-4A14-9F63-F239C763620F_1_102_a

**Comment by CetmixGitDrone** [comment]
/ocabot merge nobump
Merged by @ivs-cetmix 

... no, not by a bot
.
..
...yes, this was a real human
...
.....no, this was not done automatically
.
I have pressed the button
yes, had to use the bot but pressed that button myself
..
..really! this was me I swear 

8CBF0427-4C41-43B2-A05B-95A64945823F_1_102_a
D01A50CD-38DD-44E7-A8E3-2252166033FD_1_102_a
2C301076-07EC-4A14-9F63-F239C763620F_1_102_a

**Comment by ValentinVinagre** [comment]
> /ocabot merge nobump Merged by @ivs-cetmix
> 
> ... no, not by a bot . .. ...yes, this was a real human ... .....no, this was not done automatically . I have pressed the button yes, had to use the bot but pressed that button myself .. ..really! this was me I swear
> 
> 8CBF0427-4C41-43B2-A05B-95A64945823F_1_102_a D01A50CD-38DD-44E7-A8E3-2252166033FD_1_102_a 2C301076-07EC-4A14-9F63-F239C763620F_1_102_a

Even so, we cannot know if it is a comment programmed by the bot or if it is really real. I don't understand this continuous public debate...

**Comment by ivs-cetmix** [comment]
> > /ocabot merge nobump Merged by @ivs-cetmix
> > ... no, not by a bot . .. ...yes, this was a real human ... .....no, this was not done automatically . I have pressed the button yes, had to use the bot but pressed that button myself .. ..really! this was me I swear
> > 8CBF0427-4C41-43B2-A05B-95A64945823F_1_102_a D01A50CD-38DD-44E7-A8E3-2252166033FD_1_102_a 2C301076-07EC-4A14-9F63-F239C763620F_1_102_a
> 
> Even so, we cannot know if it is a comment programmed by the bot or if it is really real. I don't understand this continuous public debate...

hmmm.....  @ValentinVinagre don't get me wrong but you comment looks like an automated reply generated by AI...

image

**Comment by ValentinVinagre** [comment]
> > > /ocabot merge nobump Merged by @ivs-cetmix
> > > ... no, not by a bot . .. ...yes, this was a real human ... .....no, this was not done automatically . I have pressed the button yes, had to use the bot but pressed that button myself .. ..really! this was me I swear
> > > 8CBF0427-4C41-43B2-A05B-95A64945823F_1_102_a D01A50CD-38DD-44E7-A8E3-2252166033FD_1_102_a 2C301076-07EC-4A14-9F63-F239C763620F_1_102_a
> > 
> > 
> > Even so, we cannot know if it is a comment programmed by the bot or if it is really real. I don't understand this continuous public debate...
> 
> hmmm..... @ValentinVinagre don't get me wrong but you comment looks like an automated reply generated by AI...
> 
> image

hahaha good answer from a bot :D . Trying to pass the turing test?

**Comment by ivs-cetmix** [comment]
> > > > /ocabot merge nobump Merged by @ivs-cetmix
> > > > ... no, not by a bot . .. ...yes, this was a real human ... .....no, this was not done automatically . I have pressed the button yes, had to use the bot but pressed that button myself .. ..really! this was me I swear
> > > > 8CBF0427-4C41-43B2-A05B-95A64945823F_1_102_a D01A50CD-38DD-44E7-A8E3-2252166033FD_1_102_a 2C301076-07EC-4A14-9F63-F239C763620F_1_102_a
> > > 
> > > 
> > > Even so, we cannot know if it is a comment programmed by the bot or if it is really real. I don't understand this continuous public debate...
> > 
> > 
> > hmmm..... @ValentinVinagre don't get me wrong but you comment looks like an automated reply generated by AI...
> > image
> 
> hahaha good answer from a bot :D . Trying to pass the turing test?

@ValentinVinagre sound weird but I just mentioned your profile picture :D:D:D  You may believe or not but I googled for the "suspicious Futurama" while writing a reply to you :D:D

**Comment by ValentinVinagre** [comment]
> > > > > /ocabot merge nobump Merged by @ivs-cetmix
> > > > > ... no, not by a bot . .. ...yes, this was a real human ... .....no, this was not done automatically . I have pressed the button yes, had to use the bot but pressed that button myself .. ..really! this was me I swear
> > > > > 8CBF0427-4C41-43B2-A05B-95A64945823F_1_102_a D01A50CD-38DD-44E7-A8E3-2252166033FD_1_102_a 2C301076-07EC-4A14-9F63-F239C763620F_1_102_a
> > > > 
> > > > 
> > > > Even so, we cannot know if it is a comment programmed by the bot or if it is really real. I don't understand this continuous public debate...
> > > 
> > > 
> > > hmmm..... @ValentinVinagre don't get me wrong but you comment looks like an automated reply generated by AI...
> > > image
> > 
> > 
> > hahaha good answer from a bot :D . Trying to pass the turing test?
> 
> @ValentinVinagre sound weird but I just mentioned your profile picture :D:D:D You may believe or not but I googled for the "suspicious Futurama" while writing a reply to you :D:D

okay 👍🏻

**Pull request merged**
