### PR TITLE
[16.0][IMP]stock_reserve: change parent from menu_action_stock_reservation

### PR DESCRIPTION
**Pull request by hugo-cordoba**
Hello!

I have created this pull request, to propose to move the stock reservation menu, from Products to Operations.

image

Thanks, I look forward to your feedback.

Best regards

### CODE REVIEW

**Review by kikopeiro — APPROVED** [review]
Thanks @HugoCordobaLeal , i think this position is the better choice

**Comment by hugo-cordoba** [comment]
@pedrobaeza Hi! How are you?

Whats your opinion about this change? Does it make sense to you?

Regards!

**Comment by pedrobaeza** [comment]
I don't think this is a reporting option, as you can create directly from that menu. Where it makes sense is in Operations, not in Products.

**Comment by HugoCordobaLeal** [comment]
@pedrobaeza We see well the change you propose, I have added it in 'Operations'. Where it does not make sense is in 'Products'.

Thanks!

**Comment by hugo-cordoba** [comment]
@pedrobaeza We agree with the change you propose, I have added it in 'Operations'. Where it does not make sense is in 'Products'.

Thanks!

**Review by kikopeiro — APPROVED** [review]
:+1: LGTM

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge minor

**Comment by hugo-cordoba** [comment]
thanks @kikopeiro @pedrobaeza !

**Pull request merged**
