### PR TITLE
[14.0][FIX] product_route_profile _inverse_route_ids

### PR DESCRIPTION
**Pull request by awisky**
store the selected route_profile_id on creation

### CODE REVIEW

**Review by bosd — APPROVED** [review]
LGTM! :+1:

**Review by espo-tony — APPROVED** [review]
LGTM  :+1:

**Review by CasVissers-360ERP — APPROVED** [review]

**Comment by bosd** [comment]
@pedrobaeza Can you please merge this :pray: ?

**Comment by pedrobaeza** [comment]
Merging blindly based on the existing reviews:

/ocabot merge patch

**Pull request merged**
