### PR TITLE
[14.0][MIG] account_move_line_product: Migration to 14.0

### PR DESCRIPTION
**Pull request by Mantux11**
Standard migration to `14.0`.

### CODE REVIEW

**Review by gaikaz — APPROVED** [review]

**Review by JoanMForgeFlow — APPROVED** [review]

**Review by sebalix — COMMENTED** [review]
Could you squash each kind of commits into one?
- `OCA Transbot updated translations from Transifex`
- `[UPD] Update account_move_line_product.pot`
- `[UPD] README.rst`
To reduce the size of commits history?
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0#tasks-to-do-in-the-migration

**Comment by Mantux11** [comment]
@sebalix Could you please specify which exact commits would you like me to squash? I don't see two consecutive commits of same kind.

**Review by rousseldenis — APPROVED** [review]

**Pull request merged**
