### PR TITLE
[14.0][MIG] stock_vertical_lift_empty_tray_check

### PR DESCRIPTION
**Pull request by nguyenhk99**

### CODE REVIEW

**Review by sebalix — APPROVED** [review]
LG

**Comment by sebalix** [comment]
Some commits generated by OCA-bot may be missing, I don't think it's an issue... you trash them manually? (the `[ADD] icon.png`, `[ADD] README.rst`, ...)

**Review by simahawk — APPROVED** [review]

**Comment by nguyenhk99** [comment]
> Some commits generated by OCA-bot may be missing, I don't think it's an issue... you trash them manually? (the `[ADD] icon.png`, `[ADD] README.rst`, ...)

Good morning @sebalix . I've fixup them to commit `[ADD] stock_vertical_lift_empty_tray_check: is the tray empty?`. Because the task is stated in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0.

**Comment by hailangvn** [comment]
We will work on the failed merge.

**Comment by sebalix** [comment]
@hailangvn it's OK, the build is failing due to one of my "fix" on `stock_storage_type` in OCA/wms, I have fixed it here: https://github.com/OCA/wms/pull/308

**Pull request merged**
