### PR TITLE
[FIX] stock_mts_mto_rule: _update_routes now handle multiple records

### PR DESCRIPTION
**Pull request by zaoral**
This method is called from the write() method the one who support multiple records since is a api.multi method.

I was making some test when I tried to activate the mto+mts option for multiple warehouse and the next error appears: ValueError: Expected singleton

In order to fix this error I only added a loop to manage the multiple registers.

### CODE REVIEW

**Comment by moylop260** [comment]
cc @sylvain-garancher @florian-dacosta

**Review by florian-dacosta — APPROVED** [review]
It seems good to me, thanks for the fix!

**Review by Garamotte — APPROVED** [review]
LGTM :)

**Review by LoisRForgeFlow — APPROVED** [review]
:+1:

**Pull request merged**
