### PR TITLE
13.0 mig stock_available_mrp

### PR DESCRIPTION
**Pull request by leemannd**

### CODE REVIEW

**Comment by rousseldenis** [comment]
@ps-tubtim @leemannd Which one is the good PR ?

**Comment by leemannd** [comment]
The original one is from @ps-tubtim

**Comment by rousseldenis** [comment]
> The original one is from @ps-tubtim

Yes, what I wanted to say, why this one ? If this is because you want to provide a fix, you can do a PR on @ps-tubtim repo to avoid confusion.

**Comment by leemannd** [comment]
Because github GUI prevented me to select his repo to create a PR on ecosoft branch.

**Comment by leemannd** [comment]
Feel free to close this. I have added a comment into the other PR.
Sidenote: travis is failing since more than 2 weeks on the other PR.

**Pull request closed without merging**
