### PR TITLE
[11.0][FIX] stock_secondary_unit: Fix key error in vals

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa

### CODE REVIEW

**Review by yajo — APPROVED** [review]

**Review by rousseldenis — APPROVED** [review]
Fast one. Wait for travis

**Review by chienandalu — APPROVED** [review]

**Comment by rousseldenis** [comment]
@sergio-teruel Maybe an update on module version ?

**Comment by pedrobaeza** [comment]
I can bump the version after merging

**Comment by rousseldenis** [comment]
@pedrobaeza

**Comment by pedrobaeza** [comment]
Version bumped

**Comment by rousseldenis** [comment]
@sergio-teruel Do you plan to do back and forwardport ?

**Comment by pedrobaeza** [comment]
Cherry-picked for v12 in c40f741ad54ec356c6074b13057c8c8a2f702fc5

I think this one is not in v10.

**Comment by sergio-teruel** [comment]
Sorry @rousseldenis I've been late to answer the comments...

**Pull request merged**
