### PR TITLE
[14.0][MIG] stock_packaging_calculator_packaging_type: Migration to 14.0

### PR DESCRIPTION
**Pull request by hiepnh97**
Notes:
- Depend on: [PR 1245](https://github.com/OCA/stock-logistics-warehouse/pull/1245)
- Pre-commit failed because I want to disable the conflict module.
- I will delete `test-requirement.txt` when depending [PR 1245](https://github.com/OCA/stock-logistics-warehouse/pull/1245) was Merge.

### CODE REVIEW

**Review by simahawk — COMMENTED** [review]
LG, waiting for the dep to get merged

**Comment by simahawk** [comment]
can you check runbot?

**Comment by simahawk** [comment]
@hiepnh97 pls rebase instead of merging from 14.0 :pray:

**Review by simahawk — APPROVED** [review]

**Review by TDu — APPROVED** [review]

**Pull request merged**
