### PR TITLE
[14.0][IMP] scrap_reason_code (Error fix and test coverage)

### PR DESCRIPTION
**Pull request by patrickrwilson**
This PR brings in a v13 fix where if a location isn't set on the reason or a reason isn't set then an error would show. A new test is also added to satisfy the code change.

### CODE REVIEW

**Comment by patrickrwilson** [comment]
@bodedra @dreispt @rousseldenis third times a charm...hopefully :). Once checks are completed, this should be ready for your reviews.

**Comment by rousseldenis** [comment]
Ok.

The problem recreating new PR at each time is losing preceding comments...

What is your problem exactly to modify an existing one?

**Comment by patrickrwilson** [comment]
It's most likely my lack of git, but once I would cherry-pick I couldn't revert that commit and then trying to reset head would prevent squashing stating I couldn't squash a merge commit with it stating something like a merge commit cannot exist among squash commits.

**Review by bodedra — APPROVED** [review]
Functional reviewed. 👍 

Scrapped parts from Inventory & MO level with different scrap reason code.

This PR includes FW fix + unit test.

**Review by max3903 — APPROVED** [review]

**Comment by rousseldenis** [comment]
@max3903 Last Pr's comment was not attended...

**Comment by rousseldenis** [comment]
https://github.com/OCA/stock-logistics-warehouse/pull/1416#discussion_r870320178

**Comment by rousseldenis** [comment]
@patrickrwilson Please modify this accordingly

**Comment by rousseldenis** [comment]
@max3903 I've stopped travis build

**Comment by rousseldenis** [comment]
Ok, great. Could you just improve commit messages like '[IMP] scrap_reason_code: (...) ? Thanks

**Comment by rousseldenis** [comment]
Hint: This can be done through :

`git rebase -i HEAD~3`

change 'pick' lines by 'r' (see help there), save and then you'll be prompted to reword each commit.

Then, `git push origin HEAD -f`

**Comment by patrickrwilson** [comment]
> Ok, great. Could you just improve commit messages like '[IMP] scrap_reason_code: (...) ? Thanks

Thanks for the guidence, does that look better? (I didn't change the cherry picked commit, should I?)

**Review by rousseldenis — APPROVED** [review]

**Pull request merged**
