### PR TITLE
Add README.rst and remove description from __openerp__.py

### PR DESCRIPTION
**Pull request by Doscaal**

### CODE REVIEW

**Comment by yvaucher** [comment]
CLA was just signed

**Comment by yvaucher** [comment]
:+1:

**Comment by max3903** [comment]
Is it really necessary to mention the dependencies in the installation steps ?

**Comment by Doscaal** [comment]
You mean we don't have to set this dependencie at all or it doesn't have to
be in this step?

In my view, stock module dependencie is obvious but  how to define which is
an obvious dependencie and one it isn't.

2015-06-01 14:43 GMT+02:00 max3903 notifications@github.com:

> Is it really necessary to mention the dependencies in the installation
> steps ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/OCA/stock-logistics-warehouse/pull/53#issuecomment-107427818
> .

## 

## 

---

Ce message et toutes les pièces jointes (ci-après le "message") sont établis à
l'intention exclusive de ses destinataires et sont confidentiels. Si vous
recevez ce message par erreur, merci de le détruire et d'en avertir
immédiatement l'expéditeur. Toute utilisation de ce message non conforme à sa
destination, toute diffusion ou toute publication, totale ou partielle, est
interdite, sauf autorisation expresse. L'internet ne permettant pas d'assurer
l'intégrité de ce message, SYLEAM décline toute responsabilité au titre de ce
message, dans l'hypothèse où il aurait été modifié.

This message and any attachments (the "message") is intended solely for the
addressees and is confidential. If you receive this message in error, please
delete it and immediately notify the sender. Any use not in accord with its
purpose, any dissemination or disclosure, either whole or partial, is prohibited
except after formal approval. The internet can not guarantee the integrity of
this message. SYLEAM cannot therefore be liable for the message if modified.

---

**Comment by max3903** [comment]
I mean they don't need to be in this step.

**Comment by Doscaal** [comment]
I remove this section from my previous commit.

**Comment by pedrobaeza** [comment]
:+1:

**Pull request merged**
