### PR TITLE
[FIX] missing openerp namespace

### PR DESCRIPTION
**Pull request by bealdav**
it's only for me that it break the whole branch ?

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Remove vim specific line

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Please squash on merge

**Comment by bealdav** [comment]
I don't have access to merge button and then squash
https://github.com/blog/2243-rebase-and-merge-pull-requests
could you do it for me ? thanks

**Comment by pedrobaeza** [comment]
One doubt I have now: why making these changes if the module is not migrated?

**Comment by bealdav** [comment]
because when you run your server, this module code is parsed, whatever installed or not, and server fails to be initialized.

**Comment by pedrobaeza** [comment]
Uhm, curious. OK then.

**Comment by bealdav** [comment]
I think you can fast track too, thanks

**Comment by pedrobaeza** [comment]
OK, fast-tracking then

**Pull request merged**
