### PR TITLE
7.0 fix travis

### PR DESCRIPTION
**Pull request by gurneyalex**
fix flake 8 errors:
- stock_inventory_location: move binary operators at end of line
- stock_inventory_hierarchical:  imports before global scope variables 

fix test crash:
- stock_location_inactive: fix bad api use in onchange method

### CODE REVIEW

**Comment by guewen** [comment]
:+1:

**Comment by pedrobaeza** [comment]
:+1:

**Comment by laetitia-gangloff** [comment]
@gurneyalex why do you change the place of PARENT_VALUES ?

**Comment by gurneyalex** [comment]
@laetitia-gangloff to silence flake8 complaining about code before the imports. 

See https://travis-ci.org/OCA/stock-logistics-warehouse/jobs/109293094#L367

The symbol is still available at the same place for other addons to import.

**Comment by laetitia-gangloff** [comment]
Ook, so I don't need to update my custom code !
Thank you.

:+1:

**Pull request merged**
