### PR TITLE
[12.0][MIG] stock_orderpoint_manual_procurement

### PR DESCRIPTION
**Pull request by kittiu**
Module migrated to v12

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
@kittiu Please check warnings in runbot logs

**Review by LoisRForgeFlow — APPROVED** [review]
Tested locally, LGTM :+1:

**Review by bodedra — APPROVED** [review]
LGTM :+1:

**Comment by bodedra** [comment]
@kittiu Appreciate your work. IMO we can avoid cosmetic changes on next module migration.  :wink:  That's not really important on migration. Reference: https://github.com/OCA/stock-logistics-warehouse/pull/557/commits/eefe3025a5045a0eba484eee345d203d844531dc#diff-caa1ed47e650d4d52dc2c98f85bee472R99

**Review by rousseldenis — CHANGES_REQUESTED** [review]
@kittiu Could you amend commit message ?

**Comment by kittiu** [comment]
> @kittiu Could you amend commit message ?

Done

**Review by rousseldenis — APPROVED** [review]

**Pull request merged**
