### PR TITLE
[8.0] [NEW] [stock_orderpoint_demand_estimate]

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
# 
# Stock Orderpoint Demand Estimate

This module allows to create demand estimates associated to orderpoints. It
does not provide in itself any specific usage of the estimates.
# Installation

This module relies on the OCA module '2D matrix for x2many fields', and can
be downloaded from:
- Github: https://github.com/OCA/web/tree/8.0/web_widget_x2many_2d_matrix
# Usage

Go to 'Warehouse / Configuration / Demand Estimate Periods' and define your
estimating periods (monthly or weekly).

Go to 'Warehouse / Demand Planning / Create Demand Estimates' to create or
update your demand estimates.

Go to 'Warehouse / Demand Planning / Demand Estimates' to review the
estimates created.

### CODE REVIEW

**Comment by JordiBForgeFlow** [comment]
cc @roodin

**Comment by Cedric-Pigeon** [comment]
@jbeficent Do you plan to finish this PR ?

**Comment by rousseldenis** [comment]
@jbeficent

**Comment by LoisRForgeFlow** [comment]
We are not going to finish this. Let's close it and if anyone is interested can do a backport from v9, that would be probably better than finishing this.

**Pull request closed without merging**
