### PR TITLE
[14.0][IMP] stock_location_orderpoint: index and view

### PR DESCRIPTION
**Pull request by mt-software-de**
With this i will backport. 
https://github.com/OCA/stock-logistics-orderpoint/pull/3/commits/a0dc2e7ddeb4b140afb5e9b3fb44c0aa8e994503
and
https://github.com/OCA/stock-logistics-orderpoint/pull/3/commits/b413f6d8fd4b15f908e163256edac0f0ea63358d

@jbaudoux @rousseldenis

### CODE REVIEW

**Comment by mt-software-de** [comment]
ping @rousseldenis @jbaudoux

**Comment by rousseldenis** [comment]
@mt-software-de You could have cherry-picked my original commit for index.

**Comment by mt-software-de** [comment]
> @mt-software-de You could have cherry-picked my original commit for index.

done

**Review by rousseldenis — APPROVED** [review]

**Review by jbaudoux — APPROVED** [review]

**Pull request merged**
