### PR TITLE
[16.0][ADD] stock_storage_category_capacity_name

### PR DESCRIPTION
**Pull request by rousseldenis**
As in core, Odoo does not implement record name, I've added this.

I did a PR on Odoo too : https://github.com/odoo/odoo/pull/115275

### CODE REVIEW

**Review by lmignon — APPROVED** [review]
LGTM (Code review + functional test via https://github.com/OCA/wms/pull/470)

**Comment by rousseldenis** [comment]
@jbaudoux

**Review by jbaudoux — APPROVED** [review]
LGTM

**Pull request merged**
