### PR TITLE
[17.0][MIG] stock_demand_estimate_matrix

### PR DESCRIPTION
**Pull request by JasminSForgeFlow**
Standard Migration

@ForgeFlow

Depends on:

- https://github.com/OCA/web/pull/2756
- https://github.com/OCA/stock-logistics-warehouse/pull/2182

### CODE REVIEW

**Comment by MateuGForgeFlow** [comment]
Hi @JasminSForgeFlow,
Dependency merged!

**Review by sebalix — APPROVED** [review]

**Comment by LoisRForgeFlow** [comment]
@JasminSForgeFlow I just rebased but test are actually failing, could you have a look?

**Review by LoisRForgeFlow — APPROVED** [review]
Functional test :+1:

**Pull request merged**
