### PR TITLE
[15.0] [MIG] stock_location_route_description

### PR DESCRIPTION
**Pull request by JasminSForgeFlow**
Standard Migration

@ForgeFlow

### CODE REVIEW

**Review by GuillemCForgeFlow — APPROVED** [review]
LGTM! :smile: Functional and code review

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by JuanyDForgeflow — APPROVED** [review]
Functional Review LGTM

**Review by AaronHForgeFlow — APPROVED** [review]
LGTM

**Review by LoisRForgeFlow — CHANGES_REQUESTED** [review]
Same here, could you include https://github.com/OCA/stock-logistics-warehouse/pull/1465?

**Comment by JasminSForgeFlow** [comment]
> Same here, could you include #1465?

Done, thanks

**Review by LoisRForgeFlow — APPROVED** [review]
Thanks!

/ocabot merge nobump

**Pull request merged**
