### PR TITLE
[13.0][MIG] stock_quant_reservation_info_mrp

### PR DESCRIPTION
**Pull request by SergiCForgeFlow**
Standard migration from 14.0 to 13.0. This module depends on the stock_quant_reservation_info module.

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]

**Comment by rousseldenis** [comment]
@SergiCForgeFlow To easy review, you can embed the depending PRs following https://github.com/OCA/maintainer-tools/wiki/Use-temporary-reference%28s%29-to-another-pull-request%28s%29

With that, tests will be run correctly and runbot will be available

**Comment by LoisRForgeFlow** [comment]
@SergiCForgeFlow Can you rebase this PR? the dependency has been merged

**Comment by SergiCForgeFlow** [comment]
> @SergiCForgeFlow Can you rebase this PR? the dependency has been merged

Done!

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM

**Pull request merged**
