### PR TITLE
[13.0][IMP] stock_request, consolidate imp/fix from v12

### PR DESCRIPTION
**Pull request by kittiu**
- [X] Improve cancellation detection https://github.com/OCA/stock-logistics-warehouse/pull/895
- [x] fix archived search view https://github.com/OCA/stock-logistics-warehouse/pull/1040
- [x] stock_request:- Improved _compute_qty code https://github.com/OCA/stock-logistics-warehouse/pull/960

### CODE REVIEW

**Comment by kittiu** [comment]
Ready for review.

Can this be fast forward?

**Review by Saran440 — APPROVED** [review]
Code Reviewed. 👍 
you should squash commit into 1.

**Comment by kittiu** [comment]
> Code Reviewed. 
> you should squash commit into 1.

It is my intention to preserve the commit history for those I cherry-pick. But I already melt my own fix into 1 commit.

**Pull request merged**
