### PR TITLE
[14.0][MIG] stock_inventory_preparation_filter

### PR DESCRIPTION
**Pull request by ivantodorovich**
Standard migration

### CODE REVIEW

**Review by hparfr — APPROVED** [review]

**Review by bguillot — APPROVED** [review]
Tested works fine

**Comment by pedrobaeza** [comment]
Please squash version bump commits with the one that provokes them, and also follow the migration procedure for doing the pre-commit BEFORE the migration: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0

**Review by pedrobaeza — DISMISSED** [review]
See my previous comment

**Comment by ivantodorovich** [comment]
I've squashed all of them together, given that pre-commit didn't introduce that many changes and that it was already reviewed; it's easier than fixing conflicts due to reordering commits

I'll try to remember running pre-commit before the migration in the future. I use odoo-module-migrate and I always forget about pre-commit until it's too late :sweat_smile:

**Review by HaraldPanten — APPROVED** [review]

**Comment by ivantodorovich** [comment]
Can we merge this?

**Pull request merged**
