### PR TITLE
Re-license stock_packaging_calculator w/ LGPL

### PR DESCRIPTION
**Pull request by simahawk**

### CODE REVIEW

**Review by jgrandguillaume — APPROVED** [review]
LGTM, thx Simone we need this LGPL for DDMRP stack for info

**Review by marcelsavegnago — APPROVED** [review]

**Comment by grindtildeath** [comment]
While there's a PR for it, wouldn't it make sense to move the module to product-attribute repo, where all the other modules related to product and packaging are? 
Also IMO renaming the module to product_packaging_calculator would make sense as we don't really depend on stock modules.

My 0.02 $ :wink:

**Review by HaraldPanten — APPROVED** [review]
minor changes

**Comment by simahawk** [comment]
@grindtildeath you might be right but we don't have enough time to move it especially because it adds little value AFAIS.
You can add it to the ROADMAP if want.

**Pull request merged**
