### PR TITLE
[13.0][MIG] stock_account_inventory_discrepancy

### PR DESCRIPTION
**Pull request by LoisRForgeFlow**
Standard migration.

@ForgeFlow

### CODE REVIEW

**Review by AaronHForgeFlow — APPROVED** [review]
:+1:  Tested on local

**Comment by rousseldenis** [comment]
@LoisRForgeFlow Could you fix tests and pre-commit ?

**Comment by LoisRForgeFlow** [comment]
@rousseldenis The tests are finally fixed! Better late than never :) Could you have a look?

**Comment by rousseldenis** [comment]
> @rousseldenis The tests are finally fixed! Better late than never :) Could you have a look?

Great, is that warning in a dependency of this ? 

image

**Comment by LoisRForgeFlow** [comment]
@rousseldenis that was missing, it is now fixed :rocket:

**Review by rousseldenis — APPROVED** [review]

**Comment by rousseldenis** [comment]
ready ?

**Comment by LoisRForgeFlow** [comment]
ready!

/ocabot merge nobump

**Pull request merged**
