### PR TITLE
[WMS][12.0] Add stock_reserve_packaging - Alpha version

### PR DESCRIPTION
**Pull request by guewen**
Reservation by complete packaging first, then apply the removal
strategy.

This is the first working version. When working on the other modules touching
the removal strategies, we may need to make a common base, but until then, we
aren't sure of what the lowest common denominator is (first: get a working
version, two: refactor; we are clearly at step one :).

Also, I had to duplicate many lines from the stock module to get this working.
I'll open a PR on master to have better abstractions on the next release, hopefully.

Related to #621 and #685

### CODE REVIEW

**Comment by guewen** [comment]
Extraction of the methods for master: https://github.com/odoo/odoo/pull/36385

**Comment by guewen** [comment]
The build error should be fixed by https://github.com/OCA/product-attribute/pull/500

**Review by jgrandguillaume — APPROVED** [review]
LGTM, functional tests ok on my side

**Comment by guewen** [comment]
Now handled as a removal strategy in reservation rules (https://github.com/OCA/stock-logistics-warehouse/pull/683). Closing, any interested people: feel free to reopen.

**Pull request closed without merging**
