### PR TITLE
[11.0][IMP] stock_request: allow to request from all locations types.

### PR DESCRIPTION
**Pull request by LoisRForgeFlow**
By default only internal and transit locations are allowed in Stock Request and Orders.

### CODE REVIEW

**Review by max3903 — APPROVED** [review]
LGTM. No test

**Review by etobella — APPROVED** [review]
LGTM :+1:
Tested and works as expected.

**Comment by rousseldenis** [comment]
@lreficent Maybe a little test to highlight these changes ?

**Comment by LoisRForgeFlow** [comment]
@rousseldenis 100% diff coverage :wink:

**Review by rousseldenis — APPROVED** [review]

**Comment by rousseldenis** [comment]
@lreficent Don't forget to squash

**Comment by LoisRForgeFlow** [comment]
Squashed on merge.

**Pull request merged**
