### PR TITLE
[10.0][MIG] stock_quant_merge

### PR DESCRIPTION
**Pull request by LoisRForgeFlow**
Migration to v10:
* Odoo tags and imports.
* Fix new method calls.
* Rename files to respect convenction.
* Fix moved methods.

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]
:+1: Code review

**Comment by JordiBForgeFlow** [comment]
cc @darshan-serpent can you review please?

**Comment by alexis-via** [comment]
It doesn't work because quants_unreserve() has been switched from @api.model to @api.multi (default decorator in v10) in the official stock module.

**Comment by alexis-via** [comment]
A rapid fix, which may not be the best: https://github.com/Eficent/stock-logistics-warehouse/pull/9

**Comment by LoisRForgeFlow** [comment]
Thanks @alexis-via , you were right and I've added your changes. :+1:

**Comment by alexis-via** [comment]
Sorry, I left a pep8 error in my PR:

stock_quant_merge/models/stock_move.py:5:1: F401 'odoo.api' imported but unused

Then travis will be green and we can merge

**Comment by alexis-via** [comment]
My Fix PR to make travis green: https://github.com/Eficent/stock-logistics-warehouse/pull/11

**Comment by LoisRForgeFlow** [comment]
@alexis-via I just pushed the fix!

Give your review when the test are finished and we can merge :wink:

**Review by alexis-via — APPROVED** [review]

**Review by lmignon — APPROVED** [review]
:+1:  LGTM (Code only)

**Pull request merged**
