### PR TITLE
[16.0][MIG] stock_valuation_layer_total_value: Migration to 16.0 and modify test

### PR DESCRIPTION
**Pull request by PauBForgeFlow**

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]
Code review

**Comment by rousseldenis** [comment]
@PauBForgeFlow Could you rebase (I have fixed pre-commit) ?

**Comment by PauBForgeFlow** [comment]
> @PauBForgeFlow Could you rebase (I have fixed pre-commit) ?

Done

**Review by ChrisOForgeFlow — APPROVED** [review]
LGTM

**Review by andreampiovesana — APPROVED** [review]
LGTM
merge?

**Pull request merged**
