### PR TITLE
[16.0] [ADD] stock_move_auto_assign_auto_release

### PR DESCRIPTION
**Pull request by lmignon**
* [x] depends on https://github.com/OCA/wms/pull/478

Automatically release stock moves when a move is set to "done" and the product
becomes available.

It uses queue jobs to release the moves in order to have a minimal impact
on the user operations.

The conditions to trigger the check are:

* A job to check the availability of stock moves has been created

At this point, jobs are generated:

* One job per product
* Any available moves releasable are processed

### CODE REVIEW

**Comment by rousseldenis** [comment]
@lmignon Could you remove test-requirement commit and rebase ?

**Comment by lmignon** [comment]
@rousseldenis test-requirements removed

**Review by rousseldenis — APPROVED** [review]

**Review by jbaudoux — APPROVED** [review]
LG

**Pull request merged**
