### PR TITLE
[15.0][MIG] stock_cycle_count

### PR DESCRIPTION
**Pull request by ArnauCForgeFlow**
Migration to 15.0

### CODE REVIEW

**Comment by rousseldenis** [comment]
@ArnauCForgeFlow To help review, don't hesitate to put depending PR's links in this PR description.

Moreover, you can add it through : https://github.com/OCA/maintainer-tools/wiki/Use-temporary-reference%28s%29-to-another-pull-request%28s%29

In order to make tests running and be able to launch runboat

**Comment by LoisRForgeFlow** [comment]
stock_inventory_exclude_sublocation is no longer a dependency after the change done in https://github.com/OCA/stock-logistics-warehouse/pull/1991

**Review by LoisRForgeFlow — APPROVED** [review]
As a strict migration, I think this one is good to go.

After this, more improvements to come in https://github.com/OCA/stock-logistics-warehouse/pull/1997.

**Review by JoanSForgeFlow — APPROVED** [review]
Functional review! LGTM!

**Comment by LoisRForgeFlow** [comment]
@ArnauCForgeFlow litte detail

Remove the duplicated Assigned to from views

image

**Comment by ArnauCForgeFlow** [comment]
@LoisRForgeFlow Done! also removed company_id field since it is now declared in stock_inventory module.

**Comment by LoisRForgeFlow** [comment]
Thanks!

/ocabot merge nobump

**Pull request merged**
