### PR TITLE
[FIX] stock_quant_manual_assign: Search in all child locations

### PR DESCRIPTION
**Pull request by pedrobaeza**
With previous code, only 2 level locations were found, but not deeper.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please review @oihane @Daniel-CA @lbellier @clonedagain

**Comment by oihane** [comment]
LGTM :+1:

**Comment by Daniel-CA** [comment]
:+1:

**Comment by agaldona** [comment]
:+1:

**Pull request merged**
