### PR TITLE
[16.0][MIG] stock_production_lot_quantity_tree: Migration to 16.0

### PR DESCRIPTION
**Pull request by AdrianaSaiz**
Standard migration

### CODE REVIEW

**Review by ghost — APPROVED** [review]
Please change PR title 
from: `[16.0] [MIG] stock production lot quantity tree: Migration to 16.0` 
to: `[16.0][MIG] stock_production_lot_quantity_tree: Migration to 16.0`

I will leave it approved even so since the change does not affect the migration.

**Review by LuisNovalio — APPROVED** [review]
I leave proof of how it looks:


https://github.com/user-attachments/assets/b1dfff02-b4d0-4b9b-9f38-fba55c103618

Greetings.

**Review by EmilioPascual — APPROVED** [review]
LGTM. Functional and code review.

**Comment by RodrigoBM** [comment]
can @EmilioPascual merge it?

**Comment by EmilioPascual** [comment]
I haven't merge permissions. Maybe a member of @OCA/logistics-maintainers can merge.

**Review by jbaudoux — APPROVED** [review]
@rousseldenis You are the maintainer. Can you merge it if good for you?

**Pull request merged**
