### PR TITLE
[17.0][MIG] product route profile: Migration to 17.0

### PR DESCRIPTION
**Pull request by StefanRijnhart**
Based on unmerged https://github.com/OCA/stock-logistics-warehouse/pull/1775
Includes https://github.com/OCA/stock-logistics-warehouse/pull/1939

### CODE REVIEW

**Review by bosd — APPROVED** [review]
LGTM

**Review by jbaudoux — COMMENTED** [review]
I would drop the binary files from the commit that introduced them

**Comment by StefanRijnhart** [comment]
@jbaudoux That would be the best but it's not possible without a hard reset of the target branch, because the files were added in a commit related to another module. It was discussed in https://odoo-community.org/groups/contributors-15/contributors-1946820, and it was agreed that the cons would outweigh the pros.

**Comment by rousseldenis** [comment]
> @jbaudoux That would be the best but it's not possible without a hard reset of the target branch, because the files were added in a commit related to another module. It was discussed in https://odoo-community.org/groups/contributors-15/contributors-1946820, and it was agreed that the cons would outweigh the pros.

In fact, in this case, base 17.0 branch does not contain those files. So, please remove them.

**Comment by StefanRijnhart** [comment]
@rousseldenis In that case, the files have been removed in another PR. I rebased onto 17.0 so that the removal of the files is no longer visible in the diff.

**Review by jbaudoux — APPROVED** [review]

**Pull request merged**
